<?php
declare(strict_types=1);

function mcpReportsDescriptor(): array {
  $id=array('type'=>'integer','minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$boolean=array('type'=>'boolean');$short=array('type'=>'string','minLength'=>1,'maxLength'=>255);$parameters=array('type'=>'object','maxProperties'=>MCP_REPORTS_PARAMETER_LIMIT,'additionalProperties'=>true);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','maxLength'=>100),'objectClass'=>array('type'=>'string','maxLength'=>100),'id'=>$id,'externalDelivery'=>$boolean),array('action'));
  $item=mcpObjectSchema(array('index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted')),'id'=>$id,'version'=>$version),array('index','status','id'));
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','items','effects'));
  $delete=mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id','expectedVersion')))),array('items'));
  $operation=array('type'=>'string','enum'=>array('create','update'));
  $favorite=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'reportId'=>$id,'sortOrder'=>array('type'=>'integer','minimum'=>1),'idle'=>$boolean,'parameters'=>$parameters),array('operation','reportId'));
  $column=mcpObjectSchema(array('field'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'attribute'=>array('type'=>'string','maxLength'=>100),'hidden'=>$boolean,'widthPercent'=>array('type'=>'integer','minimum'=>0,'maximum'=>100)),array('field'));
  $layout=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'objectClass'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]*$','maxLength'=>100),'name'=>$short,'comment'=>array('type'=>'string','maxLength'=>4000),'shared'=>$boolean,'sortOrder'=>array('type'=>'integer','minimum'=>1),'columns'=>array('type'=>'array','maxItems'=>200,'items'=>$column)),array('operation','objectClass','name'));
  $pin=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'reportId'=>$id,'sortOrder'=>array('type'=>'integer','minimum'=>1),'idle'=>$boolean),array('operation','reportId'));
  $batch=function(array $schema):array{return mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$schema)),array('items'));};
  $render=mcpObjectSchema(array('idReport'=>$id,'format'=>array('type'=>'string','enum'=>array('pdf','png','jpeg','csv','json')),'parameters'=>$parameters),array('idReport'));
  $renderResult=mcpObjectSchema(array('ok'=>$boolean,'reportId'=>$id,'reportName'=>array('type'=>'string','maxLength'=>500),'format'=>array('type'=>'string','enum'=>array('pdf','png','jpeg','csv','json')),'mediaType'=>array('type'=>'string','maxLength'=>100),'bytes'=>array('type'=>'integer','minimum'=>1),'maxBytes'=>array('type'=>'integer','minimum'=>1),'parametersHash'=>array('type'=>'string','pattern'=>'^[a-f0-9]{64}$'),'resource'=>array('type'=>'string','pattern'=>'^projeqtor://jobs/[0-9]+/result$'),'path'=>array('type'=>'string','maxLength'=>500),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','reportId','reportName','format','mediaType','bytes','maxBytes','parametersHash','resource','path','effects'));
  $parameterMeta=mcpObjectSchema(array('name'=>array('type'=>'string','maxLength'=>100),'type'=>array('type'=>'string','maxLength'=>100),'required'=>$boolean,'defaultValue'=>array('type'=>array('string','integer','number','boolean','null'))),array('name','type','required'));
  $reportMeta=mcpObjectSchema(array('id'=>$id,'name'=>array('type'=>'string','maxLength'=>500),'categoryId'=>$id,'orientation'=>array('type'=>'string','maxLength'=>10),'formats'=>array('type'=>'array','items'=>array('type'=>'string')),'parameters'=>array('type'=>'array','maxItems'=>200,'items'=>$parameterMeta)),array('id','name','categoryId','orientation','formats','parameters'));
  $catalogResult=mcpObjectSchema(array('ok'=>$boolean,'reports'=>array('type'=>'array','items'=>$reportMeta),'count'=>array('type'=>'integer','minimum'=>0),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','reports','count','effects'));
  $widget=mcpObjectSchema(array('key'=>array('type'=>'string','maxLength'=>100),'value'=>array('type'=>'string','maxLength'=>1000)),array('key','value'));
  $dashboardResult=mcpObjectSchema(array('ok'=>$boolean,'dashboard'=>array('type'=>'string','enum'=>array('project','ticket','requirement')),'projectId'=>array('type'=>array('integer','null'),'minimum'=>1),'generatedAt'=>array('type'=>'string','maxLength'=>40),'widgets'=>array('type'=>'array','maxItems'=>200,'items'=>$widget),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','dashboard','projectId','generatedAt','widgets','effects'));
  $scheduleItem=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','delete')),'id'=>$id,'expectedVersion'=>$version,'reportId'=>$id,'name'=>$short,'frequency'=>array('type'=>'string','enum'=>array('daily','weekly','monthly')),'hour'=>array('type'=>'integer','minimum'=>0,'maximum'=>23),'minute'=>array('type'=>'integer','minimum'=>0,'maximum'=>59),'day'=>array('type'=>'integer','minimum'=>1,'maximum'=>28),'parameters'=>$parameters,'idle'=>$boolean),array('operation'));
  $deliveryResult=mcpObjectSchema(array('ok'=>$boolean,'scheduleId'=>$id,'status'=>array('type'=>'string','enum'=>array('sent')),'recipientResourceId'=>$id,'effects'=>array('type'=>'array','items'=>$effect)),array('ok','scheduleId','status','recipientResourceId','effects'));
  $guard=array('preview'=>'mcpReportsPreview','confirmationRequired'=>true);
  return array(
    'report.start'=>mcpActionSpec($render,$renderResult,'read',true,'mcpReportsStartWorker',array(),'reports.render.legacy',array('retryPolicy'=>'safe','availability'=>'mcpReportsRenderAvailable')),
    'reports.render'=>mcpActionSpec($render,$renderResult,'read',true,'mcpReportsRenderWorker',array('view:print'),'reports.render',array('retryPolicy'=>'safe','availability'=>'mcpReportsRenderAvailable')),
    'reports.catalog.read'=>mcpActionSpec(mcpObjectSchema(array('idReport'=>$id)),$catalogResult,'read',false,'mcpReportsCatalogAction',array(),'reports.catalog.read'),
    'reports.dashboard.read'=>mcpActionSpec(mcpObjectSchema(array('dashboard'=>array('type'=>'string','enum'=>array('project','ticket','requirement')),'projectId'=>$id),array('dashboard')),$dashboardResult,'read',false,'mcpReportsDashboardAction',array('tool:getParamDashboard','tool:jsonProjectDashboard','tool:jsonProjectDashboardDetail'),'reports.dashboard.read'),
    'reports.favorite.manage'=>mcpActionSpec($batch($favorite),$batchResult,'write',false,'mcpReportsFavoriteAction',array('tool:saveReportAsFavorite','tool:saveReportFavoriteOrder'),'reports.favorite.manage'),
    'reports.favorite.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpReportsDeleteOwnedAction',array('tool:removeFavoriteReport'),'reports.favorite.delete',$guard),
    'reports.layout.manage'=>mcpActionSpec($batch($layout),$batchResult,'administrative',false,'mcpReportsLayoutAction',array('tool:backupReportLayout','tool:saveReportLayout','tool:moveReportLayoutColumn','tool:shareReportLayout'),'reports.layout.manage',$guard),
    'reports.layout.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpReportsDeleteOwnedAction',array('tool:removeReportLayout'),'reports.layout.delete',$guard),
    'reports.dashboard.pin'=>mcpActionSpec($batch($pin),$batchResult,'write',false,'mcpReportsDashboardPinAction',array('tool:saveReportInToday'),'reports.dashboard.pin'),
    'reports.dashboard.unpin'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpReportsDeleteOwnedAction',array('tool:saveTodayDeleteReport'),'reports.dashboard.unpin',$guard),
    'reports.schedule'=>mcpActionSpec($batch($scheduleItem),$batchResult,'external',false,'mcpReportsScheduleAction',array('tool:saveAutoSendReport'),'reports.schedule',$guard),
    'reports.delivery.send'=>mcpActionSpec(mcpObjectSchema(array('scheduleId'=>$id,'expectedVersion'=>$version),array('scheduleId','expectedVersion')),$deliveryResult,'external',true,'mcpReportsDeliveryWorker',array(),'reports.delivery.send',array_merge($guard,array('retryPolicy'=>'recovery_required')))
  );
}
