<?php
declare(strict_types=1);

function mcpFinancialModuleDescriptor(): array {
  $id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);
  $version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$date=array('type'=>array('string','null'),'pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');
  $datetime=array('type'=>array('string','null'),'maxLength'=>30);$text=array('type'=>array('string','null'),'maxLength'=>4000);$short=array('type'=>array('string','null'),'maxLength'=>400);
  $money=array('type'=>array('number','null'),'minimum'=>-999999999999);$quantity=array('type'=>array('number','null'),'minimum'=>0);$boolean=array('type'=>'boolean');
  $operation=array('type'=>'string','enum'=>array('create','update','upsert','delete'));$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
  $saved=array('type'=>array('object','null'),'properties'=>array('id'=>$id,'_version'=>$version),'required'=>array('id','_version'),'additionalProperties'=>false);
  $error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string'),'expectedVersion'=>$version,'actualVersion'=>$version,'invalidFields'=>array('type'=>'array','items'=>array('type'=>'string')),'id'=>$id),array('code','message'),false);
  $itemResult=mcpObjectSchema(array(
    'index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','rolled_back','error')),
    'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'relatedIds'=>array('type'=>'array','maxItems'=>400,'items'=>$id),
    'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>$saved,'error'=>$error,'concurrencyUnchecked'=>$boolean
  ),array('index','status','objectClass','id','relatedIds','requestedFields','appliedFields','recalculatedFields','ignoredFields','rejectedFields','concurrencyUnchecked'),false);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>'string'),'id'=>$id),array('action','objectClass','id'),false);
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$itemResult),'effects'=>array('type'=>'array','maxItems'=>400,'items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
  $common=array('id'=>$id,'operation'=>$operation,'expectedVersion'=>$version,'idle'=>$boolean);
  $batch=function(string $name,array $item)use($transaction):array{return mcpObjectSchema(array($name=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$item),'transactionMode'=>$transaction),array($name),false);};
  $options=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpFinancialActionAvailable','permissionClasses'=>$classes,'batchLimit'=>200,'sideEffectClassification'=>'write'),$extra);};
  $guarded=function(array $classes,array $extra=array())use($options):array{return $options($classes,array_merge(array('preview'=>'mcpFinancialPreview','sideEffectClassification'=>'destructive'),$extra));};

  $expense=mcpObjectSchema($common+array('objectClass'=>array('type'=>'string','enum'=>array('IndividualExpense','ProjectExpense','ActivityExpense')),'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'idProject'=>$nullableId,'idResource'=>$nullableId,'idActivity'=>$nullableId,'idStatus'=>$nullableId,'plannedAmount'=>$money,'realAmount'=>$money,'expensePlannedDate'=>$date,'expenseRealDate'=>$date,'description'=>$text,'externalReference'=>$short),array('objectClass'),false);
  $expenseDetail=mcpObjectSchema($common+array('expenseClass'=>array('type'=>'string','enum'=>array('IndividualExpense','ProjectExpense','ActivityExpense')),'idExpense'=>$id,'idExpenseDetailType'=>$nullableId,'name'=>$short,'externalReference'=>$short,'expenseDate'=>$date,'amount'=>$money,'amountLocal'=>$money,'value01'=>$money,'value02'=>$money,'value03'=>$money,'unit01'=>$short,'unit02'=>$short,'unit03'=>$short),array('expenseClass','idExpense'),false);
  $document=mcpObjectSchema($common+array('objectClass'=>array('type'=>'string','enum'=>array('Bill','ProviderBill','ProviderOrder','ProviderPayment','Payment','Quotation','ClientContract','SupplierContract')),'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'idProject'=>$nullableId,'idClient'=>$nullableId,'idProvider'=>$nullableId,'idContact'=>$nullableId,'idResource'=>$nullableId,'idStatus'=>$nullableId,'idType'=>$nullableId,'date'=>$date,'paymentDueDate'=>$date,'untaxedAmount'=>$money,'taxPct'=>$money,'taxAmount'=>$money,'fullAmount'=>$money,'description'=>$text,'externalReference'=>$short),array('objectClass'),false);
  $billLine=mcpObjectSchema($common+array('refType'=>array('type'=>'string','enum'=>array('Bill','ProviderBill','ProviderOrder','Quotation')),'refId'=>$id,'line'=>array('type'=>'integer','minimum'=>0),'quantity'=>$quantity,'numberDays'=>$quantity,'idTerm'=>$nullableId,'idResource'=>$nullableId,'idActivityPrice'=>$nullableId,'idCatalog'=>$nullableId,'idMeasureUnit'=>$nullableId,'startDate'=>$date,'endDate'=>$date,'description'=>$short,'detail'=>$text,'price'=>$money,'priceLocal'=>$money,'extra'=>$boolean,'billingType'=>array('type'=>'string','enum'=>array('M','E'))),array('refType','refId'),false);
  $providerTerm=mcpObjectSchema($common+array('parentType'=>array('type'=>'string','enum'=>array('ProviderOrder','ProviderBill')),'parentId'=>$id,'idProject'=>$nullableId,'date'=>$date,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'taxPct'=>$money,'untaxedAmount'=>$money,'taxAmount'=>$money,'fullAmount'=>$money,'untaxedAmountLocal'=>$money,'taxAmountLocal'=>$money,'fullAmountLocal'=>$money,'idResource'=>$nullableId,'detachFromBill'=>$boolean),array('parentType','parentId'),false);
  $tender=mcpObjectSchema($common+array('objectClass'=>array('type'=>'string','enum'=>array('CallForTender','Tender')),'name'=>$short,'idProject'=>$nullableId,'idCallForTender'=>$nullableId,'idProvider'=>$nullableId,'idContact'=>$nullableId,'idTenderStatus'=>$nullableId,'idStatus'=>$nullableId,'requestDateTime'=>$datetime,'expectedTenderDateTime'=>$datetime,'description'=>$text),array('objectClass'),false);
  $criterion=mcpObjectSchema($common+array('idCallForTender'=>$id,'criteriaName'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'criteriaMaxValue'=>$money,'criteriaCoef'=>$money),array('idCallForTender'),false);
  $budget=mcpObjectSchema($common+array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'idBudget'=>$nullableId,'idBudgetType'=>$nullableId,'idBudgetOrientation'=>$nullableId,'idOrganization'=>$nullableId,'idProject'=>$nullableId,'budgetStartDate'=>$date,'budgetEndDate'=>$date,'amount'=>$money,'description'=>$text),array(),false);
  $organizationBudget=mcpObjectSchema($common+array('idOrganization'=>$id,'year'=>array('type'=>'integer','minimum'=>1900),'budgetWork'=>$money,'budgetCost'=>$money,'expenseBudgetAmount'=>$money,'closed'=>$boolean),array('idOrganization','year'),false);
  $budgetMove=mcpObjectSchema(array('id'=>$id,'targetId'=>$id,'position'=>array('type'=>'string','enum'=>array('before','after')),'expectedVersion'=>$version,'expectedTargetVersion'=>$version),array('id','targetId','position','expectedVersion','expectedTargetVersion'),false);
  $workCommand=mcpObjectSchema($common+array('idCommand'=>$id,'idWorkUnit'=>$nullableId,'idComplexity'=>$nullableId,'idWorkCommand'=>$nullableId,'name'=>$short,'unitAmount'=>$money,'commandQuantity'=>$quantity,'commandAmount'=>$money),array('idCommand'),false);
  $workAccepted=mcpObjectSchema($common+array('idWorkCommand'=>$id,'idAcceptance'=>$id,'acceptedQuantity'=>$quantity),array('idWorkCommand','idAcceptance'),false);
  $workBilled=mcpObjectSchema($common+array('idWorkCommand'=>$id,'idBill'=>$id,'billedQuantity'=>$quantity),array('idWorkCommand','idBill'),false);
  $complexity=mcpObjectSchema(array('idComplexity'=>$id,'charge'=>$money,'price'=>$money,'priceLocal'=>$money,'duration'=>$money),array('idComplexity'),false);
  $workUnit=mcpObjectSchema($common+array('idCatalogUO'=>$id,'reference'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'description'=>$text,'incoming'=>$text,'livrable'=>$text,'validityDate'=>$date,'complexities'=>array('type'=>'array','maxItems'=>50,'items'=>$complexity)),array('idCatalogUO','reference'),false);
  $catalogPhase=mcpObjectSchema($common+array('idCatalogUO'=>$id,'reference'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'ratioPct'=>array('type'=>'number','minimum'=>0)),array('idCatalogUO','reference'),false);
  $workTokenContract=mcpObjectSchema($common+array('idClientContract'=>$id,'idWorkToken'=>$id,'description'=>$short,'quantity'=>$quantity,'newQuantity'=>$quantity,'reportQuantity'=>$quantity,'allowOverUse'=>$boolean,'allowIdleUse'=>$boolean),array('idClientContract','idWorkToken'),false);
  $workTokenMarkup=mcpObjectSchema($common+array('idWorkToken'=>$id,'name'=>$short,'coefficient'=>array('type'=>array('number','null'),'minimum'=>0)),array('idWorkToken'),false);
  $abacus=mcpObjectSchema($common+array('objectClass'=>array('type'=>'string','enum'=>array('AbacusDefinition','Phase','AbacusLine','AbacusProject','Abacusable')),'name'=>$short,'idAbacusDefinition'=>$nullableId,'idProject'=>$nullableId,'idPhasing'=>$nullableId,'className'=>$short,'idClassName1'=>$nullableId,'idClassName2'=>$nullableId,'idClassName3'=>$nullableId,'idClassName4'=>$nullableId,'idClassName5'=>$nullableId,'quantity'=>$quantity,'capacity'=>$money,'assumption'=>$text,'example'=>$text,'valueField'=>$boolean,'inputField'=>$boolean,'sortOrder'=>array('type'=>array('integer','null'),'minimum'=>0),'comment'=>$text),array('objectClass'),false);
  $abacusApply=mcpObjectSchema(array('idProject'=>$id,'expectedVersion'=>$version,'mode'=>array('type'=>'string','enum'=>array('affectations','assignments','both'))),array('idProject','expectedVersion','mode'),false);
  $facturx=mcpObjectSchema(array('uploadId'=>array('type'=>'string','pattern'=>'^[a-f0-9]{48}$'),'idProject'=>$id,'createProvider'=>array('type'=>'boolean')),array('uploadId','idProject'),false);
  $facturxResult=mcpObjectSchema(array('ok'=>$boolean,'providerId'=>$id,'providerBillId'=>$id,'lineIds'=>array('type'=>'array','maxItems'=>200,'items'=>$id),'effects'=>array('type'=>'array','maxItems'=>202,'items'=>$effect)),array('ok','providerId','providerBillId','lineIds','effects'),false);

  return array('id'=>'financial','version'=>'4.0.0','dependencies'=>array('core','configuration','environment','products','follow_up','tools'),'actions'=>array(
    'financial.expense.submit'=>mcpActionSpec($batch('expenses',$expense),$batchResult,'destructive',false,'mcpFinancialExpenseAction',array(),'financial.expense.submit',$guarded(array('IndividualExpense','ProjectExpense','ActivityExpense'))),
    'financial.expense_detail.manage'=>mcpActionSpec($batch('details',$expenseDetail),$batchResult,'destructive',false,'mcpFinancialExpenseDetailAction',array('tool:saveExpenseDetail','tool:removeExpenseDetail'),'financial.expense-detail.manage',$guarded(array('IndividualExpense','ProjectExpense','ActivityExpense','ExpenseDetail'))),
    'financial.billing.generate'=>mcpActionSpec($batch('documents',$document),$batchResult,'destructive',false,'mcpFinancialDocumentAction',array(),'financial.billing.generate',$guarded(array('Bill','ProviderBill','ProviderOrder','ProviderPayment','Payment','Quotation','ClientContract','SupplierContract'))),
    'financial.bill_line.manage'=>mcpActionSpec($batch('lines',$billLine),$batchResult,'destructive',false,'mcpFinancialBillLineAction',array('tool:saveBillLine','tool:removeBillLine'),'financial.bill-line.manage',$guarded(array('Bill','ProviderBill','ProviderOrder','Quotation'))),
    'financial.provider_term.manage'=>mcpActionSpec($batch('terms',$providerTerm),$batchResult,'destructive',false,'mcpFinancialProviderTermAction',array('tool:saveProviderTerm','tool:saveProviderTermFromProviderBill','tool:removeProviderTerm'),'financial.provider-term.manage',$guarded(array('ProviderTerm','ProviderOrder','ProviderBill'))),
    'financial.tender.manage'=>mcpActionSpec($batch('tenders',$tender),$batchResult,'destructive',false,'mcpFinancialTenderAction',array('tool:saveTenderSubmission','tool:removeTenderSubmission'),'financial.tender.manage',$guarded(array('CallForTender','Tender'))),
    'financial.tender_criteria.manage'=>mcpActionSpec($batch('criteria',$criterion),$batchResult,'destructive',false,'mcpFinancialTenderCriteriaAction',array('tool:saveTenderEvaluationCriteria','tool:removeTenderEvaluationCriteria'),'financial.tender-criteria.manage',$guarded(array('CallForTender','TenderEvaluationCriteria'))),
    'financial.budget.update'=>mcpActionSpec($batch('budgets',$budget),$batchResult,'destructive',false,'mcpFinancialBudgetAction',array(),'financial.budget.update',$guarded(array('Budget'))),
    'financial.organization_budget.manage'=>mcpActionSpec($batch('periods',$organizationBudget),$batchResult,'destructive',false,'mcpFinancialOrganizationBudgetAction',array('tool:saveOrganizationBudgetElement','tool:closeUncloseOrganizationBudgetElement','tool:removeOrganizationBudgetElement'),'financial.organization-budget.manage',$guarded(array('Organization'))),
    'financial.budget.move'=>mcpActionSpec($batch('moves',$budgetMove),$batchResult,'destructive',false,'mcpFinancialBudgetMoveAction',array('tool:moveBudgetFromHierarchicalView'),'financial.budget.move',$guarded(array('Budget'))),
    'financial.work_command.manage'=>mcpActionSpec($batch('commands',$workCommand),$batchResult,'destructive',false,'mcpFinancialWorkCommandAction',array('tool:saveWorkCommand','tool:saveParentWorkCommand','tool:removeWorkCommand'),'financial.work-command.manage',$guarded(array('WorkCommand','Command'))),
    'financial.work_command.accept'=>mcpActionSpec($batch('acceptances',$workAccepted),$batchResult,'destructive',false,'mcpFinancialWorkAcceptedAction',array('tool:saveAcceptedWorkCommand','tool:removeAcceptedWorkCommand'),'financial.work-command.accept',$guarded(array('WorkCommand','Acceptance'))),
    'financial.work_command.bill'=>mcpActionSpec($batch('billings',$workBilled),$batchResult,'destructive',false,'mcpFinancialWorkBilledAction',array('tool:saveBilledWorkCommand','tool:removeBilledWorkCommand'),'financial.work-command.bill',$guarded(array('WorkCommand','Bill'))),
    'financial.work_unit.manage'=>mcpActionSpec($batch('units',$workUnit),$batchResult,'destructive',false,'mcpFinancialWorkUnitAction',array('tool:saveWorkUnit','tool:removeWorkUnit'),'financial.work-unit.manage',$guarded(array('CatalogUO'))),
    'financial.work_unit_phase.manage'=>mcpActionSpec($batch('phases',$catalogPhase),$batchResult,'destructive',false,'mcpFinancialWorkUnitPhaseAction',array('tool:saveWorkUnitCatalogPhase','tool:removeWorkUnitCatalogPhase'),'financial.work-unit-phase.manage',$guarded(array('CatalogUO'))),
    'financial.work_token_contract.manage'=>mcpActionSpec($batch('tokens',$workTokenContract),$batchResult,'destructive',false,'mcpFinancialWorkTokenContractAction',array('tool:saveWorkTokenClientContract'),'financial.work-token-contract.manage',$guarded(array('ClientContract','TokenDefinition'))),
    'financial.work_token_markup.manage'=>mcpActionSpec($batch('markups',$workTokenMarkup),$batchResult,'destructive',false,'mcpFinancialWorkTokenMarkupAction',array('tool:saveWorkTokenMarkup'),'financial.work-token-markup.manage',$guarded(array('TokenDefinition'))),
    'financial.abacus.manage'=>mcpActionSpec($batch('items',$abacus),$batchResult,'destructive',false,'mcpFinancialAbacusAction',array('tool:saveAbacusDefinition','tool:saveAbacusLine','tool:saveAbacusPhase','tool:saveAbacusProjectLine','tool:saveAbacusable'),'financial.abacus.manage',$guarded(array('Project'))),
    'financial.abacus.apply_to_project'=>mcpActionSpec($abacusApply,$batchResult,'destructive',true,'mcpFinancialAbacusApplyWorker',array('tool:saveAbacusAffectations','tool:saveAbacusAssignments'),'financial.abacus.apply',$guarded(array('Project'),array('transaction'=>'worker','retryPolicy'=>'recovery_required'))),
    'financial.facturx.import'=>mcpActionSpec($facturx,$facturxResult,'external',true,'mcpFinancialFacturXWorker',array('tool:importFacturX'),'financial.factur-x.import',$options(array('Provider','ProviderBill','Project'),array('preview'=>'mcpFinancialFacturXPreview','transaction'=>'worker','retryPolicy'=>'recovery_required','sideEffectClassification'=>'external')))
  ));
}
