LogFormat "%h %l %u %t \"%m %U %H\" %>s %b \"%{User-Agent}i\"" projeqtor_safe

<Directory "/var/www/html/api">
    AllowOverride AuthConfig FileInfo
</Directory>

<Directory "/var/www/html/mcp-api">
    AllowOverride FileInfo
    Require ip 172.30.18.13
</Directory>
