<?php
declare(strict_types=1);
$id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);
$short=array('type'=>array('string','null'),'maxLength'=>400);$text=array('type'=>array('string','null'),'maxLength'=>4000);$bool=array('type'=>'boolean');
$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));$operation=array('type'=>'string','enum'=>array('create','update','delete'));
$savedBase=mcpObjectSchema(array('id'=>$id,'_version'=>$version),array('id','_version'),false);
$saved=array('type'=>array('object','null'),'properties'=>array('id'=>$id,'_version'=>$version,'target'=>$savedBase),'required'=>array('id','_version'),'additionalProperties'=>false);
$error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>$id,'expectedVersion'=>$version,'actualVersion'=>$version,'actualVoteSetVersion'=>$version,'missingFields'=>array('type'=>'array','items'=>array('type'=>'string')),'invalidFields'=>array('type'=>'array','items'=>array('type'=>'string'))),array('code','message'),false);
$effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>'string'),'id'=>$id),array('action','objectClass','id'),false);
$itemResult=mcpObjectSchema(array(
  'index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','invalid','rolled_back','error')),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),
  'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
  'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>$saved,'error'=>$error,'concurrencyUnchecked'=>$bool
),array('status','objectClass'),false);
$batchResult=mcpObjectSchema(array('ok'=>$bool,'rolledBack'=>$bool,'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$itemResult),'effects'=>array('type'=>'array','maxItems'=>400,'items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
$options=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpScrumActionAvailable','permissionClasses'=>$classes,'transaction'=>'atomic','batchLimit'=>200,'sideEffectClassification'=>'write'),$extra);};
$guarded=function(array $classes,string $preview,array $extra=array())use($options):array{return $options($classes,array_merge(array('preview'=>$preview,'sideEffectClassification'=>'destructive'),$extra));};
$batch=function(string $key,array $item):array{return mcpObjectSchema(array($key=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$item),'transactionMode'=>array('type'=>'string','enum'=>array('atomic','best_effort'))),array($key),false);};

$story=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'idProject'=>$id,'idUserStoryType'=>$id,'idStatus'=>$id,'idResource'=>$nullableId,'idEpic'=>$nullableId,'idSprint'=>$nullableId,'idScrumPriority'=>$nullableId,'storyPoints'=>array('type'=>array('number','null'),'minimum'=>0),'businessValue'=>array('type'=>array('number','null'),'minimum'=>0),'featureAction'=>$short,'featureGoal'=>$short,'featureOpposite'=>$short,'acceptationCriteria'=>$text,'description'=>$text,'result'=>$text,'idle'=>$bool),array('operation'),false);
$priority=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version,'idScrumPriority'=>$id,'idSprint'=>$nullableId),array('id','expectedVersion','idScrumPriority'),false);
$sprint=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version,'state'=>array('type'=>'string','enum'=>array('start','pause','resume','close','reopen')),'idStatus'=>$nullableId,'result'=>$text),array('id','expectedVersion','state'),false);
$column=mcpObjectSchema(array('from'=>array('type'=>array('integer','string')),'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'cantDelete'=>$bool),array('from','name'),false);
$board=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','copy','share','delete')),'id'=>$id,'expectedVersion'=>$version,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'columnType'=>array('type'=>'string','enum'=>array('Status','Sprint','TargetProductVersion','TargetComponentVersion')),'cardType'=>array('type'=>'string','enum'=>array('Ticket','Activity','Action','Requirement','UserStory','Epic','Risk','Issue','Question','Decision')),'isShared'=>$bool,'columns'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$column)),array('operation'),false);
$columnSet=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version,'columns'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$column)),array('id','expectedVersion','columns'),false);
$card=mcpObjectSchema(array('objectClass'=>array('type'=>'string','enum'=>array('Ticket','Activity','Action','Requirement','UserStory','Epic','Risk','Issue','Question','Decision')),'id'=>$id,'expectedVersion'=>$version,'columnType'=>array('type'=>'string','enum'=>array('Status','Sprint')),'columnId'=>$nullableId,'idResource'=>$nullableId,'idResolution'=>$nullableId,'description'=>$text,'result'=>$text),array('objectClass','id','expectedVersion','columnType','columnId'),false);
$preference=mcpObjectSchema(array('idKanban'=>$nullableId,'showIdle'=>$bool,'showWork'=>$bool,'hideBacklog'=>$bool,'fullWidth'=>$bool,'orderBy'=>array('type'=>'string','enum'=>array('id asc','id desc','name asc','storyPoints desc','statusName asc'))),array(),false);
$session=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version,'state'=>array('type'=>'string','enum'=>array('start','pause','resume','finish','reopen'))),array('id','expectedVersion','state'),false);
$pokerItem=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'sessionExpectedVersion'=>$version,'idPokerSession'=>$id,'refType'=>array('type'=>'string','enum'=>array('Ticket','Activity','Requirement','UserStory')),'refId'=>$id,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'comment'=>$text),array('operation','idPokerSession'),false);
$pokerState=mcpObjectSchema(array('idPokerSession'=>$id,'idPokerItem'=>$id,'sessionExpectedVersion'=>$version,'itemExpectedVersion'=>$version,'mode'=>array('type'=>'string','enum'=>array('open','pause','finalize')),'idPokerComplexity'=>$id,'targetExpectedVersion'=>$version),array('idPokerSession','idPokerItem','sessionExpectedVersion','itemExpectedVersion','mode'),false);
$vote=mcpObjectSchema(array('idPokerSession'=>$id,'idPokerItem'=>$id,'sessionExpectedVersion'=>$version,'itemExpectedVersion'=>$version,'value'=>array('type'=>array('number','string','null')),'expectedVoteVersion'=>$version),array('idPokerSession','idPokerItem','sessionExpectedVersion','itemExpectedVersion','value'),false);
$visibility=mcpObjectSchema(array('idPokerSession'=>$id,'idPokerItem'=>$id,'sessionExpectedVersion'=>$version,'itemExpectedVersion'=>$version,'mode'=>array('type'=>'string','enum'=>array('reveal','reset')),'expectedVoteSetVersion'=>$version),array('idPokerSession','idPokerItem','sessionExpectedVersion','itemExpectedVersion','mode','expectedVoteSetVersion'),false);
$manageOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('rank_backlog','start_sprint','pause_sprint','resume_sprint','close_sprint','reopen_sprint','move_kanban_card')),'sprintId'=>$id,'itemId'=>$id,'objectClass'=>array('type'=>'string','enum'=>array('Ticket','Activity','Action','Requirement','UserStory','Epic','Risk','Issue','Question','Decision')),'boardId'=>$id,'columnType'=>array('type'=>'string','enum'=>array('Status','Sprint')),'columnId'=>$nullableId,'priorityId'=>$id,'beforeItemId'=>$id,'afterItemId'=>$id,'expectedVersion'=>$version),array('operation','expectedVersion'),false);
$boardRead=mcpObjectSchema(array('id'=>$id,'name'=>array('type'=>'string'),'columnType'=>array('type'=>'string'),'cardType'=>array('type'=>'string'),'isShared'=>$bool,'columns'=>array('type'=>'array','maxItems'=>200,'items'=>$column),'_version'=>$version),array('id','name','columnType','cardType','isShared','columns','_version'),false);
$boardReadResult=mcpObjectSchema(array('ok'=>$bool,'board'=>$boardRead,'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','board','effects'),false);
$pokerReadItem=mcpObjectSchema(array('id'=>$id,'name'=>array('type'=>'string'),'refType'=>array('type'=>'string'),'refId'=>$id,'isOpen'=>$bool,'flipped'=>$bool,'value'=>array('type'=>array('number','string','null')),'voteCount'=>array('type'=>'integer','minimum'=>0),'voteSetVersion'=>$version,'ownVote'=>mcpObjectSchema(array('id'=>$id,'value'=>array('type'=>array('number','string','null')),'_version'=>$version),array('id','value','_version'),false),'revealedVotes'=>array('type'=>'array','maxItems'=>200,'items'=>mcpObjectSchema(array('idResource'=>$id,'value'=>array('type'=>array('number','string','null'))),array('idResource','value'),false)),'_version'=>$version),array('id','name','refType','refId','isOpen','flipped','value','voteCount','voteSetVersion','_version'),false);
$pokerReadResult=mcpObjectSchema(array('ok'=>$bool,'session'=>mcpObjectSchema(array('id'=>$id,'handled'=>$bool,'done'=>$bool,'_version'=>$version),array('id','handled','done','_version'),false),'items'=>array('type'=>'array','maxItems'=>200,'items'=>$pokerReadItem),'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','session','items','effects'),false);
$preferenceResult=mcpObjectSchema(array('ok'=>$bool,'preferences'=>$preference,'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','preferences','effects'),false);

return array('id'=>'scrum','version'=>'4.0.0','dependencies'=>array('core','configuration','environment','ticketing','products'),'actions'=>array(
  'scrum.sprint.manage'=>mcpActionSpec($batch('operations',$manageOperation),$batchResult,'write',false,'mcpScrumSprintManage',array(),'scrum.sprint.manage',$options(array('Sprint','UserStory','Ticket'))),
  'scrum.story.manage'=>mcpActionSpec($batch('stories',$story),$batchResult,'destructive',false,'mcpScrumStoryManage',array('tool:saveUserStory'),'scrum.story.manage',$guarded(array('UserStory'),'mcpScrumStoryPreview')),
  'scrum.backlog.prioritize'=>mcpActionSpec($batch('items',$priority),$batchResult,'write',false,'mcpScrumBacklogPrioritize',array(),'scrum.backlog.prioritize',$options(array('UserStory'))),
  'scrum.sprint.lifecycle'=>mcpActionSpec($batch('sprints',$sprint),$batchResult,'write',false,'mcpScrumSprintLifecycle',array(),'scrum.sprint.lifecycle',$options(array('Sprint'))),
  'scrum.kanban.board.get'=>mcpActionSpec(mcpObjectSchema(array('id'=>$id),array('id')),$boardReadResult,'read',false,'mcpScrumKanbanGet',array(),'scrum.kanban.board.get',$options(array('UserStory'),array('transaction'=>'none','sideEffectClassification'=>'read'))),
  'scrum.kanban.board.manage'=>mcpActionSpec($batch('boards',$board),$batchResult,'destructive',false,'mcpScrumKanbanBoardManage',array('tool:kanbanAdd','tool:kanbanCopy','tool:kanbanDel','tool:kanbanEditName','tool:kanbanFunction','tool:kanbanShare'),'scrum.kanban.board.manage',$guarded(array('UserStory'),'mcpScrumBoardPreview')),
  'scrum.kanban.columns.replace'=>mcpActionSpec($batch('boards',$columnSet),$batchResult,'destructive',false,'mcpScrumKanbanColumnsReplace',array('tool:kanbanColumnAdd','tool:kanbanColumnEdit','tool:saveKanbanColumnManagment'),'scrum.kanban.columns.replace',$guarded(array('UserStory'),'mcpScrumColumnsPreview')),
  'scrum.kanban.card.move'=>mcpActionSpec($batch('cards',$card),$batchResult,'write',false,'mcpScrumKanbanCardMove',array('tool:backlogCheckRequiredField','tool:dynamicDialogKanbanUpdate','tool:kanbanScrumSimplifiedService','tool:kanbanUpdate'),'scrum.kanban.card.move',$options(array('UserStory','Ticket'))),
  'scrum.kanban.preferences'=>mcpActionSpec($preference,$preferenceResult,'write',false,'mcpScrumKanbanPreferences',array('view:kanbanView','view:kanbanViewMain'),'scrum.kanban.preferences',$options(array('UserStory'),array('transaction'=>'none'))),
  'scrum.poker.state.get'=>mcpActionSpec(mcpObjectSchema(array('idPokerSession'=>$id,'idPokerItem'=>$nullableId),array('idPokerSession')),$pokerReadResult,'read',false,'mcpScrumPokerStateGet',array(),'scrum.poker.state.get',$options(array('PokerSession'),array('transaction'=>'none','sideEffectClassification'=>'read'))),
  'scrum.poker.session.lifecycle'=>mcpActionSpec($batch('sessions',$session),$batchResult,'write',false,'mcpScrumPokerSessionLifecycle',array('tool:startPausePokerSession','tool:startPokerSession'),'scrum.poker.session.lifecycle',$options(array('PokerSession'))),
  'scrum.poker.item.manage'=>mcpActionSpec($batch('items',$pokerItem),$batchResult,'destructive',false,'mcpScrumPokerItemManage',array('tool:removePokerItem','tool:savePokerItem'),'scrum.poker.item.manage',$guarded(array('PokerSession'),'mcpScrumPokerItemPreview')),
  'scrum.poker.item.state'=>mcpActionSpec($batch('items',$pokerState),$batchResult,'write',false,'mcpScrumPokerItemState',array('tool:openPokerItemVote'),'scrum.poker.item.state',$options(array('PokerSession'))),
  'scrum.poker.vote.cast'=>mcpActionSpec($batch('votes',$vote),$batchResult,'write',false,'mcpScrumPokerVoteCast',array('tool:voteToPokerItem'),'scrum.poker.vote.cast',$options(array('PokerSession'))),
  'scrum.poker.vote.visibility'=>mcpActionSpec($batch('items',$visibility),$batchResult,'destructive',false,'mcpScrumPokerVoteVisibility',array('tool:flipPokerVote'),'scrum.poker.vote.visibility',$guarded(array('PokerSession'),'mcpScrumPokerVisibilityPreview'))
));
