<?php
declare(strict_types=1);

function mcpCoreModuleDescriptor(): array {
  $boolean=array('type'=>'boolean');$id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);
  $version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$class=array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$');
  $date=array('type'=>array('string','null'),'pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');$dateTime=array('type'=>array('string','null'),'maxLength'=>40);$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
  $actor=mcpObjectSchema(array('id'=>$id,'username'=>array('type'=>'string','minLength'=>1,'maxLength'=>100)),array('id','username'),false);
  $saved=mcpObjectSchema(array('id'=>$id,'_version'=>$version),array('id','_version'),false);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>'string'),'id'=>$id),array('action','objectClass','id'),false);
  $error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string'),'expectedVersion'=>$version,'actualVersion'=>$version,'field'=>array('type'=>'string')),array('code','message'),false);
  $item=mcpObjectSchema(array(
    'index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','unchanged','rolled_back','error')),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),
    'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'saved'=>array('type'=>array('object','null'),'properties'=>$saved['properties'],'required'=>$saved['required'],'additionalProperties'=>false),
    'error'=>array('type'=>array('object','null'),'properties'=>$error['properties'],'required'=>$error['required'],'additionalProperties'=>false),'concurrencyUnchecked'=>$boolean
  ),array('index','status','objectClass','id','requestedFields','appliedFields','recalculatedFields','ignoredFields','rejectedFields','saved','error','concurrencyUnchecked'),false);
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'actor'=>$actor,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$item),'effects'=>array('type'=>'array','maxItems'=>400,'items'=>$effect)),array('ok','rolledBack','transactionMode','actor','items','effects'),false);
  $options=function(array $classes=array(),array $extra=array()):array{return array_merge(array('availability'=>'mcpCoreActionAvailable','permissionClasses'=>$classes,'confirmationRequired'=>false,'transaction'=>'atomic','batchLimit'=>200,'sideEffectClassification'=>'write'),$extra);};
  $guarded=function(array $classes,string $preview,array $extra=array())use($options):array{return $options($classes,array_merge(array('confirmationRequired'=>true,'preview'=>$preview,'sideEffectClassification'=>'destructive'),$extra));};

  $objectRef=array('objectClass'=>$class,'id'=>$id,'expectedVersion'=>$version);$objectIdentity=mcpObjectSchema(array('objectClass'=>$class,'id'=>$id,'version'=>$version),array('objectClass','id','version'),false);
  $copyResult=mcpObjectSchema(array('ok'=>$boolean,'actor'=>$actor,'source'=>$objectIdentity,'copy'=>$objectIdentity,'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$effect)),array('ok','actor','source','copy','effects'),false);
  $transitionResult=mcpObjectSchema(array('ok'=>$boolean,'actor'=>$actor,'object'=>$objectIdentity,'idStatus'=>$id,'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$effect)),array('ok','actor','object','idStatus','effects'),false);
  $sessionResult=mcpObjectSchema(array('ok'=>$boolean,'status'=>array('type'=>'string','enum'=>array('active','termination_requested')),'actor'=>$actor,'auditId'=>$id,'targetUserId'=>$id,'version'=>$version,'effects'=>array('type'=>'array','maxItems'=>2,'items'=>$effect)),array('ok','status','actor','auditId','targetUserId','version','effects'),false);
  $jobResult=mcpObjectSchema(array('ok'=>$boolean,'queued'=>$boolean,'job'=>mcpObjectSchema(array('id'=>$id,'type'=>array('type'=>'string'),'status'=>array('type'=>'string'),'progress'=>array('type'=>'integer','minimum'=>0),'resultResource'=>array('type'=>'string')),array('id','type','status','progress','resultResource'),false)),array('ok','queued','job'),false);

  $job=mcpObjectSchema(array('jobDefinitionId'=>$id,'checked'=>$boolean,'expectedVersion'=>$version,'idUser'=>$nullableId,'creationDate'=>$date,'comment'=>array('type'=>array('string','null'),'maxLength'=>4000)),array('jobDefinitionId','checked'),false);
  $joblistSchema=mcpObjectSchema(array('objectClass'=>$class,'objectId'=>$id,'expectedVersion'=>$version,'joblistDefinitionId'=>$id,'jobs'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$job)),array('objectClass','objectId','expectedVersion','joblistDefinitionId','jobs'),false);
  $legalAcceptSchema=mcpObjectSchema(array('followupId'=>$id,'expectedVersion'=>$version,'newGuiEnabled'=>$boolean),array('followupId','expectedVersion'),false);
  $legalResult=mcpObjectSchema(array('ok'=>$boolean,'status'=>array('type'=>'string','enum'=>array('accepted','viewed')),'actor'=>$actor,'followupId'=>$id,'messageLegalId'=>$id,'acceptedAt'=>$dateTime,'firstViewedAt'=>$dateTime,'lastViewedAt'=>$dateTime,'preferencesUpdated'=>$boolean,'version'=>$version,'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$effect)),array('ok','status','actor','followupId','messageLegalId','acceptedAt','firstViewedAt','lastViewedAt','preferencesUpdated','version','effects'),false);
  $legalView=mcpObjectSchema(array('followupId'=>$id,'expectedVersion'=>$version),array('followupId','expectedVersion'),false);$legalViewSchema=mcpObjectSchema(array('followups'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$legalView)),array('followups'),false);
  $legalViewResult=mcpObjectSchema(array('ok'=>$boolean,'actor'=>$actor,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$legalResult),'effects'=>array('type'=>'array','maxItems'=>200,'items'=>$effect)),array('ok','actor','items','effects'),false);
  $bulkTarget=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id','expectedVersion'),false);$bulkSchema=mcpObjectSchema(array('objectClass'=>$class,'field'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'value'=>array(),'targets'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$bulkTarget),'transactionMode'=>$transaction),array('objectClass','field','value','targets'),false);
  $subTaskData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>4000),'priorityId'=>$nullableId,'resourceId'=>$nullableId,'dueDate'=>$date,'sortOrder'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('pending','paused','handled','done','idle'))),array(),false);
  $subTaskOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','delete')),'id'=>$id,'expectedVersion'=>$version,'data'=>$subTaskData),array('operation'),false);
  $subTaskOrder=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version,'sortOrder'=>array('type'=>'integer','minimum'=>0)),array('id','expectedVersion','sortOrder'),false);
  $subTaskSchema=mcpObjectSchema(array('parentClass'=>$class,'parentId'=>$id,'expectedParentVersion'=>$version,'operations'=>array('type'=>'array','maxItems'=>200,'items'=>$subTaskOperation),'order'=>array('type'=>'array','maxItems'=>200,'items'=>$subTaskOrder)),array('parentClass','parentId','expectedParentVersion'),false);

  return array('id'=>'core','version'=>'4.0.0','dependencies'=>array(),'actions'=>array(
    'object.copy'=>mcpActionSpec(mcpObjectSchema($objectRef,array('objectClass','id','expectedVersion'),false),$copyResult,'write',false,'mcpCoreCopy',array('tool:copyObject','tool:copyObjectTo','tool:copyProjectTo'),'core.object.copy',$options()),
    'workflow.transition'=>mcpActionSpec(mcpObjectSchema($objectRef+array('idStatus'=>$id),array('objectClass','id','expectedVersion','idStatus'),false),$transitionResult,'write',false,'mcpCoreTransition',array('tool:changeObjectStatus'),'core.workflow.transition',$options()),
    'core.reference.rebuild'=>mcpActionSpec(mcpObjectSchema(array('objectClass'=>$class),array(),false),$jobResult,'administrative',true,'mcpCoreReferenceRebuildWorker',array(),'core.reference.rebuild',array('availability'=>'mcpCoreActionAvailable','confirmationRequired'=>true,'preview'=>'mcpCoreReferenceRebuildPreview','transaction'=>'worker','retryPolicy'=>'recovery_required','sideEffectClassification'=>'administrative')),
    'user.session.terminate'=>mcpActionSpec(mcpObjectSchema(array('auditId'=>$id,'expectedVersion'=>$version),array('auditId','expectedVersion'),false),$sessionResult,'destructive',false,'mcpCoreSessionTerminate',array('tool:disconnectSession','tool:hackMessage'),'core.user.session.terminate',$guarded(array('Audit','User'),'mcpCoreSessionTerminatePreview')),
    'user.session.login'=>mcpActionSpec(mcpObjectSchema(array(),array(),false),$sessionResult,'write',false,'mcpCoreSessionLogin',array('tool:loginCheck'),'core.user.session.login',$options(array('Audit','User','MessageLegalFollowup'))),
    'core.joblist.update'=>mcpActionSpec($joblistSchema,$batchResult,'write',false,'mcpCoreJoblistUpdate',array('tool:saveJoblist'),'core.joblist.update',$options(array('JoblistDefinition','Job'))),
    'user.legal_notice.accept'=>mcpActionSpec($legalAcceptSchema,$legalResult,'external',false,'mcpCoreLegalNoticeAccept',array('tool:saveMessageLegalFollowup'),'core.user.legal-notice.accept',$guarded(array('MessageLegal','MessageLegalFollowup'),'mcpCoreLegalNoticeAcceptPreview',array('sideEffectClassification'=>'external'))),
    'core.object.bulk_update'=>mcpActionSpec($bulkSchema,$batchResult,'destructive',false,'mcpCoreObjectBulkUpdate',array('tool:saveObjectMultiple'),'core.object.bulk-update',$guarded(array(),'mcpCoreObjectBulkUpdatePreview')),
    'core.subtask.manage'=>mcpActionSpec($subTaskSchema,$batchResult,'destructive',false,'mcpCoreSubTaskManage',array('tool:saveSubTask','tool:saveSubTaskOrder'),'core.subtask.manage',$guarded(array('SubTask'),'mcpCoreSubTaskPreview')),
    'user.legal_notice.view'=>mcpActionSpec($legalViewSchema,$legalViewResult,'write',false,'mcpCoreLegalNoticeView',array('view:main'),'core.user.legal-notice.view',$options(array('MessageLegal','MessageLegalFollowup')))
  ));
}
