<?php
declare(strict_types=1);
require_once __DIR__.'/actions.php';
require_once __DIR__.'/worker.php';

$id=array('type'=>'integer','minimum'=>1);
$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);
$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
$data=array('type'=>'object','additionalProperties'=>true);
$operation=mcpObjectSchema(array(
  'operation'=>array('type'=>'string','enum'=>array('create','update')),
  'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),
  'id'=>$id,'expectedVersion'=>$version,'data'=>$data,
  'localKey'=>array('type'=>'string','minLength'=>1,'maxLength'=>150)
),array('operation','data'));
$batch=mcpObjectSchema(array(
  'operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$operation),
  'transactionMode'=>$transaction
),array('operations'));
$delete=mcpObjectSchema(array(
  'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id')))
),array('items'));
$batchResult=mcpObjectSchema(array(
  'ok'=>array('type'=>'boolean'),'rolledBack'=>array('type'=>'boolean'),
  'transactionMode'=>$transaction,'items'=>array('type'=>'array','items'=>array('type'=>'object')),
  'effects'=>array('type'=>'array','items'=>array('type'=>'object'))
),array('ok','rolledBack','transactionMode','items'),true);
$ok=mcpObjectSchema(array(
  'ok'=>array('type'=>'boolean'),'items'=>array('type'=>'array','items'=>array('type'=>'object')),
  'effects'=>array('type'=>'array','items'=>array('type'=>'object'))
),array('ok'),true);
$uploadId=array('type'=>'string','minLength'=>1,'maxLength'=>200);

return array('id'=>'tools','version'=>'4.0.0','dependencies'=>array('core','configuration'),'enabledStateRequirements'=>array(),'actions'=>array(
  'tools.document.manage'=>mcpActionSpec($batch,$batchResult,'write',false,'mcpToolsDocumentManage',array(
    'tool:documentExplorerColumnAction','tool:documentExplorerMove',
  ),'tools.document.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.document.rights'=>mcpActionSpec($batch,$batchResult,'administrative',false,'mcpToolsDocumentRights',array('tool:saveDocumentRight'),'tools.document.rights',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.document.version'=>mcpActionSpec(mcpObjectSchema(array(
    'uploadId'=>$uploadId,'idDocument'=>$id,'version'=>array('type'=>'integer','minimum'=>0),
    'revision'=>array('type'=>'integer','minimum'=>0),'draft'=>array('type'=>'integer','minimum'=>0),
    'versionDate'=>array('type'=>'string','minLength'=>10,'maxLength'=>30),'idStatus'=>$id,
    'description'=>array('type'=>'string','maxLength'=>4000),'isRef'=>array('type'=>'boolean'),'expectedDocumentVersion'=>$version
  ),array('uploadId','idDocument','version','revision','versionDate')),$ok,'write',true,'mcpToolsDocumentVersionWorker',array('tool:saveDocumentVersion'),'tools.document.version',array('availability'=>'mcpToolsActionAvailable')),
  'tools.document.extract'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'kind'=>array('type'=>'string','enum'=>array('document_version','attachment')),'id'=>$id
    ),array('kind','id'))),'preserveUploadedFileName'=>array('type'=>'boolean')
  ),array('items')),$ok,'read',true,'mcpToolsDocumentExtractWorker',array('tool:extractDocumentFromObject'),'tools.document.extract',array('retryPolicy'=>'safe','availability'=>'mcpToolsActionAvailable')),
  'tools.document.version.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteVersions',array('tool:removeDocumentVersion'),'tools.document.version.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.attachment.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteAttachments',array('tool:removeAttachment','tool:removeAttachmentSendMail'),'tools.attachment.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.note.manage'=>mcpActionSpec($batch,$batchResult,'write',false,'mcpToolsNoteManage',array('tool:saveNote','tool:saveNoteStream'),'tools.note.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.note.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteNotes',array('tool:removeNote'),'tools.note.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.link.manage'=>mcpActionSpec($batch,$batchResult,'write',false,'mcpToolsLinkManage',array('tool:saveLink'),'tools.link.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.link.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteLinks',array('tool:removeLink'),'tools.link.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.relationship.link'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,
      'parentClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'parentId'=>$id,'expectedVersion'=>$version
    ),array('objectClass','id','parentClass','parentId'))),'transactionMode'=>$transaction
  ),array('items')),$batchResult,'write',false,'mcpToolsRelationshipLink',array('tool:saveObjectLinkedByIdToMainObject'),'tools.relationship.link',array('availability'=>'mcpToolsActionAvailable')),
  'tools.relationship.unlink'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,
      'parentClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'expectedVersion'=>$version
    ),array('objectClass','id','parentClass')))
  ),array('items')),$batchResult,'destructive',false,'mcpToolsRelationshipUnlink',array('tool:removeObjectLinkedByIdToMainObject'),'tools.relationship.unlink',array('preview'=>'mcpToolsPreviewRelationshipUnlink','availability'=>'mcpToolsActionAvailable')),
  'tools.clone.start'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,
      'overrides'=>$data,'expectedVersion'=>$version,'copyDocumentVersions'=>array('type'=>'string','enum'=>array('none','reference','latest','all'))
    ),array('objectClass','id')))
  ),array('items')),$ok,'write',true,'mcpToolsCloneWorker',array('tool:copyDocumentTo'),'tools.clone.start',array('availability'=>'mcpToolsActionAvailable')),
  'tools.clone.schedule'=>mcpActionSpec($batch,$batchResult,'administrative',false,'mcpToolsCloneSchedule',array('tool:saveDataCloning'),'tools.clone.schedule',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.notification.status'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'id'=>$id,'statusId'=>$id,'idle'=>array('type'=>'boolean'),'expectedVersion'=>$version
    ),array('id'))),'transactionMode'=>$transaction
  ),array('items')),$batchResult,'write',false,'mcpToolsNotificationStatus',array(
    'tool:changeStatusNotification','tool:readNotification','tool:readNotificationTree','view:menuNotificationRead'
  ),'tools.notification.status',array('availability'=>'mcpToolsActionAvailable')),
  'tools.notification.subscribe'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'idAffectable'=>$id
    ),array('refType','refId','idAffectable'))),'transactionMode'=>$transaction
  ),array('items')),$batchResult,'write',false,'mcpToolsSubscribe',array('tool:saveSubscription'),'tools.notification.subscribe',array('availability'=>'mcpToolsActionAvailable')),
  'tools.notification.unsubscribe'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'idAffectable'=>$id
    ),array('refType','refId','idAffectable')))
  ),array('items')),$batchResult,'destructive',false,'mcpToolsUnsubscribe',array(),'tools.notification.unsubscribe',array('preview'=>'mcpToolsPreviewSubscriptions','availability'=>'mcpToolsActionAvailable')),
  'tools.notification.send'=>mcpActionSpec(mcpObjectSchema(array(
    'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array(
      'idUser'=>$id,'title'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),
      'content'=>array('type'=>'string','minLength'=>1,'maxLength'=>20000),
      'notificationDate'=>array('type'=>'string','minLength'=>10,'maxLength'=>30),
      'notificationTime'=>array('type'=>'string','maxLength'=>12),'idNotificationType'=>$id,
      'sendEmail'=>array('type'=>'boolean')
    ),array('idUser','title','content','notificationDate','idNotificationType')))
  ),array('items')),$ok,'external',true,'mcpToolsNotificationWorker',array(),'tools.notification.send',array('preview'=>'mcpToolsPreviewNotifications','availability'=>'mcpToolsActionAvailable')),
  'tools.mail.send'=>mcpActionSpec(mcpObjectSchema(array(
    'recipients'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>array('type'=>'string','minLength'=>3,'maxLength'=>320)),
    'subject'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),
    'body'=>array('type'=>'string','minLength'=>1,'maxLength'=>100000),
    'isHtml'=>array('type'=>'boolean'),'saveAsNote'=>array('type'=>'boolean'),
    'refType'=>array('type'=>'string','maxLength'=>100),'refId'=>$id,'expectedVersion'=>$version
  ),array('recipients','subject','body')),$ok,'external',true,'mcpToolsMailWorker',array('tool:sendMail','tool:sendMailTest'),'tools.mail.send',array('preview'=>'mcpToolsPreviewMail','availability'=>'mcpToolsMailAvailable')),
  'tools.automation.manage'=>mcpActionSpec($batch,$batchResult,'administrative',false,'mcpToolsAutomationManage',array('tool:dynamicDialogWorkflowProfileParameter','tool:saveWorkflowProfileParameter'),'tools.automation.manage',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.localization.manage'=>mcpActionSpec($batch,$batchResult,'write',false,'mcpToolsLocalizationManage',array(),'tools.localization.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.asset.manage'=>mcpActionSpec($batch,$batchResult,'write',false,'mcpToolsAssetManage',array(),'tools.asset.manage',array('availability'=>'mcpToolsActionAvailable')),

  // Existing Beta 3 action IDs and resource behavior remain stable.
  'tools.image.upload.begin'=>mcpActionSpec(mcpObjectSchema(array(
    'fileName'=>array('type'=>'string','minLength'=>1,'maxLength'=>255),
    'mimeType'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),
    'expectedBytes'=>array('type'=>'integer','minimum'=>1)
  ),array('fileName','mimeType','expectedBytes')),$ok,'write',false,'mcpToolsImageUploadBegin',array(),'tools.image.upload.begin',array('transaction'=>'none')),
  'tools.image.upload.commit'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$ok,'write',true,'mcpToolsImageUploadWorker',array('tool:uploadImage'),'tools.image.upload.commit',array('availability'=>'mcpToolsActionAvailable')),
  'import.start'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId,'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'importRunId'=>array('type'=>'string','maxLength'=>150)),array('uploadId','objectClass')),$ok,'write',true,'mcpToolsImportWorker',array('tool:importData','tool:importDataFromFile','tool:import','view:importData'),'tools.import.start'),
  'import.cleanup'=>mcpActionSpec(mcpObjectSchema(array('importRunId'=>array('type'=>'string','minLength'=>1,'maxLength'=>150),'force'=>array('type'=>'boolean')),array('importRunId')),$ok,'destructive',false,'mcpToolsCleanupImport',array(),'tools.import.cleanup',array('preview'=>'mcpToolsPreviewImport')),
  'export.start'=>mcpActionSpec(mcpObjectSchema(array('objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'filter'=>array('type'=>'object'),'format'=>array('type'=>'string','enum'=>array('json','ndjson','csv'))),array('objectClass')),$ok,'read',true,'mcpToolsExportWorker',array('tool:exportData','tool:exportPlanning'),'tools.export.start',array('retryPolicy'=>'safe')),
  'attachment.upload.begin'=>mcpActionSpec(mcpObjectSchema(array('refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'fileName'=>array('type'=>'string','minLength'=>1,'maxLength'=>255),'mimeType'=>array('type'=>'string','maxLength'=>200),'expectedBytes'=>array('type'=>'integer','minimum'=>0),'description'=>array('type'=>'string','maxLength'=>4000)),array('refType','refId','fileName','expectedBytes')),$ok,'write',false,'mcpToolsAttachmentAction',array(),'tools.attachment.begin',array('transaction'=>'none')),
  'attachment.upload.chunk'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId,'offset'=>array('type'=>'integer','minimum'=>0),'base64'=>array('type'=>'string','minLength'=>1)),array('uploadId','offset','base64')),$ok,'write',false,'mcpToolsAttachmentAction',array(),'tools.attachment.chunk',array('transaction'=>'none')),
  'attachment.upload.commit'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$ok,'write',false,'mcpToolsAttachmentAction',array('tool:saveAttachment'),'tools.attachment.commit'),
  'attachment.upload.abort'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$ok,'destructive',false,'mcpToolsAttachmentAction',array(),'tools.attachment.abort',array('transaction'=>'none','preview'=>'mcpToolsPreviewUploadAbort'))
));
