<?php
declare(strict_types=1);
require_once __DIR__.'/actions.php';
require_once __DIR__.'/worker.php';

$id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));$uploadId=array('type'=>'string','minLength'=>1,'maxLength'=>200);$short=array('type'=>'string','maxLength'=>255);$text=array('type'=>'string','maxLength'=>100000);$boolean=array('type'=>'boolean');$date=array('type'=>'string','minLength'=>10,'maxLength'=>30);
$scalar=array('type'=>array('string','integer','number','boolean','null'));
$filterProperties=array('field'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'operator'=>array('type'=>'string','enum'=>array('eq','ne','lt','lte','gt','gte','in','not_in','contains','starts_with','ends_with','is_null','is_not_null')),'value'=>array('type'=>array('string','integer','number','boolean','array','null'),'maxItems'=>500,'items'=>$scalar));
$filterLeaf=mcpObjectSchema($filterProperties,array('field','operator'));
$filterLevel1=mcpObjectSchema($filterProperties+array('all'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLeaf),'any'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLeaf),'not'=>$filterLeaf));
$filterLevel2=mcpObjectSchema($filterProperties+array('all'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLevel1),'any'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLevel1),'not'=>$filterLevel1));
$filterTree=mcpObjectSchema($filterProperties+array('all'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLevel2),'any'=>array('type'=>'array','minItems'=>1,'maxItems'=>40,'items'=>$filterLevel2),'not'=>$filterLevel2));

$operation=function(array $classes,array $fields)use($id,$version){
  return array_merge(mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update')),'objectClass'=>array('type'=>'string','enum'=>$classes),'id'=>$id,'expectedVersion'=>$version,'data'=>mcpObjectSchema($fields),'localKey'=>array('type'=>'string','minLength'=>1,'maxLength'=>150)),array('operation','data')),array('allOf'=>array(array('if'=>array('properties'=>array('operation'=>array('const'=>'update'))),'then'=>array('required'=>array('id','expectedVersion'))))));
};
$batch=function(array $classes,array $fields)use($operation,$transaction){return mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$operation($classes,$fields)),'transactionMode'=>$transaction),array('operations'));};
$delete=mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id','expectedVersion')))),array('items'));

$error=mcpObjectSchema(array('code'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'message'=>array('type'=>'string','maxLength'=>4000),'expectedVersion'=>$version,'actualVersion'=>$version),array('code','message'));
$effect=mcpObjectSchema(array('action'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'objectClass'=>array('type'=>array('string','null'),'maxLength'=>100),'id'=>$nullableId,'externalDelivery'=>$boolean,'recipientCount'=>array('type'=>'integer','minimum'=>0),'reference'=>mcpObjectSchema(array('objectClass'=>array('type'=>'string','maxLength'=>100),'id'=>$id),array('objectClass','id')),'kind'=>array('type'=>'string','maxLength'=>100),'fileName'=>$short,'fileSize'=>array('type'=>'integer','minimum'=>0)),array('action'));
$item=mcpObjectSchema(array('index'=>array('type'=>'integer','minimum'=>0),'localKey'=>array('type'=>array('string','null'),'maxLength'=>150),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','missing','present','invalid','error','sent')),'objectClass'=>array('type'=>array('string','null'),'maxLength'=>100),'id'=>$nullableId,'sourceId'=>$id,'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'concurrencyUnchecked'=>$boolean,'error'=>$error,'version'=>$version,'relatedDocumentVersionIds'=>array('type'=>'array','items'=>$id),'emailSent'=>$boolean,'recipientHash'=>array('type'=>'string','pattern'=>'^[a-f0-9]{16}$'),'fileName'=>$short,'mimeType'=>array('type'=>'string','maxLength'=>200),'fileSize'=>array('type'=>'integer','minimum'=>0),'archiveName'=>$short,'bytes'=>array('type'=>'integer','minimum'=>0),'deleteAllowed'=>$boolean),array('status'));
$batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'items'=>array('type'=>'array','items'=>$item),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'));
$simpleResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','items','effects'));

$documentFields=array('name'=>$short,'description'=>$text,'idProject'=>$id,'idDocumentDirectory'=>$id,'idDocumentType'=>$id,'idStatus'=>$id,'externalReference'=>$short,'reference'=>$short,'creationDate'=>$date,'idPrivacy'=>$id,'idle'=>$boolean);
$rightFields=array('idDocumentDirectory'=>$id,'idDocument'=>$id,'idProfile'=>$id,'idResource'=>$id,'idAccessMode'=>$id,'idle'=>$boolean);
$noteFields=array('refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'note'=>$text,'idPrivacy'=>$id,'idle'=>$boolean);
$linkFields=array('ref1Type'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'ref1Id'=>$id,'ref2Type'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'ref2Id'=>$id,'comment'=>$text,'idSynchronizationItem'=>$id,'idle'=>$boolean);
$cloneScheduleFields=array('name'=>$short,'idProject'=>$id,'idUser'=>$id,'scheduledDate'=>$date,'scheduledTime'=>array('type'=>'string','maxLength'=>12),'frequency'=>$short,'day'=>array('type'=>'integer'),'week'=>array('type'=>'integer'),'month'=>array('type'=>'integer'),'idle'=>$boolean);
$automationFields=array('name'=>$short,'idEvent'=>$id,'refType'=>array('type'=>'string','maxLength'=>100),'idStatus'=>$id,'mailTo'=>$short,'mailCc'=>$short,'mailBcc'=>$short,'subject'=>$short,'template'=>$text,'idEmailTemplate'=>$id,'idProfile'=>$id,'idWorkflow'=>$id,'idStatusFrom'=>$id,'idStatusTo'=>$id,'sendToResource'=>$boolean,'sendToContact'=>$boolean,'sendToUser'=>$boolean,'sendToProject'=>$boolean,'idle'=>$boolean);
$localizationFields=array('name'=>$short,'scope'=>$short,'idLanguage'=>$id,'idTranslator'=>$id,'idLocalizationRequest'=>$id,'reference'=>$short,'translation'=>$text,'requestedText'=>$text,'comment'=>$text,'idle'=>$boolean);
$assetFields=array('name'=>$short,'description'=>$text,'idAssetType'=>$id,'idAssetCategory'=>$id,'idResource'=>$id,'idUser'=>$id,'idProject'=>$id,'serialNumber'=>$short,'externalReference'=>$short,'acquisitionDate'=>$date,'endDate'=>$date,'idStatus'=>$id,'location'=>$short,'idle'=>$boolean);
$overrideFields=array('name'=>$short,'description'=>$text,'idProject'=>$id,'idStatus'=>$id,'externalReference'=>$short,'reference'=>$short,'idUser'=>$id,'idResource'=>$id,'idContact'=>$id,'idTeam'=>$id,'idProduct'=>$id,'idProductVersion'=>$id,'idComponent'=>$id,'idComponentVersion'=>$id,'idle'=>$boolean);
$subscriptionItem=mcpObjectSchema(array('refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'idAffectable'=>$id,'expectedTargetVersion'=>$version),array('refType','refId','idAffectable','expectedTargetVersion'));

$uploadMeta=mcpObjectSchema(array('uploadId'=>$uploadId,'kind'=>array('type'=>'string','enum'=>array('image')),'username'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'fileName'=>$short,'mimeType'=>array('type'=>'string','maxLength'=>200),'expectedBytes'=>array('type'=>'integer','minimum'=>1),'createdAt'=>array('type'=>'string','maxLength'=>40),'expiresAt'=>array('type'=>'string','maxLength'=>40)),array('uploadId','kind','username','fileName','mimeType','expectedBytes','createdAt','expiresAt'));
$imageBeginResult=mcpObjectSchema(array('ok'=>$boolean,'upload'=>$uploadMeta,'maxBytes'=>array('type'=>'integer','minimum'=>1),'chunkBytes'=>array('type'=>'integer','minimum'=>1),'nextAction'=>array('type'=>'string','enum'=>array('attachment.upload.chunk')),'commitAction'=>array('type'=>'string','enum'=>array('tools.image.upload.commit'))),array('ok','upload','maxBytes','chunkBytes','nextAction','commitAction'));
$imageResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'relativeUrl'=>array('type'=>'string','pattern'=>'^files/images/[A-Za-z0-9%._~-]+$'),'width'=>array('type'=>'integer','minimum'=>1),'height'=>array('type'=>'integer','minimum'=>1),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','items','relativeUrl','width','height','effects'));
$documentVersionResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'resource'=>array('type'=>'string','pattern'=>'^projeqtor://document-versions/[0-9]+$'),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','items','resource','effects'));
$extractItem=mcpObjectSchema(array('index'=>array('type'=>'integer','minimum'=>0),'objectClass'=>array('type'=>'string','enum'=>array('DocumentVersion','Attachment')),'id'=>$id,'archiveName'=>$short,'bytes'=>array('type'=>'integer','minimum'=>0)),array('index','objectClass','id','archiveName','bytes'));
$extractResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$extractItem),'count'=>array('type'=>'integer','minimum'=>0),'bytes'=>array('type'=>'integer','minimum'=>0),'maxBytes'=>array('type'=>'integer','minimum'=>1),'format'=>array('type'=>'string','enum'=>array('zip')),'resource'=>array('type'=>'string','pattern'=>'^projeqtor://jobs/[0-9]+/result$'),'path'=>array('type'=>'string','maxLength'=>500)),array('ok','items','count','bytes','maxBytes','format','resource','path'));
$mailResult=mcpObjectSchema(array('ok'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'recipientCount'=>array('type'=>'integer','minimum'=>0),'noteId'=>$nullableId,'effects'=>array('type'=>'array','items'=>$effect)),array('ok','items','recipientCount','noteId','effects'));
$exportResult=mcpObjectSchema(array('ok'=>$boolean,'objectClass'=>array('type'=>'string','maxLength'=>100),'format'=>array('type'=>'string','enum'=>array('json','ndjson','csv')),'count'=>array('type'=>'integer','minimum'=>0),'bytes'=>array('type'=>'integer','minimum'=>0),'maxBytes'=>array('type'=>'integer','minimum'=>1),'filtered'=>$boolean,'resource'=>array('type'=>'string','pattern'=>'^projeqtor://jobs/[0-9]+/result$'),'path'=>array('type'=>'string','maxLength'=>500)),array('ok','objectClass','format','count','bytes','maxBytes','filtered','resource','path'));
$journal=mcpObjectSchema(array('id'=>$id,'importRunId'=>array('type'=>'string','maxLength'=>150),'recorded'=>array('type'=>'integer','minimum'=>0),'total'=>array('type'=>'integer','minimum'=>0)),array('id','importRunId','recorded','total'));
$importResult=mcpObjectSchema(array('ok'=>$boolean,'objectClass'=>array('type'=>'string','maxLength'=>100),'importRunId'=>array('type'=>'string','maxLength'=>150),'message'=>array('type'=>'string','maxLength'=>4000),'created'=>array('type'=>'integer','minimum'=>0),'importJournal'=>$journal),array('ok','objectClass','importRunId','message','created','importJournal'));
$cleanupCount=mcpObjectSchema(array('deleted'=>array('type'=>'integer','minimum'=>0),'missing'=>array('type'=>'integer','minimum'=>0)),array('deleted','missing'));
$cleanupResult=mcpObjectSchema(array('ok'=>$boolean,'importRunId'=>array('type'=>'string','maxLength'=>150),'journalOperationId'=>$id,'force'=>$boolean,'items'=>array('type'=>'array','items'=>$item),'counts'=>$cleanupCount),array('ok','importRunId','journalOperationId','force','items','counts'));
$attachmentMeta=mcpObjectSchema(array('uploadId'=>$uploadId,'username'=>array('type'=>'string','maxLength'=>100),'refType'=>array('type'=>'string','maxLength'=>100),'refId'=>$id,'fileName'=>$short,'mimeType'=>array('type'=>'string','maxLength'=>200),'description'=>array('type'=>'string','maxLength'=>4000),'expectedBytes'=>array('type'=>'integer','minimum'=>0),'createdAt'=>array('type'=>'string','maxLength'=>40),'expiresAt'=>array('type'=>'string','maxLength'=>40)),array('uploadId','username','refType','refId','fileName','mimeType','description','expectedBytes','createdAt','expiresAt'));
$attachmentBeginResult=mcpObjectSchema(array('ok'=>$boolean,'upload'=>$attachmentMeta,'chunkBytes'=>array('type'=>'integer','minimum'=>1)),array('ok','upload','chunkBytes'));
$chunkResult=mcpObjectSchema(array('ok'=>$boolean,'uploadId'=>$uploadId,'receivedBytes'=>array('type'=>'integer','minimum'=>0),'expectedBytes'=>array('type'=>'integer','minimum'=>0)),array('ok','uploadId','receivedBytes','expectedBytes'));
$abortResult=mcpObjectSchema(array('ok'=>$boolean,'uploadId'=>$uploadId,'status'=>array('type'=>'string','enum'=>array('aborted'))),array('ok','uploadId','status'));
$attachmentObject=mcpObjectSchema(array('id'=>$id,'refType'=>array('type'=>'string','maxLength'=>100),'refId'=>$id,'fileName'=>$short,'description'=>array('type'=>'string','maxLength'=>4000),'type'=>array('type'=>'string','maxLength'=>30),'idUser'=>$id,'creationDate'=>$date,'subDirectory'=>array('type'=>'string','maxLength'=>500),'fileSize'=>array('type'=>'integer','minimum'=>0),'mimeType'=>array('type'=>'string','maxLength'=>200),'_version'=>$version),array('id','refType','refId','fileName'));
$attachmentCommitResult=mcpObjectSchema(array('ok'=>$boolean,'attachment'=>$attachmentObject,'resource'=>array('type'=>'string','pattern'=>'^projeqtor://attachments/[0-9]+$')),array('ok','attachment','resource'));

return array('id'=>'tools','version'=>'4.0.0','dependencies'=>array('core','configuration'),'enabledStateRequirements'=>array(),'actions'=>array(
  'tools.document.manage'=>mcpActionSpec($batch(array('Document','DocumentDirectory'),$documentFields),$batchResult,'write',false,'mcpToolsDocumentManage',array('tool:documentExplorerColumnAction','tool:documentExplorerMove'),'tools.document.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.document.rights'=>mcpActionSpec($batch(array('DocumentRight'),$rightFields),$batchResult,'administrative',false,'mcpToolsDocumentRights',array('tool:saveDocumentRight'),'tools.document.rights',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.document.version'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId,'idDocument'=>$id,'version'=>array('type'=>'integer','minimum'=>0),'revision'=>array('type'=>'integer','minimum'=>0),'draft'=>array('type'=>'integer','minimum'=>0),'versionDate'=>$date,'idStatus'=>$id,'description'=>array('type'=>'string','maxLength'=>4000),'isRef'=>$boolean,'expectedDocumentVersion'=>$version),array('uploadId','idDocument','version','revision','versionDate','expectedDocumentVersion')),$documentVersionResult,'write',true,'mcpToolsDocumentVersionWorker',array('tool:saveDocumentVersion'),'tools.document.version',array('availability'=>'mcpToolsActionAvailable')),
  'tools.document.extract'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('kind'=>array('type'=>'string','enum'=>array('document_version','attachment')),'id'=>$id),array('kind','id'))),'preserveUploadedFileName'=>$boolean),array('items')),$extractResult,'read',true,'mcpToolsDocumentExtractWorker',array('tool:extractDocumentFromObject'),'tools.document.extract',array('retryPolicy'=>'safe','availability'=>'mcpToolsActionAvailable')),
  'tools.document.version.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteVersions',array('tool:removeDocumentVersion'),'tools.document.version.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.attachment.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteAttachments',array('tool:removeAttachment','tool:removeAttachmentSendMail'),'tools.attachment.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.note.manage'=>mcpActionSpec($batch(array('Note'),$noteFields),$batchResult,'write',false,'mcpToolsNoteManage',array('tool:saveNote','tool:saveNoteStream'),'tools.note.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.note.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteNotes',array('tool:removeNote'),'tools.note.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.link.manage'=>mcpActionSpec($batch(array('Link'),$linkFields),$batchResult,'write',false,'mcpToolsLinkManage',array('tool:saveLink'),'tools.link.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.link.delete'=>mcpActionSpec($delete,$batchResult,'destructive',false,'mcpToolsDeleteLinks',array('tool:removeLink'),'tools.link.delete',array('preview'=>'mcpToolsPreviewDeletes','availability'=>'mcpToolsActionAvailable')),
  'tools.relationship.link'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,'parentClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'parentId'=>$id,'expectedVersion'=>$version),array('objectClass','id','parentClass','parentId','expectedVersion'))),'transactionMode'=>$transaction),array('items')),$batchResult,'write',false,'mcpToolsRelationshipLink',array('tool:saveObjectLinkedByIdToMainObject'),'tools.relationship.link',array('availability'=>'mcpToolsActionAvailable')),
  'tools.relationship.unlink'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,'parentClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'expectedVersion'=>$version),array('objectClass','id','parentClass','expectedVersion')))),array('items')),$batchResult,'destructive',false,'mcpToolsRelationshipUnlink',array('tool:removeObjectLinkedByIdToMainObject'),'tools.relationship.unlink',array('preview'=>'mcpToolsPreviewRelationshipUnlink','availability'=>'mcpToolsActionAvailable')),
  'tools.clone.start'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'id'=>$id,'overrides'=>mcpObjectSchema($overrideFields),'expectedVersion'=>$version,'copyDocumentVersions'=>array('type'=>'string','enum'=>array('none','reference','latest','all'))),array('objectClass','id','expectedVersion')))),array('items')),$simpleResult,'write',true,'mcpToolsCloneWorker',array('tool:copyDocumentTo'),'tools.clone.start',array('availability'=>'mcpToolsActionAvailable')),
  'tools.clone.schedule'=>mcpActionSpec($batch(array('DataCloning'),$cloneScheduleFields),$batchResult,'administrative',false,'mcpToolsCloneSchedule',array('tool:saveDataCloning'),'tools.clone.schedule',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.notification.status'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('id'=>$id,'statusId'=>$id,'idle'=>$boolean,'expectedVersion'=>$version),array('id','expectedVersion'))),'transactionMode'=>$transaction),array('items')),$batchResult,'write',false,'mcpToolsNotificationStatus',array('tool:changeStatusNotification','tool:readNotification','tool:readNotificationTree','view:menuNotificationRead'),'tools.notification.status',array('availability'=>'mcpToolsActionAvailable')),
  'tools.notification.subscribe'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$subscriptionItem),'transactionMode'=>$transaction),array('items')),$batchResult,'write',false,'mcpToolsSubscribe',array('tool:saveSubscription'),'tools.notification.subscribe',array('availability'=>'mcpToolsActionAvailable')),
  'tools.notification.unsubscribe'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'idAffectable'=>$id,'expectedVersion'=>$version),array('refType','refId','idAffectable','expectedVersion')))),array('items')),$batchResult,'destructive',false,'mcpToolsUnsubscribe',array(),'tools.notification.unsubscribe',array('preview'=>'mcpToolsPreviewSubscriptions','availability'=>'mcpToolsActionAvailable')),
  'tools.notification.send'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>mcpObjectSchema(array('idUser'=>$id,'title'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'content'=>array('type'=>'string','minLength'=>1,'maxLength'=>20000),'notificationDate'=>$date,'notificationTime'=>array('type'=>'string','maxLength'=>12),'idNotificationType'=>$id,'sendEmail'=>$boolean),array('idUser','title','content','notificationDate','idNotificationType')))),array('items')),$simpleResult,'external',true,'mcpToolsNotificationWorker',array(),'tools.notification.send',array('preview'=>'mcpToolsPreviewNotifications','availability'=>'mcpToolsActionAvailable')),
  'tools.mail.send'=>mcpActionSpec(mcpObjectSchema(array('recipients'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>array('type'=>'string','minLength'=>3,'maxLength'=>320)),'subject'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'body'=>$text,'isHtml'=>$boolean,'saveAsNote'=>$boolean,'refType'=>array('type'=>'string','maxLength'=>100),'refId'=>$id,'expectedVersion'=>$version),array('recipients','subject','body'),false)+array('allOf'=>array(array('if'=>array('required'=>array('refType','refId')),'then'=>array('required'=>array('expectedVersion'))))),$mailResult,'external',true,'mcpToolsMailWorker',array('tool:sendMail','tool:sendMailTest'),'tools.mail.send',array('preview'=>'mcpToolsPreviewMail','availability'=>'mcpToolsMailAvailable')),
  'tools.automation.manage'=>mcpActionSpec($batch(array('NotificationDefinition','EventForMail','StatusMail','StatusMailPerProject','EmailTemplate'),$automationFields),$batchResult,'administrative',false,'mcpToolsAutomationManage',array('tool:dynamicDialogWorkflowProfileParameter'),'tools.automation.manage',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.localization.manage'=>mcpActionSpec($batch(array('LocalizationItem','LocalizationRequest','LocalizationTranslator','LocalizationTranslatorLanguage'),$localizationFields),$batchResult,'administrative',false,'mcpToolsLocalizationManage',array(),'tools.localization.manage',array('preview'=>'mcpToolsPreviewAdministrativeBatch','availability'=>'mcpToolsActionAvailable')),
  'tools.asset.manage'=>mcpActionSpec($batch(array('Asset','AssetCategory','AssetType'),$assetFields),$batchResult,'write',false,'mcpToolsAssetManage',array(),'tools.asset.manage',array('availability'=>'mcpToolsActionAvailable')),
  'tools.image.upload.begin'=>mcpActionSpec(mcpObjectSchema(array('fileName'=>$short,'mimeType'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'expectedBytes'=>array('type'=>'integer','minimum'=>1,'maximum'=>MCP_TOOLS_IMAGE_HARD_MAX_BYTES)),array('fileName','mimeType','expectedBytes')),$imageBeginResult,'write',false,'mcpToolsImageUploadBegin',array(),'tools.image.upload.begin',array('transaction'=>'none')),
  'tools.image.upload.commit'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$imageResult,'administrative',true,'mcpToolsImageUploadWorker',array('tool:uploadImage'),'tools.image.upload.commit',array('preview'=>'mcpToolsPreviewImageCommit','availability'=>'mcpToolsActionAvailable')),
  'import.start'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId,'objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'importRunId'=>array('type'=>'string','maxLength'=>150)),array('uploadId','objectClass')),$importResult,'write',true,'mcpToolsImportWorker',array('tool:import','view:importData'),'tools.import.start'),
  'import.cleanup'=>mcpActionSpec(mcpObjectSchema(array('importRunId'=>array('type'=>'string','minLength'=>1,'maxLength'=>150),'force'=>$boolean),array('importRunId')),$cleanupResult,'destructive',false,'mcpToolsCleanupImport',array(),'tools.import.cleanup',array('preview'=>'mcpToolsPreviewImport')),
  'export.start'=>mcpActionSpec(mcpObjectSchema(array('objectClass'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'filter'=>$filterTree,'format'=>array('type'=>'string','enum'=>array('json','ndjson','csv'))),array('objectClass')),$exportResult,'read',true,'mcpToolsExportWorker',array(),'tools.export.start',array('retryPolicy'=>'safe')),
  'attachment.upload.begin'=>mcpActionSpec(mcpObjectSchema(array('refType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'refId'=>$id,'fileName'=>$short,'mimeType'=>array('type'=>'string','maxLength'=>200),'expectedBytes'=>array('type'=>'integer','minimum'=>0),'description'=>array('type'=>'string','maxLength'=>4000)),array('refType','refId','fileName','expectedBytes')),$attachmentBeginResult,'write',false,'mcpToolsAttachmentAction',array(),'tools.attachment.begin',array('transaction'=>'none')),
  'attachment.upload.chunk'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId,'offset'=>array('type'=>'integer','minimum'=>0),'base64'=>array('type'=>'string','minLength'=>1)),array('uploadId','offset','base64')),$chunkResult,'write',false,'mcpToolsAttachmentAction',array(),'tools.attachment.chunk',array('transaction'=>'none')),
  'attachment.upload.commit'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$attachmentCommitResult,'write',false,'mcpToolsAttachmentAction',array('tool:saveAttachment'),'tools.attachment.commit'),
  'attachment.upload.abort'=>mcpActionSpec(mcpObjectSchema(array('uploadId'=>$uploadId),array('uploadId')),$abortResult,'destructive',false,'mcpToolsAttachmentAction',array(),'tools.attachment.abort',array('transaction'=>'none','preview'=>'mcpToolsPreviewUploadAbort'))
));