<?php
declare(strict_types=1);

require_once __DIR__ . '/lib/coverage-v4.php';

if ($argc !== 3) {
    pqV4Fail('Usage: php generate-source-inventory-v4.php <ProjeQtOr-source> <output>', 2);
}

$root = rtrim((string) (realpath($argv[1]) ?: ''), '/');
if ($root === '' || !is_dir("$root/tool") || !is_dir("$root/view") || !is_dir("$root/report")) {
    pqV4Fail('Invalid ProjeQtOr source root: tool/, view/, and report/ are required', 2);
}

$paths = [];
foreach (['tool', 'view', 'report', 'api', 'sso', 'plugin'] as $surface) {
    if (!is_dir("$root/$surface")) {
        pqV4Fail("Missing required source surface: $surface", 2);
    }
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator("$root/$surface", FilesystemIterator::SKIP_DOTS)
    );
    foreach ($iterator as $file) {
        if (!$file->isFile() || strtolower($file->getExtension()) !== 'php') {
            continue;
        }
        $relative = substr($file->getPathname(), strlen($root) + 1);
        // This file is generated by a deployment and is not part of the pinned archive.
        if ($relative === 'tool/parametersLocation.php') {
            continue;
        }
        $paths[$relative] = $file->getPathname();
    }
}
ksort($paths, SORT_STRING);

$files = [];
$tree = hash_init('sha256');
$surfaces = [];
$roles = ['http_entrypoint' => 0, 'included_library' => 0];
$entrypointMutations = 0;
$detectedMutations = 0;
foreach ($paths as $relative => $path) {
    $source = (string) file_get_contents($path);
    $sourceHash = hash('sha256', $source);
    hash_update($tree, $relative . "\0" . $sourceHash . "\n");
    $surface = pqV4SurfaceForPath($relative);
    if ($surface === null) {
        pqV4Fail("Unrecognized source surface: $relative");
    }
    $role = pqV4SourceRole($relative);
    $mutationTypes = pqV4MutationKinds(pqV4ExecutableTokens($source));
    if ($mutationTypes !== []) {
        $detectedMutations++;
        if ($role === 'http_entrypoint') {
            $entrypointMutations++;
        }
    }
    $surfaces[$surface] = ($surfaces[$surface] ?? 0) + 1;
    $roles[$role]++;
    $files[] = [
        'id' => pqV4HandlerId($relative),
        'path' => $relative,
        'surface' => $surface,
        'sourceRole' => $role,
        'coverageClassification' => $role === 'http_entrypoint' ? 'handler_policy' : 'included_library',
        'sourceHash' => $sourceHash,
        'detectedMutationTypes' => $mutationTypes,
        'mutationCandidate' => $role === 'http_entrypoint' && $mutationTypes !== [],
    ];
}
ksort($surfaces, SORT_STRING);

$inventory = [
    'inventoryVersion' => 4,
    'sourceVersion' => PQ_V4_SOURCE_VERSION,
    'sourceArchiveSha256' => PQ_V4_SOURCE_ARCHIVE_SHA256,
    'sourceTreeHash' => hash_final($tree),
    'sourceFileCount' => count($files),
    'entrypointCount' => $roles['http_entrypoint'],
    'includedLibraryCount' => $roles['included_library'],
    'detectedMutationFileCount' => $detectedMutations,
    'mutationCandidateCount' => $entrypointMutations,
    'surfaceCounts' => $surfaces,
    'files' => $files,
];
$inventory['inventoryHash'] = pqV4StableHash($inventory['files']);

pqV4WriteJson($argv[2], $inventory);
fwrite(STDOUT, json_encode([
    'files' => $inventory['sourceFileCount'],
    'entrypoints' => $inventory['entrypointCount'],
    'libraries' => $inventory['includedLibraryCount'],
    'mutations' => $inventory['mutationCandidateCount'],
    'inventoryHash' => $inventory['inventoryHash'],
]) . "\n");
