<?php
declare(strict_types=1);

function mcpProductsModuleDescriptor(): array {
  $id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);
  $date=array('type'=>array('string','null'),'pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');$text=array('type'=>array('string','null'),'maxLength'=>4000);$short=array('type'=>array('string','null'),'maxLength'=>400);
  $operation=array('type'=>'string','enum'=>array('create','update','upsert','delete'));$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));$boolean=array('type'=>'boolean');
  $saved=mcpObjectSchema(array(),array(),true);$error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string')),array('code','message'),true);
  $itemResult=mcpObjectSchema(array(
    'index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','invalid','error')),
    'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'relatedIds'=>array('type'=>'array','items'=>$id),
    'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>$saved,'error'=>$error,'concurrencyUnchecked'=>$boolean
  ),array('status','objectClass'),false);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>array('string','null')),'id'=>array('type'=>array('integer','null'))),array('action','objectClass','id'),false);
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$itemResult),'effects'=>array('type'=>'array','maxItems'=>400,'items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
  $common=array('id'=>$id,'operation'=>$operation,'expectedVersion'=>$version,'idle'=>$boolean);
  $options=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpProductsActionAvailable','permissionClasses'=>$classes,'transaction'=>'atomic','batchLimit'=>200),$extra);};
  $guarded=function(array $classes,array $extra=array())use($options):array{return $options($classes,array_merge(array('preview'=>'mcpProductsBatchPreview','sideEffectClassification'=>'destructive'),$extra));};

  $hierarchy=mcpObjectSchema($common+array(
    'objectClass'=>array('type'=>'string','enum'=>array('Product','Component','ProductVersion','ComponentVersion')),'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'designation'=>$short,
    'idClient'=>$nullableId,'idContact'=>$nullableId,'idProduct'=>$nullableId,'idComponent'=>$nullableId,'idProductType'=>$nullableId,'idComponentType'=>$nullableId,
    'idProductVersionType'=>$nullableId,'idComponentVersionType'=>$nullableId,'versionNumber'=>$short,'idResource'=>$nullableId,'idStatus'=>$nullableId,'creationDate'=>$date,'description'=>$text,
    'initialStartDate'=>$date,'plannedStartDate'=>$date,'realStartDate'=>$date,'isStarted'=>$boolean,'initialDeliveryDate'=>$date,'plannedDeliveryDate'=>$date,'realDeliveryDate'=>$date,'isDelivered'=>$boolean,
    'initialEisDate'=>$date,'plannedEisDate'=>$date,'realEisDate'=>$date,'isEis'=>$boolean,'initialEndDate'=>$date,'plannedEndDate'=>$date,'realEndDate'=>$date
  ),array('objectClass'),false);
  $transition=mcpObjectSchema(array('objectClass'=>array('type'=>'string','enum'=>array('ProductVersion','ComponentVersion')),'id'=>$id,'expectedVersion'=>$version,'idStatus'=>$id,'isStarted'=>$boolean,'realStartDate'=>$date,'isDelivered'=>$boolean,'realDeliveryDate'=>$date,'isEis'=>$boolean,'realEisDate'=>$date,'idle'=>$boolean,'realEndDate'=>$date),array('objectClass','id','expectedVersion'),false);
  $composition=mcpObjectSchema($common+array('parentId'=>$id,'componentId'=>$id,'comment'=>$text),array('parentId','componentId'),false);
  $versionComposition=mcpObjectSchema($common+array('parentVersionId'=>$id,'componentVersionId'=>$id,'comment'=>$text),array('parentVersionId','componentVersionId'),false);
  $compatibility=mcpObjectSchema($common+array('versionAId'=>$id,'versionBId'=>$id,'comment'=>$text),array('versionAId','versionBId'),false);
  $context=mcpObjectSchema($common+array('targetType'=>array('type'=>'string','enum'=>array('Product','Component','ProductVersion','ComponentVersion')),'targetId'=>$id,'idContext'=>$id),array('targetType','targetId','idContext'),false);
  $language=mcpObjectSchema($common+array('targetType'=>array('type'=>'string','enum'=>array('Product','Component','ProductVersion','ComponentVersion')),'targetId'=>$id,'idLanguage'=>$id),array('targetType','targetId','idLanguage'),false);
  $assetLink=mcpObjectSchema($common+array('versionId'=>$id,'assetId'=>$id,'comment'=>$text),array('versionId','assetId'),false);
  $assetComposition=mcpObjectSchema(array('id'=>$id,'parentAssetId'=>$nullableId,'expectedVersion'=>$version),array('id','expectedVersion'),false);
  $projectLink=mcpObjectSchema($common+array('kind'=>array('type'=>'string','enum'=>array('product','version')),'targetId'=>$id,'idProject'=>$id,'startDate'=>$date,'endDate'=>$date),array('kind','targetId','idProject'),false);
  $feature=mcpObjectSchema($common+array('idProduct'=>$id,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200)),array('idProduct'),false);
  $otherVersion=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('upsert','delete','make_primary')),'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'scope'=>array('type'=>'string','enum'=>array('ProductVersion','ComponentVersion')),'versionId'=>$id,'comment'=>$text,'expectedVersion'=>$version),array('operation','refType','refId','scope','versionId'),false);
  $restriction=mcpObjectSchema(array('idProfile'=>$id,'mode'=>array('type'=>'string','enum'=>array('showAll','showStarted','showDelivered','showInService')),'expectedVersion'=>$version),array('idProfile','mode'),false);

  return array('id'=>'products','version'=>'4.0.0','dependencies'=>array('core','configuration'),'actions'=>array(
    'products.hierarchy.manage'=>mcpActionSpec(mcpObjectSchema(array('items'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$hierarchy),'transactionMode'=>$transaction),array('items')),$batchResult,'destructive',false,'mcpProductsHierarchyAction',array(),'products.hierarchy.manage',$guarded(array('Product','Component','ProductVersion','ComponentVersion'))),
    'products.version.transition'=>mcpActionSpec(mcpObjectSchema(array('versions'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$transition),'transactionMode'=>$transaction),array('versions')),$batchResult,'write',false,'mcpProductsVersionTransitionAction',array(),'products.version.transition',$options(array('ProductVersion','ComponentVersion'),array('sideEffectClassification'=>'write'))),
    'products.composition.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$composition),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsCompositionAction',array('tool:saveProductStructure','tool:removeProductStructure'),'products.composition.update',$guarded(array('ProductStructure','Product','Component'))),
    'products.version_composition.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$versionComposition),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsVersionCompositionAction',array('tool:saveProductVersionStructure','tool:removeProductVersionStructure'),'products.version-composition.update',$guarded(array('ProductVersionStructure','ProductVersion','ComponentVersion'))),
    'products.version_composition.upgrade'=>mcpActionSpec(mcpObjectSchema(array('productVersionId'=>$id,'structureId'=>$id),array('productVersionId')),$batchResult,'destructive',true,'mcpProductsUpgradeWorker',array('tool:upgradeProductVersionStructure'),'products.version-composition.upgrade',$guarded(array('ProductVersionStructure','ProductVersion','ComponentVersion'),array('preview'=>'mcpProductsUpgradePreview','retryPolicy'=>'recovery_required','transaction'=>'worker'))),
    'products.compatibility.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$compatibility),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsCompatibilityAction',array('tool:saveVersionCompatibility','tool:removeVersionCompatibility'),'products.compatibility.update',$guarded(array('VersionCompatibility','ProductVersion','ComponentVersion'))),
    'products.context.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$context),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsContextAction',array('tool:saveProductContext','tool:removeProductContext'),'products.context.update',$guarded(array('ProductContext','VersionContext'))),
    'products.language.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$language),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsLanguageAction',array('tool:saveProductLanguage','tool:removeProductLanguage'),'products.language.update',$guarded(array('ProductLanguage','VersionLanguage'))),
    'products.asset.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$assetLink),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsAssetLinkAction',array('tool:saveProductAsset','tool:removeProductVersionStructureAsset'),'products.asset.update',$guarded(array('ProductAsset','Asset','ProductVersion','ComponentVersion'))),
    'products.asset.composition'=>mcpActionSpec(mcpObjectSchema(array('assets'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$assetComposition),'transactionMode'=>$transaction),array('assets')),$batchResult,'write',false,'mcpProductsAssetCompositionAction',array('tool:saveAssetComposition','tool:removeAssetComposition'),'products.asset.composition',$options(array('Asset'),array('sideEffectClassification'=>'write'))),
    'products.project_links.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$projectLink),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsProjectLinksAction',array('tool:saveProductProject','tool:removeProductProject','tool:saveVersionProject','tool:removeVersionProject'),'products.project-links.update',$guarded(array('ProductProject','VersionProject','Project'))),
    'products.business_feature.update'=>mcpActionSpec(mcpObjectSchema(array('features'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$feature),'transactionMode'=>$transaction),array('features')),$batchResult,'destructive',false,'mcpProductsBusinessFeatureAction',array('tool:saveBusinessFeature','tool:removeBusinessFeature'),'products.business-feature.update',$guarded(array('BusinessFeature','Product'))),
    'products.other_version.update'=>mcpActionSpec(mcpObjectSchema(array('links'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$otherVersion),'transactionMode'=>$transaction),array('links')),$batchResult,'destructive',false,'mcpProductsOtherVersionAction',array('tool:saveOtherVersion','tool:removeOtherVersion','tool:switchOtherVersion'),'products.other-version.update',$guarded(array('OtherVersion','ProductVersion','ComponentVersion'))),
    'products.restriction.update'=>mcpActionSpec(mcpObjectSchema(array('profiles'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$restriction),'transactionMode'=>$transaction),array('profiles')),$batchResult,'administrative',false,'mcpProductsRestrictionAction',array('tool:dynamicDialogRestrictProductList','tool:saveRestrictProductList'),'products.restriction.update',$options(array('Profile'),array('preview'=>'mcpProductsBatchPreview','sideEffectClassification'=>'administrative'))),
    'products.component_filter.apply'=>mcpActionSpec(mcpObjectSchema(array('target'=>array('type'=>'string','enum'=>array('Component','ComponentVersion')),'ids'=>array('type'=>'array','maxItems'=>200,'items'=>$id)),array('target')),mcpObjectSchema(array('ok'=>$boolean,'target'=>array('type'=>'string'),'ids'=>array('type'=>'array','maxItems'=>200,'items'=>$id),'count'=>array('type'=>'integer','minimum'=>0),'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','target','ids','count','effects'),false),'write',false,'mcpProductsComponentFilterAction',array('tool:dynamicDialogProductVersionStructure','tool:filterComponentType'),'products.component-filter.apply',$options(array('Component','ComponentVersion'),array('transaction'=>'none','sideEffectClassification'=>'write')))
  ));
}
