<?php
declare(strict_types=1);

function mcpConfigurationConsistencyNames(): array {
  return array('wbs','bbs','sbs','duplicate_work','work_on_ticket','work_on_assignment','idle_propagation','missing_planning_element','work_on_activity','work_on_meeting','periodic_meeting_assignment','budget','invalid_filters','pools','project','assignment_selection','subtask_project');
}

function mcpConfigurationAdminBranchSchemas(): array {
  $id=array('type'=>'integer','minimum'=>1);$bool=array('type'=>'boolean');$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
  $checks=array('type'=>'array','minItems'=>1,'maxItems'=>17,'items'=>array('type'=>'string','enum'=>mcpConfigurationConsistencyNames()));
  $parameter=mcpObjectSchema(array('code'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_.:-]{0,119}$'),'value'=>array('type'=>'string','maxLength'=>10000),'scope'=>array('type'=>'string','enum'=>array('user','project','global')),'idProject'=>$id,'expectedVersion'=>$version),array('code','value','scope'));
  return array(
    'send_alert'=>mcpObjectSchema(array('audience'=>array('type'=>'string','enum'=>array('all','connected','users')),'userIds'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$id),'alertType'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'scheduledAt'=>array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}(?::\\d{2})?$'),'title'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'message'=>array('type'=>'string','minLength'=>1,'maxLength'=>20000),'notificationTypeId'=>$id,'sendEmail'=>$bool),array('audience','alertType','scheduledAt','title','message','notificationTypeId'),false),
    'maintenance'=>mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('delete','close','read')),'item'=>array('type'=>'string','enum'=>array('Alert','Mail','Audit','Notification','Logfile')),'olderThanDays'=>array('type'=>'integer','minimum'=>0,'maximum'=>36500)),array('operation','item','olderThanDays'),false),
    'rebuild_reference'=>mcpObjectSchema(array('objectClass'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$')),array(),false),
    'terminate_sessions'=>mcpObjectSchema(array('scope'=>array('type'=>'string','enum'=>array('all','users')),'userIds'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$id),'excludeCurrent'=>$bool),array('scope'),false),
    'set_parameters'=>mcpObjectSchema(array('parameters'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$parameter),'transactionMode'=>$transaction),array('parameters'),false),
    'check_consistency'=>mcpObjectSchema(array('checks'=>$checks),array(),false),
    'repair_consistency'=>mcpObjectSchema(array('checks'=>$checks),array(),false),
    'renumber_wbs'=>mcpObjectSchema(array('fixProjectOrder'=>$bool),array(),false),
    'execute_deferred_updates'=>mcpObjectSchema(array(),array(),false)
  );
}

function mcpConfigurationAdminTargets(): array {
  return array(
    'send_alert'=>'tools.alert.send','maintenance'=>'configuration.maintenance.run','rebuild_reference'=>'core.reference.rebuild',
    'terminate_sessions'=>'user.session.terminate','set_parameters'=>'configuration.parameter.set','check_consistency'=>'configuration.consistency.check',
    'repair_consistency'=>'configuration.consistency.repair','renumber_wbs'=>'planning.wbs.renumber','execute_deferred_updates'=>'configuration.deferred_updates.execute'
  );
}

function mcpConfigurationModuleDescriptor(): array {
$bool=array('type'=>'boolean');$positive=array('type'=>'integer','minimum'=>1);$nullablePositive=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
$resultItem=mcpObjectSchema(array('status'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>mcpObjectSchema(array(),array(),true),'idempotencyKey'=>array('type'=>'string'),'concurrencyUnchecked'=>$bool,'index'=>array('type'=>'integer','minimum'=>0),'localKey'=>array('type'=>array('string','null')),'error'=>mcpObjectSchema(array(),array(),true)),array('status','objectClass'));
$effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>array('string','null')),'id'=>array('type'=>array('integer','null'))),array('action','objectClass','id'));
$batchResult=mcpObjectSchema(array('ok'=>$bool,'rolledBack'=>$bool,'transactionMode'=>$transaction,'items'=>array('type'=>'array','items'=>$resultItem),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'));
$cronResult=mcpObjectSchema(array('ok'=>$bool,'cronStatus'=>array('type'=>'string')),array('ok','cronStatus'));
$resetResult=mcpObjectSchema(array('ok'=>$bool,'idUser'=>$positive,'status'=>array('type'=>'string','enum'=>array('reset_email_sent'))),array('ok','idUser','status'));
$admin=array('availability'=>'mcpConfigurationAdminAvailable','confirmationRequired'=>true,'batchLimit'=>200,'transaction'=>'atomic');

$userData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'resourceName'=>array('type'=>'string','maxLength'=>100),'initials'=>array('type'=>'string','maxLength'=>20),'email'=>array('type'=>'string','maxLength'=>250),'idProfile'=>$positive,'idClient'=>$positive,'idLanguage'=>$positive,'locked'=>$bool,'loginTry'=>array('type'=>'integer','minimum'=>0),'isContact'=>$bool,'isEmployee'=>$bool,'isResource'=>$bool,'startDate'=>array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$'),'idRole'=>$positive,'idCalendarDefinition'=>$positive,'idle'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'dontReceiveTeamMails'=>$bool,'idTeam'=>$positive,'idOrganization'=>$positive));
$userOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','lock','unlock','assign_profile','retire','reactivate')),'idUser'=>$positive,'idProfile'=>$positive,'expectedVersion'=>$version,'data'=>$userData),array('operation'));
$userSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$userOperation),'transactionMode'=>$transaction),array('operations'));

$profileData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'profileCode'=>array('type'=>'string','maxLength'=>20),'sortOrder'=>array('type'=>'integer','minimum'=>0),'idle'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'idAccessScopeRead'=>$positive,'idAccessScopeCreate'=>$positive,'idAccessScopeUpdate'=>$positive,'idAccessScopeDelete'=>$positive,'isNonProject'=>$bool));
$profileOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','retire','reactivate')),'profileType'=>array('type'=>'string','enum'=>array('profile','access_profile')),'id'=>$positive,'expectedVersion'=>$version,'data'=>$profileData),array('operation','profileType'));
$profileSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$profileOperation),'transactionMode'=>$transaction),array('operations'));

$accessOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('menu_access','menu_visibility','report_access','other_right')),'idProfile'=>$positive,'targetId'=>$positive,'scope'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,79}$'),'value'=>array('type'=>array('string','integer','boolean')),'expectedVersion'=>$version),array('operation','idProfile','value'));
$accessSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$accessOperation),'transactionMode'=>$transaction),array('operations'));

$workflowData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'sortOrder'=>array('type'=>'integer','minimum'=>0),'idle'=>$bool,'workflowUpdate'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'isLeaveWorkflow'=>$bool));
$workflowOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','retire','reactivate','set_profile','set_transition')),'idWorkflow'=>$positive,'idProfile'=>$positive,'idStatusFrom'=>$positive,'idStatusTo'=>$positive,'value'=>$bool,'expectedVersion'=>$version,'data'=>$workflowData),array('operation'));
$workflowSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$workflowOperation),'transactionMode'=>$transaction),array('operations'));

$moduleRequest=mcpObjectSchema(array('idModule'=>$positive,'active'=>$bool,'expectedVersion'=>$version),array('idModule','active','expectedVersion'));
$moduleSchema=mcpObjectSchema(array('modules'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$moduleRequest),'transactionMode'=>$transaction),array('modules'));
$parameterRequest=mcpObjectSchema(array('code'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_.:-]{0,119}$'),'value'=>array('type'=>'string','maxLength'=>10000),'scope'=>array('type'=>'string','enum'=>array('user','project','global')),'idProject'=>$positive,'expectedVersion'=>$version),array('code','value','scope'));
$parameterSchema=mcpObjectSchema(array('parameters'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$parameterRequest),'transactionMode'=>$transaction),array('parameters'));

$viewData=mcpObjectSchema(array('name'=>array('type'=>'string','maxLength'=>100),'refType'=>array('type'=>'string','maxLength'=>100),'isShared'=>$bool,'isDynamic'=>$bool,'isCommon'=>$bool,'isFavoriteProject'=>$bool,'sortOrder'=>array('type'=>'integer','minimum'=>0),'idLayout'=>$positive,'scope'=>array('type'=>'string','maxLength'=>100),'objectClass'=>array('type'=>'string','maxLength'=>100),'isDefault'=>$bool,'comment'=>array('type'=>'string','maxLength'=>1000),'field'=>array('type'=>'string','maxLength'=>100),'attribute'=>array('type'=>'string','maxLength'=>100),'hidden'=>$bool,'widthPct'=>array('type'=>'number','minimum'=>0),'subItem'=>array('type'=>'string','maxLength'=>100),'formatter'=>array('type'=>'string','maxLength'=>100),'isReportList'=>$bool,'idUser'=>$positive));
$viewOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','delete')),'entity'=>array('type'=>'string','enum'=>array('filter','layout','layout_column','forced_layout')),'id'=>$positive,'expectedVersion'=>$version,'data'=>$viewData),array('operation','entity'));
$viewSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$viewOperation),'transactionMode'=>$transaction),array('operations'));

$branchSchemas=mcpConfigurationAdminBranchSchemas();$branchNames=array_keys($branchSchemas);$targets=mcpConfigurationAdminTargets();$adminVariants=array();$adminResultVariants=array();
foreach($branchSchemas as $branch=>$arguments){
  $branchConst=array('type'=>'string','const'=>$branch);$adminVariants[]=mcpObjectSchema(array('branch'=>$branchConst,'arguments'=>$arguments),array('branch','arguments'),false);
  $targetEnum=$branch==='send_alert'?array('tools.alert.send','tools.notification.send'):array($targets[$branch]);
  $adminResultVariants[]=mcpObjectSchema(array('ok'=>$bool,'branch'=>$branchConst,'targetAction'=>array('type'=>'string','enum'=>$targetEnum),'status'=>array('type'=>'string','enum'=>array('completed','queued')),'queued'=>$bool,'jobId'=>$nullablePositive,'jobResource'=>array('type'=>array('string','null'),'maxLength'=>500)),array('ok','branch','targetAction','status','queued','jobId','jobResource'),false);
}
$adminSchema=mcpObjectSchema(array('branch'=>array('type'=>'string','enum'=>$branchNames),'arguments'=>mcpObjectSchema(array(),array(),true)),array('branch','arguments'),false);$adminSchema['oneOf']=$adminVariants;
$adminResult=mcpObjectSchema(array('ok'=>$bool,'branch'=>array('type'=>'string','enum'=>$branchNames),'targetAction'=>array('type'=>'string','minLength'=>3,'maxLength'=>101),'status'=>array('type'=>'string','enum'=>array('completed','queued')),'queued'=>$bool,'jobId'=>$nullablePositive,'jobResource'=>array('type'=>array('string','null'),'maxLength'=>500)),array('ok','branch','targetAction','status','queued','jobId','jobResource'),false);$adminResult['oneOf']=$adminResultVariants;

$maintenanceSchema=$branchSchemas['maintenance'];
$maintenanceEffect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('delete','update')),'objectClass'=>array('type'=>'string'),'count'=>array('type'=>array('integer','null'),'minimum'=>0)),array('action','objectClass','count'),false);
$maintenanceResult=mcpObjectSchema(array('ok'=>$bool,'operation'=>array('type'=>'string','enum'=>array('delete','close','read')),'item'=>array('type'=>'string','enum'=>array('Alert','Mail','Audit','Notification','Logfile')),'cutoff'=>array('type'=>'string','maxLength'=>30),'affectedCount'=>array('type'=>array('integer','null'),'minimum'=>0),'status'=>array('type'=>'string','enum'=>array('completed')),'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$maintenanceEffect)),array('ok','operation','item','cutoff','affectedCount','status','effects'),false);
$consistencySchema=$branchSchemas['check_consistency'];
$consistencyItem=mcpObjectSchema(array('check'=>array('type'=>'string','enum'=>mcpConfigurationConsistencyNames()),'status'=>array('type'=>'string','enum'=>array('checked','repaired','error')),'error'=>array('type'=>array('string','null'),'maxLength'=>1000)),array('check','status','error'),false);
$consistencyEffect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('consistency.repair')),'objectClass'=>array('type'=>'null'),'count'=>array('type'=>'integer','minimum'=>0)),array('action','objectClass','count'),false);
$consistencyResult=mcpObjectSchema(array('ok'=>$bool,'mode'=>array('type'=>'string','enum'=>array('check','repair')),'items'=>array('type'=>'array','minItems'=>1,'maxItems'=>17,'items'=>$consistencyItem),'completedCount'=>array('type'=>'integer','minimum'=>0),'errorCount'=>array('type'=>'integer','minimum'=>0),'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$consistencyEffect)),array('ok','mode','items','completedCount','errorCount','effects'),false);
$deferredEffect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('deferred_updates.execute')),'objectClass'=>array('type'=>'null'),'count'=>array('type'=>'integer','minimum'=>0)),array('action','objectClass','count'),false);
$deferredResult=mcpObjectSchema(array('ok'=>$bool,'processed'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('completed')),'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$deferredEffect)),array('ok','processed','status','effects'),false);

$cronField=array('type'=>'string','minLength'=>1,'maxLength'=>64,'pattern'=>'^[0-9*?/,\\-]+$');
$cronSchedule=mcpObjectSchema(array('minutes'=>$cronField,'hours'=>$cronField,'dayOfMonth'=>$cronField,'month'=>$cronField,'dayOfWeek'=>$cronField),array('minutes','hours','dayOfMonth','month','dayOfWeek'),false);
$cronConfigure=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('save_definition','activate')),'scope'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'schedule'=>$cronSchedule,'consistencyCheckMail'=>array('type'=>'string','maxLength'=>320),'expectedVersion'=>$version,'active'=>$bool),array('operation'),false);
$cronConfigure['oneOf']=array(mcpObjectSchema(array('operation'=>array('type'=>'string','const'=>'save_definition'),'scope'=>$cronConfigure['properties']['scope'],'schedule'=>$cronSchedule,'consistencyCheckMail'=>$cronConfigure['properties']['consistencyCheckMail'],'expectedVersion'=>$version),array('operation','scope','schedule'),false),mcpObjectSchema(array('operation'=>array('type'=>'string','const'=>'activate'),'active'=>$bool),array('operation','active'),false));
$cronEffect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('update')),'objectClass'=>array('type'=>'string','enum'=>array('CronExecution')),'id'=>$positive),array('action','objectClass','id'),false);
$cronConfigureResult=mcpObjectSchema(array('ok'=>$bool,'operation'=>array('type'=>'string','enum'=>array('save_definition','activate')),'scope'=>array('type'=>array('string','null'),'maxLength'=>100),'active'=>array('type'=>array('boolean','null')),'status'=>array('type'=>'string','enum'=>array('configured_disabled','starting','stopping')),'queued'=>$bool,'jobId'=>$nullablePositive,'jobResource'=>array('type'=>array('string','null'),'maxLength'=>500),'cronStatus'=>array('type'=>array('string','null'),'maxLength'=>100),'effects'=>array('type'=>'array','maxItems'=>1,'items'=>$cronEffect)),array('ok','operation','scope','active','status','queued','jobId','jobResource','cronStatus','effects'),false);

$pluginSchema=mcpObjectSchema(array('pluginId'=>array('type'=>'string','pattern'=>'^[A-Za-z0-9_.:-]{1,100}$'),'pluginName'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'installedVersion'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'availableVersion'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'recipientUserId'=>$positive,'notificationTypeId'=>$positive,'notificationDate'=>array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$')),array('pluginId','pluginName','installedVersion','availableVersion','recipientUserId','notificationTypeId'),false);
$pluginResult=mcpObjectSchema(array('ok'=>$bool,'pluginId'=>array('type'=>'string'),'installedVersion'=>array('type'=>'string'),'availableVersion'=>array('type'=>'string'),'notificationAction'=>array('type'=>'string','enum'=>array('tools.notification.send')),'status'=>array('type'=>'string','enum'=>array('queued','completed')),'queued'=>$bool,'jobId'=>$nullablePositive,'jobResource'=>array('type'=>array('string','null'),'maxLength'=>500),'effects'=>array('type'=>'array','maxItems'=>0,'items'=>mcpObjectSchema())),array('ok','pluginId','installedVersion','availableVersion','notificationAction','status','queued','jobId','jobResource','effects'),false);

return array('id'=>'configuration','version'=>'4.0.0','dependencies'=>array('core'),'actions'=>array(
  'configuration.admin.execute'=>mcpActionSpec($adminSchema,$adminResult,'administrative',false,'mcpConfigurationAdminExecute',array('tool:adminFunctionalities'),'configuration.admin.execute',array_merge($admin,array('preview'=>'mcpConfigurationAdminPreview','transaction'=>'none','delegates'=>$targets))),
  'configuration.user.manage'=>mcpActionSpec($userSchema,$batchResult,'administrative',false,'mcpConfigurationManageUsers',array(),'configuration.user.manage',$admin),
  'user.trigger_password_reset'=>mcpActionSpec(mcpObjectSchema(array('idUser'=>$positive),array('idUser')),$resetResult,'external',false,'mcpConfigurationResetPassword',array('tool:sendRequestResetPassword'),'configuration.user.reset',$admin),
  'configuration.profile.manage'=>mcpActionSpec($profileSchema,$batchResult,'administrative',false,'mcpConfigurationManageProfiles',array(),'configuration.profile.manage',$admin),
  'configuration.access.manage'=>mcpActionSpec($accessSchema,$batchResult,'administrative',false,'mcpConfigurationManageAccess',array('tool:saveParameter'),'configuration.access.manage',$admin),
  'configuration.workflow.manage'=>mcpActionSpec($workflowSchema,$batchResult,'administrative',false,'mcpConfigurationManageWorkflows',array('tool:saveWorkflowParameter','tool:saveWorkflowProfileParameter'),'configuration.workflow.manage',$admin),
  'configuration.module.set_state'=>mcpActionSpec($moduleSchema,$batchResult,'administrative',true,'mcpConfigurationModuleWorker',array('tool:saveModuleStatus','tool:resetModuleTablesInSession'),'configuration.module.set_state',array_merge($admin,array('retryPolicy'=>'recovery_required','transaction'=>'worker'))),
  'configuration.parameter.set'=>mcpActionSpec($parameterSchema,$batchResult,'administrative',false,'mcpConfigurationSetParameters',array('tool:saveUserParameter','tool:saveGlobalParameter'),'configuration.parameter.set',$admin),
  'configuration.view.manage'=>mcpActionSpec($viewSchema,$batchResult,'administrative',false,'mcpConfigurationManageViews',array('tool:saveFilter','tool:saveFilterShared','tool:shareFilter','tool:removeFilter','tool:saveLayout','tool:shareLayout','tool:removeLayout','tool:moveLayoutColumn','tool:saveSelectedLayoutColumn','tool:saveValidateLayoutForOthers'),'configuration.view.manage',$admin),
  'configuration.maintenance.run'=>mcpActionSpec($maintenanceSchema,$maintenanceResult,'destructive',false,'mcpConfigurationMaintenanceRun',array(),'configuration.maintenance.run',array_merge($admin,array('preview'=>'mcpConfigurationMaintenancePreview','transaction'=>'best_effort','retryPolicy'=>'never'))),
  'configuration.consistency.check'=>mcpActionSpec($consistencySchema,$consistencyResult,'read',false,'mcpConfigurationConsistencyCheck',array(),'configuration.consistency.check',array_merge($admin,array('confirmationRequired'=>false,'transaction'=>'best_effort','retryPolicy'=>'never'))),
  'configuration.consistency.repair'=>mcpActionSpec($consistencySchema,$consistencyResult,'destructive',false,'mcpConfigurationConsistencyRepair',array(),'configuration.consistency.repair',array_merge($admin,array('preview'=>'mcpConfigurationConsistencyPreview','transaction'=>'best_effort','retryPolicy'=>'never'))),
  'configuration.deferred_updates.execute'=>mcpActionSpec(mcpObjectSchema(),$deferredResult,'administrative',false,'mcpConfigurationDeferredUpdatesExecute',array(),'configuration.deferred-updates.execute',array_merge($admin,array('preview'=>'mcpConfigurationDeferredUpdatesPreview','transaction'=>'best_effort','retryPolicy'=>'never'))),
  'configuration.plugin_update.notify'=>mcpActionSpec($pluginSchema,$pluginResult,'external',false,'mcpConfigurationPluginUpdateNotify',array('view:menuNewGuiLeft'),'configuration.plugin-update.notify',array_merge($admin,array('preview'=>'mcpConfigurationPluginUpdatePreview','transaction'=>'none','retryPolicy'=>'never'))),
  'cron.configure'=>mcpActionSpec($cronConfigure,$cronConfigureResult,'administrative',false,'mcpConfigurationCronConfigure',array('tool:cronExecutionStandard'),'configuration.cron.configure',array_merge($admin,array('preview'=>'mcpConfigurationCronConfigurePreview','transaction'=>'none','retryPolicy'=>'never'))),
  'cron.check'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'read',false,'mcpConfigurationCronAction',array('tool:cronCheck'),'configuration.cron.check',array_merge($admin,array('confirmationRequired'=>false,'transaction'=>'none'))),
  'cron.start'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',true,'mcpConfigurationCronStartWorker',array('tool:cronActivation'),'configuration.cron.start',array_merge($admin,array('retryPolicy'=>'safe','transaction'=>'worker'))),
  'cron.stop'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',false,'mcpConfigurationCronAction',array('tool:cronStop'),'configuration.cron.stop',array_merge($admin,array('transaction'=>'none'))),
  'cron.restart'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',true,'mcpConfigurationCronRestartWorker',array('tool:cronRelaunch','tool:cronRun'),'configuration.cron.restart',array_merge($admin,array('retryPolicy'=>'safe','transaction'=>'worker')))
));
}
