<?php
declare(strict_types=1);
require_once __DIR__.'/actions.php';
require_once __DIR__.'/worker.php';

$bool=array('type'=>'boolean');$positive=array('type'=>'integer','minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
$resultItem=mcpObjectSchema(array('status'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>mcpObjectSchema(array(),array(),true),'idempotencyKey'=>array('type'=>'string'),'concurrencyUnchecked'=>$bool,'index'=>array('type'=>'integer','minimum'=>0),'localKey'=>array('type'=>array('string','null')),'error'=>mcpObjectSchema(array(),array(),true)),array('status','objectClass'));
$effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>array('string','null')),'id'=>array('type'=>array('integer','null'))),array('action','objectClass','id'));
$batchResult=mcpObjectSchema(array('ok'=>$bool,'rolledBack'=>$bool,'transactionMode'=>$transaction,'items'=>array('type'=>'array','items'=>$resultItem),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'));
$cronResult=mcpObjectSchema(array('ok'=>$bool,'cronStatus'=>array('type'=>'string')),array('ok','cronStatus'));
$resetResult=mcpObjectSchema(array('ok'=>$bool,'idUser'=>$positive,'status'=>array('type'=>'string','enum'=>array('reset_email_sent'))),array('ok','idUser','status'));
$admin=array('availability'=>'mcpConfigurationAdminAvailable','confirmationRequired'=>true,'batchLimit'=>200,'transaction'=>'atomic');

$userData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'resourceName'=>array('type'=>'string','maxLength'=>100),'initials'=>array('type'=>'string','maxLength'=>20),'email'=>array('type'=>'string','maxLength'=>250),'idProfile'=>$positive,'idClient'=>$positive,'idLanguage'=>$positive,'locked'=>$bool,'loginTry'=>array('type'=>'integer','minimum'=>0),'isContact'=>$bool,'isEmployee'=>$bool,'isResource'=>$bool,'startDate'=>array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$'),'idRole'=>$positive,'idCalendarDefinition'=>$positive,'idle'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'dontReceiveTeamMails'=>$bool,'idTeam'=>$positive,'idOrganization'=>$positive));
$userOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','lock','unlock','assign_profile','retire','reactivate')),'idUser'=>$positive,'idProfile'=>$positive,'expectedVersion'=>$version,'data'=>$userData),array('operation'));
$userSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$userOperation),'transactionMode'=>$transaction),array('operations'));

$profileData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'profileCode'=>array('type'=>'string','maxLength'=>20),'sortOrder'=>array('type'=>'integer','minimum'=>0),'idle'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'idAccessScopeRead'=>$positive,'idAccessScopeCreate'=>$positive,'idAccessScopeUpdate'=>$positive,'idAccessScopeDelete'=>$positive,'isNonProject'=>$bool));
$profileOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','retire','reactivate')),'profileType'=>array('type'=>'string','enum'=>array('profile','access_profile')),'id'=>$positive,'expectedVersion'=>$version,'data'=>$profileData),array('operation','profileType'));
$profileSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$profileOperation),'transactionMode'=>$transaction),array('operations'));

$accessOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('menu_access','menu_visibility','report_access','other_right')),'idProfile'=>$positive,'targetId'=>$positive,'scope'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,79}$'),'value'=>array('type'=>array('string','integer','boolean')),'expectedVersion'=>$version),array('operation','idProfile','value'));
$accessSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$accessOperation),'transactionMode'=>$transaction),array('operations'));

$workflowData=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>100),'sortOrder'=>array('type'=>'integer','minimum'=>0),'idle'=>$bool,'workflowUpdate'=>$bool,'description'=>array('type'=>'string','maxLength'=>4000),'isLeaveWorkflow'=>$bool));
$workflowOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','retire','reactivate','set_profile','set_transition')),'idWorkflow'=>$positive,'idProfile'=>$positive,'idStatusFrom'=>$positive,'idStatusTo'=>$positive,'value'=>$bool,'expectedVersion'=>$version,'data'=>$workflowData),array('operation'));
$workflowSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$workflowOperation),'transactionMode'=>$transaction),array('operations'));

$moduleRequest=mcpObjectSchema(array('idModule'=>$positive,'active'=>$bool,'expectedVersion'=>$version),array('idModule','active','expectedVersion'));
$moduleSchema=mcpObjectSchema(array('modules'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$moduleRequest),'transactionMode'=>$transaction),array('modules'));
$parameterRequest=mcpObjectSchema(array('code'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_.:-]{0,119}$'),'value'=>array('type'=>'string','maxLength'=>10000),'scope'=>array('type'=>'string','enum'=>array('user','project','global')),'idProject'=>$positive,'expectedVersion'=>$version),array('code','value','scope'));
$parameterSchema=mcpObjectSchema(array('parameters'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$parameterRequest),'transactionMode'=>$transaction),array('parameters'));

$viewData=mcpObjectSchema(array('name'=>array('type'=>'string','maxLength'=>100),'refType'=>array('type'=>'string','maxLength'=>100),'isShared'=>$bool,'isDynamic'=>$bool,'isCommon'=>$bool,'isFavoriteProject'=>$bool,'sortOrder'=>array('type'=>'integer','minimum'=>0),'idLayout'=>$positive,'scope'=>array('type'=>'string','maxLength'=>100),'objectClass'=>array('type'=>'string','maxLength'=>100),'isDefault'=>$bool,'comment'=>array('type'=>'string','maxLength'=>1000),'field'=>array('type'=>'string','maxLength'=>100),'attribute'=>array('type'=>'string','maxLength'=>100),'hidden'=>$bool,'widthPct'=>array('type'=>'number','minimum'=>0),'subItem'=>array('type'=>'string','maxLength'=>100),'formatter'=>array('type'=>'string','maxLength'=>100),'isReportList'=>$bool,'idUser'=>$positive));
$viewOperation=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','delete')),'entity'=>array('type'=>'string','enum'=>array('filter','layout','layout_column','forced_layout')),'id'=>$positive,'expectedVersion'=>$version,'data'=>$viewData),array('operation','entity'));
$viewSchema=mcpObjectSchema(array('operations'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$viewOperation),'transactionMode'=>$transaction),array('operations'));

return array('id'=>'configuration','version'=>'4.0.0','dependencies'=>array('core'),'actions'=>array(
  'configuration.user.manage'=>mcpActionSpec($userSchema,$batchResult,'administrative',false,'mcpConfigurationManageUsers',array(),'configuration.user.manage',$admin),
  'user.trigger_password_reset'=>mcpActionSpec(mcpObjectSchema(array('idUser'=>$positive),array('idUser')),$resetResult,'external',false,'mcpConfigurationResetPassword',array('tool:sendRequestResetPassword'),'configuration.user.reset',$admin),
  'configuration.profile.manage'=>mcpActionSpec($profileSchema,$batchResult,'administrative',false,'mcpConfigurationManageProfiles',array(),'configuration.profile.manage',$admin),
  'configuration.access.manage'=>mcpActionSpec($accessSchema,$batchResult,'administrative',false,'mcpConfigurationManageAccess',array('tool:saveParameter'),'configuration.access.manage',$admin),
  'configuration.workflow.manage'=>mcpActionSpec($workflowSchema,$batchResult,'administrative',false,'mcpConfigurationManageWorkflows',array('tool:saveWorkflowParameter','tool:saveWorkflowProfileParameter'),'configuration.workflow.manage',$admin),
  'configuration.module.set_state'=>mcpActionSpec($moduleSchema,$batchResult,'administrative',true,'mcpConfigurationModuleWorker',array('tool:saveModuleStatus','tool:resetModuleTablesInSession'),'configuration.module.set_state',array_merge($admin,array('retryPolicy'=>'recovery_required','transaction'=>'worker'))),
  'configuration.parameter.set'=>mcpActionSpec($parameterSchema,$batchResult,'administrative',false,'mcpConfigurationSetParameters',array('tool:saveUserParameter','tool:saveGlobalParameter'),'configuration.parameter.set',$admin),
  'configuration.view.manage'=>mcpActionSpec($viewSchema,$batchResult,'administrative',false,'mcpConfigurationManageViews',array('tool:saveFilter','tool:saveFilterShared','tool:shareFilter','tool:removeFilter','tool:saveLayout','tool:shareLayout','tool:removeLayout','tool:moveLayoutColumn','tool:saveSelectedLayoutColumn','tool:saveValidateLayoutForOthers'),'configuration.view.manage',$admin),
  'cron.check'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'read',false,'mcpConfigurationCronAction',array('tool:cronCheck'),'configuration.cron.check',array_merge($admin,array('confirmationRequired'=>false,'transaction'=>'none'))),
  'cron.start'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',true,'mcpConfigurationCronStartWorker',array('tool:cronActivation'),'configuration.cron.start',array_merge($admin,array('retryPolicy'=>'safe','transaction'=>'worker'))),
  'cron.stop'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',false,'mcpConfigurationCronAction',array('tool:cronStop'),'configuration.cron.stop',array_merge($admin,array('transaction'=>'none'))),
  'cron.restart'=>mcpActionSpec(mcpObjectSchema(),$cronResult,'administrative',true,'mcpConfigurationCronRestartWorker',array('tool:cronRelaunch','tool:cronRun'),'configuration.cron.restart',array_merge($admin,array('retryPolicy'=>'safe','transaction'=>'worker')))
));
