<?php
declare(strict_types=1);

function mcpFollowUpActionAvailable(array $action): bool {
  foreach($action['permissionClasses']??array() as $class){
    if(!SqlElement::class_exists((string)$class))return false;
    $policy=mcpClassPolicy((string)$class);if(!($policy['supported']??false))return false;
    try{
      if(Security::checkValidAccessForUser(null,'read',(string)$class,null,false))continue;
      if(in_array('create',$policy['operations']??array(),true)&&Security::checkValidAccessForUser(new $class(),'create',null,null,false))continue;
    }catch(Throwable $error){}
    return false;
  }
  return true;
}
function mcpFollowUpDirectAccess(object $object,string $operation): bool { try{return (bool)Security::checkValidAccessForUser($object,$operation,null,null,false);}catch(Throwable $error){return false;} }
function mcpFollowUpTarget(string $class,int $id,string $operation='read'): object { Security::checkValidClass($class);$object=new $class($id);if(!$object->id)mcpJsonError(404,'follow_up_target_not_found',"$class #$id was not found");if(!mcpFollowUpDirectAccess($object,$operation))mcpJsonError(403,'forbidden',"$operation access is denied for $class #$id");return $object; }
function mcpFollowUpRequireVersion(object $object,?string $expected): void { if(!$object->id)return;if($expected===null||$expected==='')mcpJsonError(409,'expected_version_required',get_class($object).' #'.$object->id.' requires expectedVersion');$actual=mcpObjectVersion($object);if(!hash_equals($actual,$expected))mcpJsonError(409,'version_conflict',get_class($object).' #'.$object->id.' has changed',array('expectedVersion'=>$expected,'actualVersion'=>$actual)); }
function mcpFollowUpRequireResource(int $resourceId,bool $validationOnly=false): Resource { $resource=new Resource($resourceId);if(!$resource->id||!mcpFollowUpDirectAccess($resource,'read'))mcpJsonError(404,'resource_not_found','Resource is unavailable');$self=(int)getSessionUser()->id===$resourceId;$validator=ImputationLine::getValidationRight($resourceId);if($validationOnly?!$validator:(!$self&&!$validator))mcpJsonError(403,'forbidden','Native work rights do not allow access to this resource');if(!$validationOnly&&$self&&securityGetAccessRightYesNo('menuImputation','read')!=='YES')mcpJsonError(403,'forbidden','Timesheet access is required');return $resource; }
function mcpFollowUpFields(array $source,array $allowed): array { $result=array();foreach($allowed as $field)if(array_key_exists($field,$source))$result[$field]=$source[$field];return $result; }
function mcpFollowUpSaved(object $object): array { return array('id'=>(int)$object->id,'_version'=>mcpObjectVersion($object)); }
function mcpFollowUpItem(string $status,string $class,?int $id,array $requested=array(),array $applied=array(),array $recalculated=array(),array $saved=array(),array $related=array()): array { return array('status'=>$status,'objectClass'=>$class,'id'=>$id,'relatedIds'=>array_values(array_unique(array_filter(array_map('intval',$related)))),'requestedFields'=>$requested,'appliedFields'=>$applied,'recalculatedFields'=>$recalculated,'ignoredFields'=>array(),'rejectedFields'=>array(),'saved'=>$saved,'concurrencyUnchecked'=>false); }
function mcpFollowUpEffects(array $items): array { $effects=array();foreach($items as $item){$status=(string)($item['status']??'');if(in_array($status,array('error','rolled_back'),true))continue;$action=$status==='deleted'?'delete':(in_array($status,array('created'),true)?'create':'update');if(!empty($item['id']))$effects[]=array('action'=>$action,'objectClass'=>$item['objectClass']??null,'id'=>(int)$item['id']);foreach($item['relatedIds']??array() as $id)$effects[]=array('action'=>'update','objectClass'=>null,'id'=>(int)$id);}return $effects; }
function mcpFollowUpBatch(array $entries,string $mode,callable $executor): array {
  if(count($entries)<1||count($entries)>200)mcpJsonError(400,'invalid_batch','Follow-up actions require 1 to 200 items');if(!in_array($mode,array('atomic','best_effort'),true))mcpJsonError(400,'invalid_transaction_mode','transactionMode must be atomic or best_effort');
  $items=array();$previousCapture=$GLOBALS['mcpCaptureErrors']??false;if($mode==='atomic')Sql::beginTransaction();
  foreach($entries as $index=>$entry){if($mode==='best_effort')Sql::beginTransaction();$GLOBALS['mcpCaptureErrors']=true;try{$item=$executor($entry,$index);$item['index']=$index;$items[]=$item;if($mode==='best_effort')Sql::commitTransaction();}catch(Throwable $error){
    if($mode==='best_effort')Sql::rollbackTransaction();$details=$error instanceof McpBridgeException?array_merge(array('code'=>$error->errorCode,'message'=>cleanApiMessage($error->getMessage())),$error->details):array('code'=>'follow_up_operation_failed','message'=>cleanApiMessage($error->getMessage()));$details=mcpFollowUpFields($details,array('code','message','objectClass','id','expectedVersion','actualVersion','missingFields','invalidFields','workTotal','detailTotal'));
    $items[]=array('index'=>$index,'status'=>'error','objectClass'=>'FollowUp','id'=>$entry['id']??null,'error'=>$details);
    if($mode==='atomic'){Sql::rollbackTransaction();foreach($items as &$rolledBack)if(($rolledBack['status']??'')!=='error'){$rolledBack['status']='rolled_back';$rolledBack['rejectedFields']=array_values(array_unique(array_merge($rolledBack['rejectedFields']??array(),$rolledBack['appliedFields']??array())));$rolledBack['appliedFields']=array();$rolledBack['recalculatedFields']=array();$rolledBack['saved']=array();}unset($rolledBack);return array('ok'=>false,'rolledBack'=>true,'transactionMode'=>$mode,'items'=>$items,'effects'=>array());}
  }finally{$GLOBALS['mcpCaptureErrors']=$previousCapture;}}
  if($mode==='atomic')Sql::commitTransaction();return array('ok'=>!count(array_filter($items,fn($item)=>($item['status']??'')==='error')),'rolledBack'=>false,'transactionMode'=>$mode,'items'=>$items,'effects'=>mcpFollowUpEffects($items));
}
function mcpFollowUpDate(string $date): void { $value=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$value||$value->format('Y-m-d')!==$date)mcpJsonError(400,'invalid_date',"Invalid work date '$date'"); }
function mcpFollowUpWorkContext(array $entry): array { $resourceId=(int)$entry['resourceId'];$assignment=null;$workElement=null;$refType=(string)($entry['refType']??'');$refId=(int)($entry['refId']??0);if(!empty($entry['assignmentId'])){$assignment=new Assignment((int)$entry['assignmentId']);if(!$assignment->id||((int)$assignment->idResource!==$resourceId&&!$assignment->isResourceTeam))mcpJsonError(400,'assignment_mismatch','Assignment is unavailable or belongs to another resource');$refType=(string)$assignment->refType;$refId=(int)$assignment->refId;}elseif(!empty($entry['workElementId'])){$workElement=new WorkElement((int)$entry['workElementId']);if(!$workElement->id)mcpJsonError(404,'work_element_not_found','Work element was not found');$refType=(string)$workElement->refType;$refId=(int)$workElement->refId;}elseif($refType!==''&&$refId>0){$rows=(new Assignment())->getSqlElementsFromCriteria(array('refType'=>$refType,'refId'=>$refId,'idResource'=>$resourceId),false,null,'id desc');if($rows)$assignment=reset($rows);else{$workElement=SqlElement::getSingleSqlElementFromCriteria('WorkElement',array('refType'=>$refType,'refId'=>$refId));}}else mcpJsonError(400,'missing_work_target','assignmentId, workElementId, or refType/refId is required');$target=mcpFollowUpTarget($refType,$refId,'read');return array($assignment,$workElement,$target,$refType,$refId); }
function mcpFollowUpFindWork(array $entry,?Assignment $assignment,?WorkElement $workElement,string $refType,int $refId): Work { if(!empty($entry['id'])){$work=new Work((int)$entry['id']);if(!$work->id)mcpJsonError(404,'work_not_found','Work entry was not found');}else{$criteria=array('idResource'=>(int)$entry['resourceId'],'workDate'=>(string)$entry['workDate']);if($assignment&&$assignment->id)$criteria['idAssignment']=(int)$assignment->id;elseif($workElement&&$workElement->id)$criteria['idWorkElement']=(int)$workElement->id;else{$criteria['refType']=$refType;$criteria['refId']=$refId;}$work=SqlElement::getSingleSqlElementFromCriteria('Work',$criteria);}if($work->id&&((int)$work->idResource!==(int)$entry['resourceId']||(string)$work->refType!==$refType||(int)$work->refId!==$refId))mcpJsonError(400,'work_target_mismatch','Existing work does not belong to the requested resource and target');return $work; }
function mcpFollowUpSaveDetails(Work $work,array $details): array { if(count($details)>200)mcpJsonError(400,'invalid_batch','At most 200 work details are allowed');$sum=0.0;$ids=array();foreach($details as $detail){$sum+=(float)$detail['work'];$object=!empty($detail['id'])?new WorkDetail((int)$detail['id']):new WorkDetail();if($object->id&&(int)$object->idWork!==(int)$work->id)mcpJsonError(400,'work_detail_mismatch','Work detail belongs to another work entry');$operation=(string)($detail['operation']??($object->id?'update':'create'));if($operation==='create'&&$object->id)mcpJsonError(409,'work_detail_exists','Work detail already exists');if($operation==='update'&&!$object->id)mcpJsonError(404,'work_detail_not_found','Work detail was not found');if($object->id)mcpFollowUpRequireVersion($object,$detail['expectedVersion']??null);$object->idWork=(int)$work->id;$object->work=(float)$detail['work'];$object->idWorkCategory=$detail['idWorkCategory']??null;$object->uncertainties=$detail['uncertainties']??null;$object->progress=$detail['progress']??null;$raw=$object->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'work_detail_save_failed',cleanApiMessage($raw));$ids[]=(int)$object->id;}if(abs($sum-(float)$work->work)>0.00001)mcpJsonError(400,'work_detail_total_mismatch','Work detail total must equal the work entry total',array('workTotal'=>(float)$work->work,'detailTotal'=>$sum));return $ids; }
function mcpFollowUpWorkRecordAction(array $arguments,string $username,string $action): array { return mcpFollowUpBatch($arguments['entries'],(string)($arguments['transactionMode']??'atomic'),fn(array $entry)=>mcpFollowUpWorkRecordOne($entry)); }
function mcpFollowUpWorkRecordOne(array $entry): array {
  $resourceId=(int)$entry['resourceId'];$date=(string)$entry['workDate'];mcpFollowUpDate($date);mcpFollowUpRequireResource($resourceId);if((float)$entry['work']<=0)mcpJsonError(400,'zero_work_requires_delete','Use follow_up.work.delete to remove an existing work entry');list($assignment,$workElement,$target,$refType,$refId)=mcpFollowUpWorkContext($entry);$work=mcpFollowUpFindWork($entry,$assignment,$workElement,$refType,$refId);
  $operation=(string)($entry['operation']??'upsert');if($operation==='create'&&$work->id)mcpJsonError(409,'work_exists','A work entry already exists for this target and date');if($operation==='update'&&!$work->id)mcpJsonError(404,'work_not_found','Work entry was not found');$wasNew=!$work->id;if(!$wasNew)mcpFollowUpRequireVersion($work,$entry['expectedVersion']??null);mcpRequireClassOperation('Work',$wasNew?'create':'update');
  if(($assignment&&array_key_exists('leftWork',$entry))||array_key_exists('comment',$entry)){if(!$assignment)mcpJsonError(400,'assignment_required','leftWork and comment require an assignment-backed entry');if(empty($entry['assignmentExpectedVersion']))mcpJsonError(409,'expected_version_required','Assignment changes require assignmentExpectedVersion');mcpFollowUpRequireVersion($assignment,(string)$entry['assignmentExpectedVersion']);mcpRequireClassOperation('Assignment','update');}
  $oldWork=(float)($work->work??0);$work->idResource=$resourceId;$work->idProject=(int)($target->idProject??0);$work->refType=$refType;$work->refId=$refId;$work->idAssignment=$assignment?(int)$assignment->id:null;$work->idWorkElement=$workElement?(int)$workElement->id:null;$work->work=(float)$entry['work'];$work->setDates($date);$raw=$work->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'work_save_failed',cleanApiMessage($raw));$related=array();$recalculated=array();
  if($assignment&&$assignment->id){$work->updateAssignment((float)$work->work-$oldWork);$assignment=new Assignment((int)$assignment->id);if(array_key_exists('leftWork',$entry))$assignment->leftWork=(float)$entry['leftWork'];if(array_key_exists('comment',$entry))$assignment->comment=(string)$entry['comment'];if(array_key_exists('leftWork',$entry)||array_key_exists('comment',$entry)){$saved=$assignment->saveWithRefresh();if(!in_array(getLastOperationStatus($saved),array('OK','NO_CHANGE'),true))mcpJsonError(400,'assignment_save_failed',cleanApiMessage($saved));}$related[]=(int)$assignment->id;$recalculated[]=array_key_exists('leftWork',$entry)?'assignment.leftWork':'assignment.realWork';}
  if($workElement&&$workElement->id){$workElement=new WorkElement((int)$workElement->id);$workElement->realWork=(new Work())->sumSqlElementsFromCriteria('work',array('idWorkElement'=>(int)$workElement->id));$saved=$workElement->save(true);if(!in_array(getLastOperationStatus($saved),array('OK','NO_CHANGE'),true))mcpJsonError(400,'work_element_save_failed',cleanApiMessage($saved));$related[]=(int)$workElement->id;$recalculated[]='workElement.realWork';}$detailIds=!empty($entry['details'])?mcpFollowUpSaveDetails($work,$entry['details']):array();$related=array_merge($related,$detailIds);
  return mcpFollowUpItem($wasNew?'created':'updated','Work',(int)$work->id,array_keys($entry),array('work','workDate','idResource','refType','refId'),$recalculated,mcpFollowUpSaved(new Work($work->id)),$related); }
function mcpFollowUpWorkDeleteOne(array $entry): array { $work=new Work((int)$entry['id']);if(!$work->id)mcpJsonError(404,'work_not_found','Work entry was not found');mcpFollowUpRequireResource((int)$work->idResource);mcpFollowUpTarget((string)$work->refType,(int)$work->refId,'read');mcpFollowUpRequireVersion($work,(string)$entry['expectedVersion']);mcpRequireClassOperation('Work','delete');$id=(int)$work->id;$related=array_filter(array((int)$work->idAssignment,(int)$work->idWorkElement));$raw=$work->idAssignment?$work->deleteWork():$work->delete();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'work_delete_failed',cleanApiMessage($raw));if($work->idWorkElement){$element=new WorkElement((int)$work->idWorkElement);if($element->id){$element->realWork=(new Work())->sumSqlElementsFromCriteria('work',array('idWorkElement'=>(int)$element->id));$element->save(true);}}return mcpFollowUpItem('deleted','Work',$id,array(),array(),array('assignment.leftWork','workElement.realWork'),array(),$related); }
function mcpFollowUpWorkDeleteAction(array $arguments,string $username,string $action): array { return mcpFollowUpBatch($arguments['entries'],(string)($arguments['transactionMode']??'atomic'),fn(array $entry)=>mcpFollowUpWorkDeleteOne($entry)); }
function mcpFollowUpWorkDeletePreview(array $arguments,string $username,string $action): array { $items=array();foreach($arguments['entries'] as $index=>$entry){$work=new Work((int)$entry['id']);if(!$work->id)mcpJsonError(404,'work_not_found','Work entry was not found');mcpFollowUpRequireResource((int)$work->idResource);mcpFollowUpTarget((string)$work->refType,(int)$work->refId,'read');mcpFollowUpRequireVersion($work,(string)$entry['expectedVersion']);mcpRequireClassOperation('Work','delete');$items[]=array('index'=>$index,'id'=>(int)$work->id,'resourceId'=>(int)$work->idResource,'workDate'=>(string)$work->workDate,'work'=>(float)$work->work,'refType'=>(string)$work->refType,'refId'=>(int)$work->refId,'version'=>mcpObjectVersion($work));}return array('count'=>count($items),'transactionMode'=>$arguments['transactionMode']??'atomic','items'=>$items); }
function mcpFollowUpDispatchContext(array $arguments): array { $refType=(string)$arguments['refType'];$refId=(int)$arguments['refId'];$target=mcpFollowUpTarget($refType,$refId,'update');$element=new WorkElement((int)$arguments['workElementId']);if(!$element->id||(string)$element->refType!==$refType||(int)$element->refId!==$refId)mcpJsonError(400,'work_element_mismatch','Work element does not belong to the requested object');mcpFollowUpRequireVersion($element,(string)$arguments['expectedVersion']);return array($target,$element); }
function mcpFollowUpDispatchAction(array $arguments,string $username,string $action): array {
  list($target,$element)=mcpFollowUpDispatchContext($arguments);$mode=(string)($arguments['transactionMode']??'atomic');$result=mcpFollowUpBatch($arguments['entries'],$mode,function(array $entry)use($target,$element):array{
    $operation=(string)$entry['operation'];$work=!empty($entry['id'])?new Work((int)$entry['id']):new Work();if($operation==='delete'&&!$work->id)mcpJsonError(404,'work_not_found','Dispatch deletion requires an existing work id');if($work->id&&(int)$work->idWorkElement!==(int)$element->id)mcpJsonError(400,'work_target_mismatch','Dispatch work belongs to another work element');if($work->id)mcpFollowUpRequireVersion($work,$entry['expectedVersion']??null);if($operation!=='delete'&&(!isset($entry['resourceId'],$entry['workDate'],$entry['work'])||(float)$entry['work']<=0))mcpJsonError(400,'invalid_dispatch_entry','Dispatch create/update requires resourceId, workDate and positive work');mcpRequireClassOperation('Work',$operation==='delete'?'delete':($work->id?'update':'create'));
    if($operation==='delete'){$oldId=(int)$work->id;$ass=WorkElement::updateAssignment($work,(float)$work->work*(-1));$raw=$work->delete();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'work_delete_failed',cleanApiMessage($raw));if($ass)$ass->saveWithRefresh();$item=mcpFollowUpItem('deleted','Work',$oldId,array(),array(),array('assignment.leftWork','workElement.realWork'),array(),$ass?array((int)$ass->id):array());}else{$resource=new Resource((int)$entry['resourceId']);if(!$resource->id||!mcpFollowUpDirectAccess($resource,'read'))mcpJsonError(404,'resource_not_found','Dispatch resource is unavailable');mcpFollowUpDate((string)$entry['workDate']);$old=$work->id?new Work((int)$work->id):new Work();$oldValue=(float)($old->work??0);$oldResource=(int)($old->idResource??0);$work->idResource=(int)$entry['resourceId'];$work->idProject=(int)($target->idProject??0);$work->refType=(string)$element->refType;$work->refId=(int)$element->refId;$work->idWorkElement=(int)$element->id;$work->work=(float)$entry['work'];$work->setDates((string)$entry['workDate']);if($old->id&&$oldResource!==(int)$work->idResource)WorkElement::updateAssignment($old,$oldValue*(-1));$diff=$old->id&&$oldResource===(int)$work->idResource?(float)$work->work-$oldValue:(float)$work->work;$ass=WorkElement::updateAssignment($work,$diff);$work->idAssignment=$ass?(int)$ass->id:null;$raw=$work->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'work_save_failed',cleanApiMessage($raw));if($ass)$ass->saveWithRefresh();$item=mcpFollowUpItem($old->id?'updated':'created','Work',(int)$work->id,array_keys($entry),array('work','workDate','idResource'),array('assignment.leftWork','workElement.realWork'),mcpFollowUpSaved(new Work($work->id)),$ass?array((int)$ass->id):array());}
    $current=new WorkElement((int)$element->id);$current->realWork=(new Work())->sumSqlElementsFromCriteria('work',array('idWorkElement'=>(int)$current->id));$raw=$current->save(true);if(!in_array(getLastOperationStatus($raw),array('OK','NO_CHANGE'),true))mcpJsonError(400,'work_element_save_failed',cleanApiMessage($raw));$item['relatedIds'][]=(int)$current->id;return $item;});return $result; }
function mcpFollowUpDispatchPreview(array $arguments,string $username,string $action): array { list($target,$element)=mcpFollowUpDispatchContext($arguments);$items=array();$deletes=0;foreach($arguments['entries'] as $index=>$entry){$operation=(string)$entry['operation'];$row=array('index'=>$index,'operation'=>$operation,'id'=>$entry['id']??null,'resourceId'=>$entry['resourceId']??null,'workDate'=>$entry['workDate']??null,'work'=>$entry['work']??null);if(!empty($entry['id'])){$work=new Work((int)$entry['id']);if(!$work->id||(int)$work->idWorkElement!==(int)$element->id)mcpJsonError(404,'work_not_found','Dispatch work is unavailable');mcpFollowUpRequireVersion($work,$entry['expectedVersion']??null);$row['version']=mcpObjectVersion($work);}if($operation==='delete')$deletes++;$items[]=$row;}return array('refType'=>(string)$element->refType,'refId'=>(int)$element->refId,'workElementId'=>(int)$element->id,'count'=>count($items),'deleteCount'=>$deletes,'transactionMode'=>$arguments['transactionMode']??'atomic','items'=>$items); }
function mcpFollowUpTimerAction(array $arguments,string $username,string $action): array { $refType=(string)$arguments['refType'];$refId=(int)$arguments['refId'];mcpFollowUpTarget($refType,$refId,'update');$element=new WorkElement((int)$arguments['workElementId']);if(!$element->id||(string)$element->refType!==$refType||(int)$element->refId!==$refId)mcpJsonError(404,'work_element_not_found','Work element is unavailable');mcpFollowUpRequireVersion($element,(string)$arguments['expectedVersion']);$userId=(int)getSessionUser()->id;$operation=(string)$arguments['operation'];if($operation==='stop'&&(!$element->ongoing||(int)$element->idUser!==$userId))mcpJsonError(409,'timer_not_owned','Only the actor that owns an active timer may stop it');if($operation==='start'&&$element->ongoing&&(int)$element->idUser!==$userId)mcpJsonError(409,'timer_in_use','Another user owns this timer');$active=(new WorkElement())->getSqlElementsFromCriteria(array('idUser'=>$userId,'ongoing'=>1),false,null,'id asc');$stopped=array_values(array_map(fn($item)=>(int)$item->id,array_filter($active,fn($item)=>(int)$item->id!==(int)$element->id)));Sql::beginTransaction();try{if($operation==='start')$element->start();else $element->stop();Sql::commitTransaction();}catch(Throwable $error){Sql::rollbackTransaction();throw $error;}$saved=new WorkElement((int)$element->id);$effects=array_map(fn($id)=>array('action'=>'update','objectClass'=>'WorkElement','id'=>$id),$stopped);$effects[]=array('action'=>'update','objectClass'=>'WorkElement','id'=>(int)$saved->id);return array('ok'=>true,'status'=>$operation==='start'?'started':'stopped','refType'=>$refType,'refId'=>$refId,'workElementId'=>(int)$saved->id,'ongoing'=>(bool)$saved->ongoing,'ongoingStartDateTime'=>$saved->ongoingStartDateTime?:null,'realWork'=>(float)$saved->realWork,'stoppedWorkElementIds'=>$stopped,'version'=>mcpObjectVersion($saved),'effects'=>$effects); }
function mcpFollowUpRemainingWorkAction(array $arguments,string $username,string $action): array { return mcpFollowUpBatch($arguments['assignments'],(string)($arguments['transactionMode']??'atomic'),function(array $entry):array{$assignment=new Assignment((int)$entry['assignmentId']);if(!$assignment->id)mcpJsonError(404,'assignment_not_found','Assignment was not found');$target=mcpFollowUpTarget((string)$assignment->refType,(int)$assignment->refId,'update');mcpFollowUpRequireVersion($assignment,(string)$entry['expectedVersion']);mcpRequireClassOperation('Assignment','update');$fields=array();if(array_key_exists('assignedWork',$entry)){$assignment->assignedWork=(float)$entry['assignedWork'];$fields[]='assignedWork';}if(array_key_exists('leftWork',$entry)){$assignment->leftWork=(float)$entry['leftWork'];$fields[]='leftWork';}if(!$fields)mcpJsonError(400,'missing_field','assignedWork or leftWork is required');PlanningElement::$_skipUpdateRevenue=true;try{$raw=$assignment->saveWithRefresh();}finally{PlanningElement::$_skipUpdateRevenue=false;}if(!in_array(getLastOperationStatus($raw),array('OK','NO_CHANGE'),true))mcpJsonError(400,'assignment_save_failed',cleanApiMessage($raw));return mcpFollowUpItem('updated','Assignment',(int)$assignment->id,$fields,$fields,array('planningElement'),mcpFollowUpSaved(new Assignment($assignment->id)),array((int)$target->id));}); }
function mcpFollowUpPeriod(array $entry,bool $mustExist=false): WorkPeriod { $range=(string)$entry['periodRange'];$value=(string)$entry['periodValue'];$part=(int)substr($value,4,2);if(($range==='week'&&($part<1||$part>53))||($range==='month'&&($part<1||$part>12)))mcpJsonError(400,'invalid_period','periodValue is invalid for periodRange');$period=SqlElement::getSingleSqlElementFromCriteria('WorkPeriod',array('idResource'=>(int)$entry['resourceId'],'periodRange'=>$range,'periodValue'=>$value));if($mustExist&&!$period->id)mcpJsonError(404,'work_period_not_found','Work period was not found');if($period->id)mcpFollowUpRequireVersion($period,$entry['expectedVersion']??null);else{$period->idResource=(int)$entry['resourceId'];$period->periodRange=$range;$period->periodValue=$value;$period->submitted=0;$period->validated=0;}return $period; }
function mcpFollowUpPeriodSubmitAction(array $arguments,string $username,string $action): array { $operation=(string)$arguments['operation'];return mcpFollowUpBatch($arguments['periods'],(string)($arguments['transactionMode']??'atomic'),function(array $entry)use($operation):array{mcpFollowUpRequireResource((int)$entry['resourceId']);$period=mcpFollowUpPeriod($entry,$operation==='unsubmit');mcpRequireClassOperation('WorkPeriod',$period->id?'update':'create');$period->submitted=$operation==='submit'?1:0;$period->submittedDate=$operation==='submit'?date('Y-m-d H:i:s'):null;if(array_key_exists('comment',$entry))$period->comment=$entry['comment'];$raw=$period->save();if(!in_array(getLastOperationStatus($raw),array('OK','NO_CHANGE'),true))mcpJsonError(400,'work_period_save_failed',cleanApiMessage($raw));return mcpFollowUpItem($operation==='submit'?'submitted':'unsubmitted','WorkPeriod',(int)$period->id,array('submitted','submittedDate','comment'),array('submitted','submittedDate','comment'),array(),mcpFollowUpSaved(new WorkPeriod($period->id)));}); }
function mcpFollowUpPeriodValidationAction(array $arguments,string $username,string $action): array { $decision=(string)$arguments['decision'];return mcpFollowUpBatch($arguments['periods'],(string)($arguments['transactionMode']??'atomic'),function(array $entry)use($decision):array{mcpFollowUpRequireResource((int)$entry['resourceId'],true);$period=mcpFollowUpPeriod($entry,true);mcpRequireClassOperation('WorkPeriod','update');if($decision==='validate'){$period->validated=1;$period->validatedDate=date('Y-m-d H:i:s');$period->idLocker=(int)getSessionUser()->id;$status='validated';}elseif($decision==='reject'){$period->submitted=0;$period->submittedDate=null;$period->validated=0;$period->validatedDate=null;$period->idLocker=null;$status='rejected';}else{$period->validated=0;$period->validatedDate=null;$period->idLocker=null;$status='cancelled';}if(array_key_exists('comment',$entry))$period->comment=$entry['comment'];$raw=$period->save();if(!in_array(getLastOperationStatus($raw),array('OK','NO_CHANGE'),true))mcpJsonError(400,'work_period_save_failed',cleanApiMessage($raw));return mcpFollowUpItem($status,'WorkPeriod',(int)$period->id,array('decision','comment'),array('submitted','validated','submittedDate','validatedDate','idLocker','comment'),array(),mcpFollowUpSaved(new WorkPeriod($period->id)));}); }
function mcpFollowUpRequireAlertAdmin(): void { if(securityGetAccessRightYesNo('menuAdmin','read')!=='YES')mcpJsonError(403,'forbidden','Administration access is required to generate imputation alerts'); }
function mcpFollowUpAlertPreview(array $arguments,string $username,string $action): array { mcpFollowUpRequireAlertAdmin();mcpFollowUpDate((string)$arguments['startDate']);mcpFollowUpDate((string)$arguments['endDate']);if($arguments['endDate']<$arguments['startDate'])mcpJsonError(400,'invalid_date_range','endDate must not be earlier than startDate');$deliveries=array('resource'=>$arguments['resourceDelivery']??'NO','projectLeader'=>$arguments['projectLeaderDelivery']??'NO','teamManager'=>$arguments['teamManagerDelivery']??'NO','organizationManager'=>$arguments['organizationManagerDelivery']??'NO');if(!count(array_filter($deliveries,fn($value)=>$value!=='NO')))mcpJsonError(400,'no_delivery_selected','At least one alert delivery must be enabled');return array('startDate'=>$arguments['startDate'],'endDate'=>$arguments['endDate'],'deliveries'=>$deliveries,'mayCreateAlerts'=>(bool)count(array_filter($deliveries,fn($value)=>str_contains($value,'ALERT'))),'maySendMail'=>(bool)count(array_filter($deliveries,fn($value)=>str_contains($value,'MAIL')))); }
function mcpFollowUpCommentAction(array $arguments,string $username,string $action): array { return mcpFollowUpBatch(array($arguments),'atomic',function(array $entry):array{$assignment=new Assignment((int)$entry['assignmentId']);if(!$assignment->id)mcpJsonError(404,'assignment_not_found','Assignment was not found');$target=mcpFollowUpTarget((string)$assignment->refType,(int)$assignment->refId,'update');mcpFollowUpRequireVersion($assignment,(string)$entry['expectedVersion']);mcpRequireClassOperation('Assignment','update');$stamp='['.date('Y-m-d H:i:s').']: '.(string)$entry['comment'];$assignment->comment=$stamp."\n\n".(string)$assignment->comment;$raw=$assignment->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'assignment_save_failed',cleanApiMessage($raw));$related=array();if(!empty($entry['saveAsNote'])){mcpRequireClassOperation('Note','create');$note=new Note();$note->idUser=(int)getSessionUser()->id;$note->creationDate=date('Y-m-d H:i:s');$note->refType=(string)$assignment->refType;$note->refId=(int)$assignment->refId;$note->note=nl2brForPlainText($stamp);$note->idPrivacy=1;if(!mcpFollowUpDirectAccess($note,'create'))mcpJsonError(403,'forbidden','Note creation is denied');$raw=$note->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'note_save_failed',cleanApiMessage($raw));$related[]=(int)$note->id;}return mcpFollowUpItem('updated','Assignment',(int)$assignment->id,array('comment','saveAsNote'),array('comment'),array(),mcpFollowUpSaved(new Assignment($assignment->id)),$related);}); }
function mcpFollowUpTimesheetResultAction(array $arguments,string $username,string $action): array { return mcpFollowUpBatch(array($arguments),'atomic',function(array $entry):array{$activity=mcpFollowUpTarget('Activity',(int)$entry['activityId'],'update');mcpFollowUpRequireVersion($activity,(string)$entry['expectedVersion']);mcpRequireClassOperation('Activity','update');$activity->result=$entry['result'];$raw=$activity->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'activity_save_failed',cleanApiMessage($raw));return mcpFollowUpItem('updated','Activity',(int)$activity->id,array('result'),array('result'),array(),mcpFollowUpSaved(new Activity($activity->id)));}); }
