<?php
declare(strict_types=1);

function mcpFollowUpModuleDescriptor(): array {
  $id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);
  $date=array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');$text=array('type'=>array('string','null'),'maxLength'=>4000);$boolean=array('type'=>'boolean');
  $transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));$work=array('type'=>'number','minimum'=>0);
  $saved=mcpObjectSchema(array('id'=>$id,'_version'=>$version),array(),false);$error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>$id,'expectedVersion'=>$version,'actualVersion'=>$version,'missingFields'=>array('type'=>'array','items'=>array('type'=>'string')),'invalidFields'=>array('type'=>'array','items'=>array('type'=>'string')),'workTotal'=>array('type'=>'number'),'detailTotal'=>array('type'=>'number')),array('code','message'),false);
  $item=mcpObjectSchema(array(
    'index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','submitted','unsubmitted','validated','rejected','cancelled','started','stopped','rolled_back','error')),
    'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'relatedIds'=>array('type'=>'array','maxItems'=>400,'items'=>$id),
    'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),
    'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>$saved,'error'=>$error,'concurrencyUnchecked'=>$boolean
  ),array('status','objectClass'),false);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>array('string','null')),'id'=>array('type'=>array('integer','null'))),array('action','objectClass','id'),false);
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$item),'effects'=>array('type'=>'array','maxItems'=>1000,'items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
  $options=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpFollowUpActionAvailable','permissionClasses'=>$classes,'transaction'=>'atomic','batchLimit'=>200,'sideEffectClassification'=>'write'),$extra);};
  $guarded=function(array $classes,string $preview,array $extra=array())use($options):array{return $options($classes,array_merge(array('preview'=>$preview,'sideEffectClassification'=>'destructive'),$extra));};

  $detail=mcpObjectSchema(array('id'=>$id,'operation'=>array('type'=>'string','enum'=>array('create','update','upsert')),'expectedVersion'=>$version,'work'=>$work,'idWorkCategory'=>$nullableId,'uncertainties'=>$text,'progress'=>$text),array('work'),false);
  $workEntry=mcpObjectSchema(array(
    'id'=>$id,'operation'=>array('type'=>'string','enum'=>array('create','update','upsert')),'expectedVersion'=>$version,'assignmentExpectedVersion'=>$version,
    'resourceId'=>$id,'workDate'=>$date,'assignmentId'=>$nullableId,'workElementId'=>$nullableId,'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$nullableId,
    'work'=>$work,'leftWork'=>$work,'comment'=>$text,'details'=>array('type'=>'array','maxItems'=>200,'items'=>$detail)
  ),array('resourceId','workDate','work'),false);
  $deleteEntry=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id','expectedVersion'),false);
  $dispatchEntry=mcpObjectSchema(array('id'=>$id,'operation'=>array('type'=>'string','enum'=>array('create','update','upsert','delete')),'expectedVersion'=>$version,'resourceId'=>$id,'workDate'=>$date,'work'=>$work),array('operation'),false);
  $remaining=mcpObjectSchema(array('assignmentId'=>$id,'expectedVersion'=>$version,'assignedWork'=>$work,'leftWork'=>$work),array('assignmentId','expectedVersion'),false);
  $period=mcpObjectSchema(array('resourceId'=>$id,'periodRange'=>array('type'=>'string','enum'=>array('week','month')),'periodValue'=>array('type'=>'string','pattern'=>'^\\d{6}$'),'expectedVersion'=>$version,'comment'=>$text),array('resourceId','periodRange','periodValue'),false);

  $timerResult=mcpObjectSchema(array('ok'=>$boolean,'status'=>array('type'=>'string','enum'=>array('started','stopped')),'refType'=>array('type'=>'string'),'refId'=>$id,'workElementId'=>$id,'ongoing'=>$boolean,'ongoingStartDateTime'=>array('type'=>array('string','null')),'realWork'=>array('type'=>'number'),'stoppedWorkElementIds'=>array('type'=>'array','maxItems'=>200,'items'=>$id),'version'=>$version,'effects'=>array('type'=>'array','maxItems'=>201,'items'=>$effect)),array('ok','status','refType','refId','workElementId','ongoing','realWork','stoppedWorkElementIds','version','effects'),false);
  $alertResult=mcpObjectSchema(array('ok'=>$boolean,'startDate'=>$date,'endDate'=>$date,'deliveries'=>mcpObjectSchema(array('resource'=>array('type'=>'string'),'projectLeader'=>array('type'=>'string'),'teamManager'=>array('type'=>'string'),'organizationManager'=>array('type'=>'string')),array('resource','projectLeader','teamManager','organizationManager'),false),'status'=>array('type'=>'string','enum'=>array('completed')),'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','startDate','endDate','deliveries','status','effects'),false);

  return array('id'=>'follow_up','version'=>'4.0.0','dependencies'=>array('core','planning','environment'),'actions'=>array(
    'follow_up.work.record'=>mcpActionSpec(mcpObjectSchema(array('entries'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$workEntry),'transactionMode'=>$transaction),array('entries')),$batchResult,'write',false,'mcpFollowUpWorkRecordAction',array('tool:saveImputation','tool:saveWorkDetailImputation'),'follow-up.work-record',$options(array('Work','Assignment'))),
    'follow_up.work.delete'=>mcpActionSpec(mcpObjectSchema(array('entries'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$deleteEntry),'transactionMode'=>$transaction),array('entries')),$batchResult,'destructive',false,'mcpFollowUpWorkDeleteAction',array(),'follow-up.work-delete',$guarded(array('Work'),'mcpFollowUpWorkDeletePreview')),
    'follow_up.dispatch_work.apply'=>mcpActionSpec(mcpObjectSchema(array('refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'workElementId'=>$id,'expectedVersion'=>$version,'entries'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$dispatchEntry),'transactionMode'=>$transaction),array('refType','refId','workElementId','expectedVersion','entries')),$batchResult,'destructive',false,'mcpFollowUpDispatchAction',array('tool:dynamicDialogDispatchWork','tool:saveDispatchWork'),'follow-up.dispatch-work',$guarded(array('Work'),'mcpFollowUpDispatchPreview')),
    'follow_up.timer.control'=>mcpActionSpec(mcpObjectSchema(array('refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'workElementId'=>$id,'expectedVersion'=>$version,'operation'=>array('type'=>'string','enum'=>array('start','stop'))),array('refType','refId','workElementId','expectedVersion','operation')),$timerResult,'write',false,'mcpFollowUpTimerAction',array('tool:startStopWork'),'follow-up.timer',$options(array('Work'))),
    'follow_up.remaining_work.update'=>mcpActionSpec(mcpObjectSchema(array('assignments'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$remaining),'transactionMode'=>$transaction),array('assignments')),$batchResult,'write',false,'mcpFollowUpRemainingWorkAction',array('tool:saveLeftWork'),'follow-up.remaining-work',$options(array('Assignment'))),
    'follow_up.period.submit'=>mcpActionSpec(mcpObjectSchema(array('periods'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$period),'operation'=>array('type'=>'string','enum'=>array('submit','unsubmit')),'transactionMode'=>$transaction),array('periods','operation')),$batchResult,'write',false,'mcpFollowUpPeriodSubmitAction',array('tool:submitWorkPeriod'),'follow-up.period-submit',$options(array('WorkPeriod'))),
    'follow_up.period.validate'=>mcpActionSpec(mcpObjectSchema(array('periods'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$period),'decision'=>array('type'=>'string','enum'=>array('validate','reject','cancel_validation')),'transactionMode'=>$transaction),array('periods','decision')),$batchResult,'write',false,'mcpFollowUpPeriodValidationAction',array('tool:saveImputationValidation'),'follow-up.period-validation',$options(array('WorkPeriod'))),
    'follow_up.imputation_alert.generate'=>mcpActionSpec(mcpObjectSchema(array('startDate'=>$date,'endDate'=>$date,'resourceDelivery'=>array('type'=>'string','enum'=>array('NO','ALERT','MAIL','ALERT&MAIL')),'projectLeaderDelivery'=>array('type'=>'string','enum'=>array('NO','ALERT','MAIL','ALERT&MAIL')),'teamManagerDelivery'=>array('type'=>'string','enum'=>array('NO','ALERT','MAIL','ALERT&MAIL')),'organizationManagerDelivery'=>array('type'=>'string','enum'=>array('NO','ALERT','MAIL','ALERT&MAIL')),'onlyIncompleteResource'=>$boolean,'onlyIncompleteProjectLeader'=>$boolean,'onlyIncompleteTeamManager'=>$boolean,'onlyIncompleteOrganizationManager'=>$boolean),array('startDate','endDate')),$alertResult,'external',true,'mcpFollowUpImputationAlertWorker',array('tool:generateImputationAlert'),'follow-up.imputation-alert',$options(array('Alert'),array('preview'=>'mcpFollowUpAlertPreview','retryPolicy'=>'recovery_required','transaction'=>'worker','sideEffectClassification'=>'external'))),
    'follow_up.comment.add'=>mcpActionSpec(mcpObjectSchema(array('assignmentId'=>$id,'expectedVersion'=>$version,'comment'=>array('type'=>'string','minLength'=>1,'maxLength'=>4000),'saveAsNote'=>$boolean),array('assignmentId','expectedVersion','comment')),$batchResult,'write',false,'mcpFollowUpCommentAction',array('tool:dynamicDialogCommentImputation'),'follow-up.comment',$options(array('Assignment','Note'))),
    'follow_up.timesheet.result'=>mcpActionSpec(mcpObjectSchema(array('activityId'=>$id,'expectedVersion'=>$version,'result'=>$text),array('activityId','expectedVersion','result')),$batchResult,'write',false,'mcpFollowUpTimesheetResultAction',array('tool:timesheetAddResult'),'follow-up.timesheet-result',$options(array('Activity')))
  ));
}
