<?php
declare(strict_types=1);

function mcpHrSchemas(): array {
  $id=array('type'=>'integer','minimum'=>1);$date=array('type'=>'string','pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');
  $nullableDate=array('type'=>array('string','null'),'pattern'=>'^\\d{4}-\\d{2}-\\d{2}$');$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);
  $transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));$strings=array('type'=>'array','items'=>array('type'=>'string'));
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>$id),array('action','objectClass'),true);
  $error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string')),array('code','message'),true);
  $resultItem=mcpObjectSchema(array('index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'saved'=>array('type'=>'object','additionalProperties'=>true),'requestedFields'=>$strings,'appliedFields'=>$strings,'recalculatedFields'=>$strings,'ignoredFields'=>$strings,'rejectedFields'=>$strings,'concurrencyUnchecked'=>array('type'=>'boolean'),'error'=>$error,'effects'=>array('type'=>'array','items'=>$effect)),array('index','status'),false);
  $batchResult=mcpObjectSchema(array('ok'=>array('type'=>'boolean'),'rolledBack'=>array('type'=>'boolean'),'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$resultItem),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
  $batch=fn(string $name,array $item,bool $mode=true)=>mcpObjectSchema(array_merge(array($name=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$item)),$mode?array('transactionMode'=>$transaction):array()),array($name),false);

  $employeeFields=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'initials'=>array('type'=>'string','maxLength'=>20),'email'=>array('type'=>'string','maxLength'=>200),'idCalendarDefinition'=>$id,'idProfile'=>$id,'idOrganization'=>array('type'=>array('integer','null'),'minimum'=>1),'idTeam'=>array('type'=>array('integer','null'),'minimum'=>1),'idRole'=>array('type'=>array('integer','null'),'minimum'=>1),'startDate'=>$nullableDate,'endDate'=>$nullableDate,'phone'=>array('type'=>'string','maxLength'=>100),'mobile'=>array('type'=>'string','maxLength'=>100),'description'=>array('type'=>'string','maxLength'=>4000)),array(),false);
  $employee=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update','deactivate','reactivate')),'employeeId'=>$id,'fields'=>$employeeFields,'endDate'=>$date,'expectedVersion'=>$version),array('operation'),false);
  $manager=mcpObjectSchema(array('id'=>$id,'managerId'=>$id,'employeeId'=>$id,'startDate'=>$nullableDate,'endDate'=>$nullableDate,'idle'=>array('type'=>'boolean'),'expectedVersion'=>$version),array('managerId','employeeId'),false);
  $remove=mcpObjectSchema(array('id'=>$id,'expectedVersion'=>$version),array('id','expectedVersion'),false);
  $contractFields=mcpObjectSchema(array('name'=>array('type'=>'string','minLength'=>1,'maxLength'=>200),'mission'=>array('type'=>'string','maxLength'=>4000),'idEmployee'=>$id,'idEmploymentContractType'=>$id,'startDate'=>$date,'idStatus'=>$id),array(),false);
  $contract=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update')),'contractId'=>$id,'fields'=>$contractFields,'expectedVersion'=>$version),array('operation','fields'),false);
  $closeContract=mcpObjectSchema(array('contractId'=>$id,'endDate'=>$date,'endReasonId'=>$id,'expectedVersion'=>$version),array('contractId','endDate','endReasonId','expectedVersion'),false);
  $absence=mcpObjectSchema(array('workId'=>$id,'resourceId'=>$id,'workDate'=>$date,'projectId'=>$id,'activityId'=>$id,'assignmentId'=>$id,'work'=>array('type'=>'number','minimum'=>0.000001),'expectedVersion'=>$version),array('resourceId','workDate','projectId','activityId','assignmentId','work'),false);
  $absenceDelete=mcpObjectSchema(array('workId'=>$id,'expectedVersion'=>$version),array('workId','expectedVersion'),false);
  $leave=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','update')),'leaveId'=>$id,'employeeId'=>$id,'leaveTypeId'=>$id,'statusId'=>$id,'startDate'=>$date,'startAMPM'=>array('type'=>'string','enum'=>array('AM','PM')),'endDate'=>$date,'endAMPM'=>array('type'=>'string','enum'=>array('AM','PM')),'comment'=>array('type'=>'string','maxLength'=>4000),'expectedVersion'=>$version),array('operation','employeeId','leaveTypeId','statusId','startDate','startAMPM','endDate','endAMPM'),false);
  $decision=mcpObjectSchema(array('leaveId'=>$id,'statusId'=>$id,'comment'=>array('type'=>'string','maxLength'=>4000),'expectedVersion'=>$version),array('leaveId','statusId','expectedVersion'),false);
  $leaveDelete=mcpObjectSchema(array('leaveId'=>$id,'expectedVersion'=>$version),array('leaveId','expectedVersion'),false);
  $entitlement=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('create','adjust','close')),'entitlementId'=>$id,'employeeId'=>$id,'leaveTypeId'=>$id,'startDate'=>$nullableDate,'endDate'=>$nullableDate,'quantity'=>array('type'=>array('number','null'),'minimum'=>0),'leftQuantity'=>array('type'=>array('number','null'),'minimum'=>0),'idle'=>array('type'=>'boolean'),'expectedVersion'=>$version),array('operation'),false);
  $skill=mcpObjectSchema(array('id'=>$id,'resourceId'=>$id,'skillId'=>$id,'skillLevelId'=>$id,'useSince'=>$nullableDate,'useUntil'=>$nullableDate,'comment'=>array('type'=>'string','maxLength'=>4000),'idle'=>array('type'=>'boolean'),'expectedVersion'=>$version),array('resourceId','skillId','skillLevelId'),false);
  $move=mcpObjectSchema(array('skillId'=>$id,'targetSkillId'=>$id,'position'=>array('type'=>'string','enum'=>array('before','after')),'expectedVersion'=>$version),array('skillId','targetSkillId','position','expectedVersion'),false);
  $roleList=array('type'=>'array','uniqueItems'=>true,'items'=>array('type'=>'string','enum'=>array('A','M','m','E','O','S'))); $permission=mcpObjectSchema(array('menuName'=>array('type'=>'string','pattern'=>'^menu[A-Za-z0-9_]{1,100}$'),'viewAccess'=>$roleList,'readAccess'=>$roleList,'createAccess'=>$roleList,'updateAccess'=>$roleList,'deleteAccess'=>$roleList,'seeAllAccess'=>$roleList),array('menuName'),false);
  $calendarResult=mcpObjectSchema(array('ok'=>array('type'=>'boolean'),'format'=>array('type'=>'string','enum'=>array('xlsx','csv','json')),'count'=>array('type'=>'integer','minimum'=>0),'period'=>mcpObjectSchema(array('startDate'=>$date,'endDate'=>$date),array('startDate','endDate'),false),'resource'=>array('type'=>'string','pattern'=>'^projeqtor:\/\/jobs\/[0-9]+\/result$'),'path'=>array('type'=>'string'),'effects'=>array('type'=>'array','items'=>$effect)),array('ok','format','count','period','resource','path','effects'),false);

  return compact('id','date','transaction','batchResult','batch','employee','manager','remove','contract','closeContract','absence','absenceDelete','leave','decision','leaveDelete','entitlement','skill','move','permission','calendarResult');
}

function mcpHrModuleDescriptor(): array {
  $s=mcpHrSchemas();$batch=$s['batch'];$common=array('transaction'=>'atomic','batchLimit'=>200);
  return array('id'=>'hr','version'=>'4.0.0','dependencies'=>array('core','configuration','environment'),'enabledStateRequirements'=>array('employee-or-skill-class-installed'),'ownedClasses'=>array('Employee','EmployeeManager','EmployeesManaged','EmploymentContract','EmployeeLeaveEarned','Leave','ResourceSkill','Skill','SkillLevel','LanguageSkillLevel'),'actions'=>array(
    'hr.employee.manage'=>mcpActionSpec($batch('employees',$s['employee']),$s['batchResult'],'write',false,'mcpHrEmployeeManage',array(),'hr.employee.manage',$common+array('permissionPolicy'=>'native Employee permissions')),
    'hr.employee.manager.assign'=>mcpActionSpec($batch('assignments',$s['manager']),$s['batchResult'],'write',false,'mcpHrManagerAssign',array('tool:addEmployeesManagedBulk','tool:saveEmployeesManaged'),'hr.employee.manager.assign',$common+array('permissionPolicy'=>'native EmployeeManager update and Employee read')),
    'hr.employee.manager.remove'=>mcpActionSpec($batch('assignments',$s['remove'],false),$s['batchResult'],'destructive',false,'mcpHrManagerRemove',array('tool:removeEmployeesManaged'),'hr.employee.manager.remove',$common+array('preview'=>'mcpHrManagerRemovePreview','permissionPolicy'=>'native EmployeeManager update')),
    'hr.employment.contract.manage'=>mcpActionSpec($batch('contracts',$s['contract']),$s['batchResult'],'write',false,'mcpHrContractManage',array(),'hr.employment.contract.manage',$common+array('availability'=>'mcpHrLeaveAvailable','permissionPolicy'=>'native EmploymentContract permissions')),
    'hr.employment.contract.close'=>mcpActionSpec($batch('contracts',$s['closeContract'],false),$s['batchResult'],'destructive',false,'mcpHrContractClose',array(),'hr.employment.contract.close',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrContractClosePreview','permissionPolicy'=>'native EmploymentContract update')),
    'hr.absence.record'=>mcpActionSpec($batch('entries',$s['absence']),$s['batchResult'],'write',false,'mcpHrAbsenceRecord',array('tool:saveAbsence'),'hr.absence.record',$common+array('availability'=>'mcpHrLeaveAvailable','permissionPolicy'=>'employee scope and native Assignment read')),
    'hr.absence.remove'=>mcpActionSpec($batch('entries',$s['absenceDelete'],false),$s['batchResult'],'destructive',false,'mcpHrAbsenceRemove',array(),'hr.absence.remove',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrAbsenceRemovePreview','permissionPolicy'=>'native Work delete and employee scope')),
    'hr.leave.submit'=>mcpActionSpec($batch('requests',$s['leave']),$s['batchResult'],'write',false,'mcpHrLeaveSubmit',array('tool:saveLeaveOfCalendar'),'hr.leave.submit',$common+array('availability'=>'mcpHrLeaveAvailable','permissionPolicy'=>'native Leave permissions and employee scope')),
    'hr.leave.decide'=>mcpActionSpec($batch('decisions',$s['decision'],false),$s['batchResult'],'administrative',false,'mcpHrLeaveDecide',array('tool:saveValidOrCancelStatusLeave'),'hr.leave.decide',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrLeaveDecisionPreview','permissionPolicy'=>'employee manager or leave administrator')),
    'hr.leave.delete'=>mcpActionSpec($batch('leaves',$s['leaveDelete'],false),$s['batchResult'],'destructive',false,'mcpHrLeaveDelete',array('tool:deleteLeaveOfCalendar'),'hr.leave.delete',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrLeaveDeletePreview','permissionPolicy'=>'native Leave delete and employee scope')),
    'hr.leave.entitlement.adjust'=>mcpActionSpec($batch('entitlements',$s['entitlement'],false),$s['batchResult'],'administrative',false,'mcpHrEntitlementAdjust',array(),'hr.leave.entitlement.adjust',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrEntitlementPreview','permissionPolicy'=>'leave administrator and native entitlement permissions')),
    'hr.skill.assign'=>mcpActionSpec($batch('assignments',$s['skill']),$s['batchResult'],'write',false,'mcpHrSkillAssign',array('tool:saveResourceSkill'),'hr.skill.assign',$common+array('availability'=>'mcpHrSkillAvailable','permissionPolicy'=>'native ResourceSkill permissions')),
    'hr.skill.remove'=>mcpActionSpec($batch('assignments',$s['remove'],false),$s['batchResult'],'destructive',false,'mcpHrSkillRemove',array(),'hr.skill.remove',$common+array('availability'=>'mcpHrSkillAvailable','preview'=>'mcpHrSkillRemovePreview','permissionPolicy'=>'native ResourceSkill delete')),
    'hr.skill.hierarchy.move'=>mcpActionSpec($batch('moves',$s['move']),$s['batchResult'],'write',false,'mcpHrSkillMove',array('tool:moveSkillFromHierarchicalView'),'hr.skill.hierarchy.move',$common+array('availability'=>'mcpHrSkillAvailable','permissionPolicy'=>'native Skill update')),
    'hr.leave.calendar.export'=>mcpActionSpec(mcpObjectSchema(array('year'=>array('type'=>'integer','minimum'=>2000),'month'=>array('type'=>'integer','minimum'=>1,'maximum'=>12),'statusId'=>$s['id'],'leaveTypeId'=>$s['id'],'employeeId'=>$s['id'],'format'=>array('type'=>'string','enum'=>array('xlsx','csv','json'))),array('year','month'),false),$s['calendarResult'],'read',true,'mcpHrLeaveCalendarExportWorker',array('tool:exportLeaveCalendarOfDashboardEmployeeManager'),'hr.leave.calendar.export',array('transaction'=>'worker','retryPolicy'=>'safe','availability'=>'mcpHrLeaveAvailable','permissionPolicy'=>'native Leave read and employee scope')),
    'hr.leave.permissions.configure'=>mcpActionSpec($batch('rules',$s['permission'],false),$s['batchResult'],'administrative',false,'mcpHrLeavePermissionsConfigure',array('tool:saveLeavesSystemHabilitation'),'hr.leave.permissions.configure',$common+array('availability'=>'mcpHrLeaveAvailable','preview'=>'mcpHrLeavePermissionsPreview','permissionPolicy'=>'leave administrator and native habilitation permissions'))
  ));
}
