<?php
declare(strict_types=1);

/** Steering semantic workflows. The canonical runtime owns identity,
 * idempotency, confirmation tokens and audit records. */
function mcpSteeringActionAvailable(array $action): bool {
  foreach($action['permissionClasses']??array() as $class){
    if(!SqlElement::class_exists((string)$class))return false;
    $policy=mcpClassPolicy((string)$class);if(!($policy['supported']??false))return false;
    try{
      if(Security::checkValidAccessForUser(null,'read',(string)$class,null,false))continue;
      if(in_array('create',$policy['operations']??array(),true)&&Security::checkValidAccessForUser(new $class(),'create',null,null,false))continue;
    }catch(Throwable $error){}
    return false;
  }
  return true;
}
function mcpSteeringFields(array $item,array $allowed): array {$out=array();foreach($allowed as $field)if(array_key_exists($field,$item))$out[$field]=$item[$field];return $out;}
function mcpSteeringDirect(object $object,string $operation): bool {try{return (bool)Security::checkValidAccessForUser($object,$operation,null,null,false);}catch(Throwable $e){return false;}}
function mcpSteeringVersion(object $object,array $item,string $operation): void {
  if(!$object->id||!in_array($operation,array('update','delete'),true))return;$expected=(string)($item['expectedVersion']??'');
  if($expected==='')mcpJsonError(409,'expected_version_required','Existing Steering records require expectedVersion',array('objectClass'=>get_class($object),'id'=>(int)$object->id));
  $actual=mcpObjectVersion($object);if(!hash_equals($actual,$expected))mcpJsonError(409,'version_conflict',get_class($object).' #'.$object->id.' has changed',array('expectedVersion'=>$expected,'actualVersion'=>$actual));
}
function mcpSteeringTarget(string $class,int $id,string $operation='update'): object {
  Security::checkValidClass($class);mcpRequireClassOperation($class,$operation);$object=new $class($id);if(!$object->id)mcpJsonError(404,'steering_target_not_found',"$class #$id was not found");if(!mcpSteeringDirect($object,$operation))mcpJsonError(403,'forbidden',"$operation access is denied for $class #$id");return $object;
}
function mcpSteeringSave(object $object,string $operation,array $item,array $data,bool $parentScoped=false): array {
  $class=get_class($object);if(!$parentScoped)mcpRequireClassOperation($class,$operation==='create'?'create':$operation);mcpSteeringVersion($object,$item,$operation);if(!$parentScoped&&!mcpSteeringDirect($object,$operation))mcpJsonError(403,'forbidden',"$operation access is denied for $class");$id=(int)($object->id??0);
  if($operation==='delete'){SqlElement::setDeleteConfirmed();$raw=$object->delete();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'delete_failed',cleanApiMessage($raw));return array('status'=>'deleted','objectClass'=>$class,'id'=>$id,'requestedFields'=>array(),'appliedFields'=>array(),'recalculatedFields'=>array(),'ignoredFields'=>array(),'rejectedFields'=>array(),'concurrencyUnchecked'=>false);}
  foreach($data as $field=>$value)$object->$field=$value;$control=method_exists($object,'control')?cleanApiMessage($object->control()):'OK';if($control!==''&&strtoupper($control)!=='OK')mcpJsonError(400,'validation_failed',$control);$new=!$object->id;$raw=$object->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'save_failed',cleanApiMessage($raw));$result=mcpOperationResult($new?'created':'updated',$class,$object,$data,array('concurrencyUnchecked'=>false));$saved=new $class($object->id);$result['saved']=array('id'=>(int)$saved->id,'_version'=>mcpObjectVersion($saved));return $result;
}
function mcpSteeringEffects(array $result): array {$effects=array();foreach($result['items']??array() as $item){$status=(string)($item['status']??'');if(!in_array($status,array('created','updated','deleted','existing'),true))continue;$effects[]=array('action'=>$status==='deleted'?'delete':($status==='created'?'create':'update'),'objectClass'=>$item['objectClass']??null,'id'=>$item['id']??null);}return $effects;}
function mcpSteeringBatch(array $items,string $mode,callable $executor,?callable $between=null): array {
  if(count($items)<1||count($items)>200)mcpJsonError(400,'invalid_batch','Steering actions require 1 to 200 items');if(!in_array($mode,array('atomic','best_effort'),true))mcpJsonError(400,'invalid_transaction_mode','transactionMode must be atomic or best_effort');$results=array();$previousCapture=$GLOBALS['mcpCaptureErrors']??false;if($mode==='atomic')Sql::beginTransaction();
  foreach($items as $index=>$item){if($mode==='best_effort')Sql::beginTransaction();$GLOBALS['mcpCaptureErrors']=true;try{if($between)$between($index);$entry=$executor($item,$index);$entry['index']=$index;$results[]=$entry;if($mode==='best_effort')Sql::commitTransaction();}catch(Throwable $error){
    if($mode==='best_effort')Sql::rollbackTransaction();$details=$error instanceof McpBridgeException?array_merge(array('code'=>$error->errorCode,'message'=>cleanApiMessage($error->getMessage())),$error->details):array('code'=>'steering_operation_failed','message'=>cleanApiMessage($error->getMessage()));$details=mcpSteeringFields($details,array('code','message','objectClass','id','expectedVersion','actualVersion','missingFields','invalidFields'));
    $results[]=array('index'=>$index,'status'=>'error','objectClass'=>$item['objectClass']??'SteeringInternal','id'=>$item['id']??null,'error'=>$details);
    if($mode==='atomic'){Sql::rollbackTransaction();foreach($results as &$rolledBack)if(($rolledBack['status']??'')!=='error'){$rolledBack['status']='rolled_back';$rolledBack['rejectedFields']=array_values(array_unique(array_merge($rolledBack['rejectedFields']??array(),$rolledBack['appliedFields']??array())));$rolledBack['appliedFields']=array();$rolledBack['recalculatedFields']=array();$rolledBack['saved']=array();}unset($rolledBack);return array('ok'=>false,'rolledBack'=>true,'transactionMode'=>$mode,'items'=>$results,'effects'=>array());}
  }finally{$GLOBALS['mcpCaptureErrors']=$previousCapture;}}
  if($mode==='atomic')Sql::commitTransaction();$result=array('ok'=>!count(array_filter($results,fn($r)=>($r['status']??'')==='error')),'rolledBack'=>false,'transactionMode'=>$mode,'items'=>$results);$result['effects']=mcpSteeringEffects($result);return $result;
}
function mcpSteeringNatural(string $class,array $criteria): object {return SqlElement::getSingleSqlElementFromCriteria($class,$criteria);}
function mcpSteeringStateRow(object $row): array {
  $raw=mcpObjectArray($row);$result=array('id'=>(int)$row->id,'_version'=>mcpObjectVersion($row),'objectClass'=>get_class($row));
  $fields=array('refType','refId','idProject','idKpiDefinition','idTestSession','idTestCase','idTicket','idMeeting','idAffectable','idResource','idUser','idClient','idVotingAttribution','idVotingAttributionRule','idRaciModel','idRaciRole','resourceType','resourceId','name','approved','disapproved','approvedDate','disapprovedDate','comment','thresholdValue','thresholdColor','situationType','date','sortOrder','idRunStatus','result','statusDateTime','value','totalValue','usedValue','leftValue','lastAttributionDate','endAttributionDate','idle');
  $ids=array('refId','idProject','idKpiDefinition','idTestSession','idTestCase','idTicket','idMeeting','idAffectable','idResource','idUser','idClient','idVotingAttribution','idVotingAttributionRule','idRaciModel','idRaciRole','resourceId','idRunStatus');$booleans=array('approved','disapproved','idle');$numbers=array('thresholdValue','value','totalValue','usedValue','leftValue');$dates=array('approvedDate','disapprovedDate','date','statusDateTime','lastAttributionDate','endAttributionDate');
  foreach($fields as $field){if(!array_key_exists($field,$raw))continue;$value=$raw[$field];if(in_array($field,$ids,true))$value=$value===null||$value===''?null:(int)$value;elseif(in_array($field,$booleans,true))$value=(bool)$value;elseif(in_array($field,$numbers,true))$value=(float)$value;elseif($field==='sortOrder')$value=(int)$value;elseif(in_array($field,$dates,true)&&$value==='')$value=null;$result[$field]=$value;}
  return $result;
}
function mcpSteeringOperation(string $class,array $item,array $criteria=array()): array {
  $object=!empty($item['id'])?new $class((int)$item['id']):($criteria?mcpSteeringNatural($class,$criteria):new $class());if(!empty($item['id'])&&!$object->id)mcpJsonError(404,'steering_target_not_found',"$class #{$item['id']} was not found");$operation=(string)($item['operation']??'upsert');if($operation==='upsert')$operation=$object->id?'update':'create';if($operation==='create'&&$object->id)mcpJsonError(409,'steering_duplicate','Record already exists',array('objectClass'=>$class,'id'=>(int)$object->id));if(in_array($operation,array('update','delete'),true)&&!$object->id)mcpJsonError(404,'steering_target_not_found',"$class target was not found");if($operation==='create')$object=new $class();return array($object,$operation);
}

function mcpSteeringBusinessAction(array $arguments,string $username,string $action): array {
  $allowed=array('Risk','Issue','Opportunity','Decision','Question','Acceptance','TestCase','TestSession','Meeting','PeriodicMeeting');$fields=array('name','idProject','idRiskType','idIssueType','idOpportunityType','idDecisionType','idQuestionType','idAcceptanceType','idTestCaseType','idTestSessionType','idMeetingType','idStatus','idResource','idUser','idSeverity','idLikelihood','idCriticality','idPriority','idBusinessFeature','idProduct','idVersion','idComponentVersion','idActivity','idTestCase','idRunStatus','externalReference','creationDate','creationDateTime','initialDueDate','actualDueDate','initialEndDate','actualEndDate','decisionDate','acceptanceDate','meetingDate','meetingStartTime','meetingEndTime','location','description','result','cause','impact','mitigationPlan','prerequisite','plannedWork','handled','done','cancelled','idle');
  return mcpSteeringBatch($arguments['items'],(string)($arguments['transactionMode']??'atomic'),function(array $item)use($allowed,$fields):array{$class=(string)$item['objectClass'];if(!in_array($class,$allowed,true))mcpJsonError(400,'unsupported_steering_class',"$class is not a Steering business class");list($object,$operation)=mcpSteeringOperation($class,$item);$data=$operation==='delete'?array():mcpSteeringFields($item,$fields);if($operation==='create'){if(property_exists($object,'creationDate')&&!array_key_exists('creationDate',$data))$data['creationDate']=date('Y-m-d');if(property_exists($object,'creationDateTime')&&!array_key_exists('creationDateTime',$data))$data['creationDateTime']=date('Y-m-d H:i:s');if(property_exists($object,'idUser')&&!array_key_exists('idUser',$data))$data['idUser']=(int)getSessionUser()->id;}return mcpSteeringSave($object,$operation,$item,$data,false);});
}
function mcpSteeringApprovalDecideAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['approvals'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$approver=new Approver((int)$item['id']);if(!$approver->id)mcpJsonError(404,'steering_target_not_found','Approver was not found');mcpSteeringTarget((string)$approver->refType,(int)$approver->refId,'update');$data=$item['decision']==='approved'?array('approved'=>1,'approvedDate'=>date('Y-m-d H:i'),'disapproved'=>0,'disapprovedDate'=>null,'disapprovedComment'=>null):array('approved'=>0,'disapproved'=>1,'disapprovedDate'=>date('Y-m-d H:i'),'disapprovedComment'=>$item['comment']??null);return mcpSteeringSave($approver,'update',$item,$data,true);});
}
function mcpSteeringApproverManageAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['approvers'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$criteria=array('refType'=>(string)$item['refType'],'refId'=>(int)$item['refId'],'idAffectable'=>(int)$item['idAffectable']);list($object,$operation)=mcpSteeringOperation('Approver',$item,$criteria);mcpSteeringTarget((string)$item['refType'],(int)$item['refId'],'update');$data=$operation==='delete'?array():$criteria+array('idle'=>!empty($item['idle'])?1:0);return mcpSteeringSave($object,$operation,$item,$data,true);});
}
function mcpSteeringChecklistAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['checklists'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{mcpSteeringTarget((string)$item['refType'],(int)$item['refId'],'update');$criteria=array('refType'=>(string)$item['refType'],'refId'=>(int)$item['refId']);list($checklist,$operation)=mcpSteeringOperation('Checklist',$item,$criteria);if($operation==='delete')return mcpSteeringSave($checklist,'delete',$item,array(),true);mcpSteeringTarget('ChecklistDefinition',(int)$item['definitionId'],'read');$result=mcpSteeringSave($checklist,$operation,$item,array('refType'=>$criteria['refType'],'refId'=>$criteria['refId'],'idChecklistDefinition'=>(int)$item['definitionId'],'comment'=>$item['comment']??null),true);foreach($item['lines']??array() as $line){$lineCriteria=array('idChecklist'=>(int)$checklist->id,'idChecklistDefinitionLine'=>(int)$line['definitionLineId']);$value=mcpSteeringNatural('ChecklistLine',$lineCriteria);if(!$value->id)$value=new ChecklistLine();$data=$lineCriteria+mcpSteeringFields($line,array('value01','value02','value03','value04','value05','comment'));if(count($data)>2){$data['idUser']=(int)getSessionUser()->id;$data['checkTime']=date('Y-m-d H:i:s');mcpSteeringSave($value,$value->id?'update':'create',$line,$data,true);}}$result['recalculatedFields']=array('ChecklistLine');return $result;});
}
function mcpSteeringChecklistDefinitionAction(array $arguments,string $username,string $action): array {
  $fields=array('name','title','check01','title01','check02','title02','check03','title03','check04','title04','check05','title05','sortOrder','exclusive','required');return mcpSteeringBatch($arguments['lines'],(string)($arguments['transactionMode']??'atomic'),function(array $item)use($fields):array{mcpSteeringTarget('ChecklistDefinition',(int)$item['definitionId'],'update');list($line,$operation)=mcpSteeringOperation('ChecklistDefinitionLine',$item);$data=$operation==='delete'?array():array('idChecklistDefinition'=>(int)$item['definitionId'])+mcpSteeringFields($item,$fields);return mcpSteeringSave($line,$operation,$item,$data,true);});
}
function mcpSteeringRaciAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['assignments'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{mcpSteeringTarget('Project',(int)$item['projectId'],'update');mcpSteeringTarget('RaciModel',(int)$item['modelId'],'read');$criteria=array('idProject'=>(int)$item['projectId'],'idRaciModel'=>(int)$item['modelId'],'idRaciRole'=>(int)$item['roleId'],'resourceType'=>'Affectable','resourceId'=>(int)$item['affectableId']);list($assignment,$operation)=mcpSteeringOperation('RaciAssignment',$item,$criteria);return mcpSteeringSave($assignment,$operation,$item,$operation==='delete'?array():$criteria,true);});
}
function mcpSteeringMeetingTeamAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['meetings'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$class=(string)$item['objectClass'];$meeting=mcpSteeringTarget($class,(int)$item['id'],'update');mcpSteeringVersion($meeting,$item,'update');$meetingDate=(string)($class==='PeriodicMeeting'?($meeting->periodicityEndDate?:date('Y-m-d')):($meeting->meetingDate?:date('Y-m-d')));$hours=0.0;if(!empty($meeting->meetingStartTime)&&!empty($meeting->meetingEndTime))$hours=max(0,(strtotime((string)$meeting->meetingEndTime)-strtotime((string)$meeting->meetingStartTime))/3600);$days=$hours/max(0.01,(float)Parameter::getGlobalParameter('dayTime'));$affectations=(new Affectation())->getSqlElementsFromCriteria(array('idProject'=>(int)$meeting->idProject,'idle'=>'0'));$created=0;foreach($affectations as $affectation){if(!empty($affectation->endDate)&&(string)$affectation->endDate<$meetingDate)continue;$resource=new Resource((int)$affectation->idResource,true);if(!$resource->id||$resource->idle)continue;$criteria=array('idResource'=>(int)$resource->id,'refType'=>$class,'refId'=>(int)$meeting->id);$assignment=mcpSteeringNatural('Assignment',$criteria);if($assignment->id)continue;$assignment=new Assignment();$work=array('assignedWork'=>$days,'realWork'=>0,'leftWork'=>$days,'plannedWork'=>$days,'notPlannedWork'=>0);foreach($criteria+$work+array('idProject'=>(int)$meeting->idProject,'rate'=>100,'idle'=>0) as $field=>$value)$assignment->$field=$value;$raw=$assignment->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'assignment_failed',cleanApiMessage($raw));$created++;}return array('status'=>$created?'updated':'existing','objectClass'=>$class,'id'=>(int)$meeting->id,'requestedFields'=>array('teamAffectations'),'appliedFields'=>$created?array('teamAffectations'):array(),'recalculatedFields'=>array('Assignment'),'ignoredFields'=>array(),'rejectedFields'=>array(),'saved'=>array('createdAssignments'=>$created,'_version'=>mcpObjectVersion(new $class($meeting->id))),'concurrencyUnchecked'=>false);});
}
function mcpSteeringMeetingLinkAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['links'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$meeting=mcpSteeringTarget('Meeting',(int)$item['meetingId'],'update');mcpSteeringVersion($meeting,array('expectedVersion'=>$item['meetingExpectedVersion']??''),'update');mcpSteeringTarget((string)$item['targetClass'],(int)$item['targetId'],'read');$criteria=array('ref1Type'=>(string)$item['targetClass'],'ref1Id'=>(int)$item['targetId'],'ref2Type'=>'Meeting','ref2Id'=>(int)$item['meetingId']);list($link,$operation)=mcpSteeringOperation('Link',$item,$criteria);return mcpSteeringSave($link,$operation,$item,$operation==='delete'?array():$criteria+array('creationDate'=>date('Y-m-d')),true);});
}
function mcpSteeringLiveMeetingAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['meetings'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$meeting=mcpSteeringTarget('Meeting',(int)$item['meetingId'],'update');mcpSteeringVersion($meeting,$item,'update');$live=mcpSteeringNatural('LiveMeeting',array('idMeeting'=>(int)$meeting->id));$liveItem=$live->id?array('expectedVersion'=>$item['liveExpectedVersion']??''):array();$param=$live->param?json_decode((string)$live->param,true):array();if(!is_array($param))$param=array();foreach($item['participants']??array() as $speaker){$resourceId=(int)$speaker['affectableId'];$assignment=mcpSteeringNatural('Assignment',array('refType'=>'Meeting','refId'=>(int)$meeting->id,'idResource'=>$resourceId));if(!$assignment->id)mcpJsonError(403,'forbidden',"Affectable #$resourceId is not assigned to this meeting");$current=is_array($param[$resourceId]??null)?$param[$resourceId]:array('name'=>SqlList::getNameFromId('Affectable',$resourceId));$param[$resourceId]=$current+array();$param[$resourceId]['time']=(float)$speaker['elapsedSeconds'];$param[$resourceId]['color']=(string)$speaker['color'];$param[$resourceId]['organizator']=(bool)$speaker['organizer'];$param[$resourceId]['canSpeak']=(bool)$speaker['canSpeak'];}if(array_key_exists('lastElapsedSeconds',$item))$param['lastTime']=(float)$item['lastElapsedSeconds'];if(array_key_exists('organizerElapsedSeconds',$item))$param['lastTimeOrganizator']=(float)$item['organizerElapsedSeconds'];$liveData=array('idMeeting'=>(int)$meeting->id,'result'=>$item['result']??$meeting->result,'param'=>$param?json_encode($param,JSON_UNESCAPED_SLASHES):null);mcpSteeringSave($live,$live->id?'update':'create',$liveItem,$liveData,true);$result=mcpSteeringSave($meeting,'update',$item,array('result'=>$liveData['result']),false);$result['recalculatedFields']=array('LiveMeeting');return $result;});
}
function mcpSteeringKpiAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['thresholds'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{mcpSteeringTarget('KpiDefinition',(int)$item['definitionId'],'update');list($threshold,$operation)=mcpSteeringOperation('KpiThreshold',$item);$data=$operation==='delete'?array():array('idKpiDefinition'=>(int)$item['definitionId'],'name'=>(string)$item['name'],'thresholdValue'=>$item['value'],'thresholdColor'=>(string)$item['color']);return mcpSteeringSave($threshold,$operation,$item,$data,true);});
}
function mcpSteeringSituationAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['situations'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$parent=mcpSteeringTarget((string)$item['refType'],(int)$item['refId'],'update');mcpSteeringVersion($parent,array('expectedVersion'=>$item['parentExpectedVersion']??''),'update');list($situation,$operation)=mcpSteeringOperation('Situation',$item);$data=$operation==='delete'?array():array('refType'=>(string)$item['refType'],'refId'=>(int)$item['refId'],'idUser'=>(int)getSessionUser()->id,'idProject'=>(int)($item['idProject']??$parent->idProject),'idResource'=>$item['idResource']??null,'name'=>(string)$item['name'],'situationType'=>(string)($item['situationType']??'income'),'date'=>(string)$item['date'],'comment'=>$item['comment']??null);$result=mcpSteeringSave($situation,$operation,$item,$data,true);$latest=(new Situation())->getSqlElementsFromCriteria(array('refType'=>(string)$item['refType'],'refId'=>(int)$item['refId']),false,null,'date desc',1,true);$current=$latest?reset($latest):null;$parent->idSituation=$current?(int)$current->id:null;$raw=$parent->save();if(getLastOperationStatus($raw)!=='OK')mcpJsonError(400,'parent_update_failed',cleanApiMessage($raw));$result['recalculatedFields']=array('idSituation');return $result;});
}
function mcpSteeringTestRunBatch(array $arguments,?int $jobId=null): array {
  return mcpSteeringBatch($arguments['runs'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{$session=mcpSteeringTarget('TestSession',(int)$item['sessionId'],'update');$criteria=array('idTestSession'=>(int)$item['sessionId'],'idTestCase'=>(int)$item['testCaseId']);list($run,$operation)=mcpSteeringOperation('TestCaseRun',$item,$criteria);if($operation!=='delete')mcpSteeringTarget('TestCase',(int)$item['testCaseId'],'read');$data=$operation==='delete'?array():$criteria+mcpSteeringFields($item,array('idTicket','comment','sortOrder','idRunStatus','result','idle'))+array('idUser'=>(int)getSessionUser()->id);if($operation==='update'&&isset($item['idRunStatus'])&&(int)$run->idRunStatus!==(int)$item['idRunStatus'])$data['statusDateTime']=date('Y-m-d H:i:s');$saved=mcpSteeringSave($run,$operation,$item,$data,true);if(method_exists($session,'updateDependencies'))$session->updateDependencies();$saved['recalculatedFields']=array('TestSession.dependencies');return $saved;},$jobId===null?null:function(int $index)use($jobId,$arguments):void{if(workerCancelled($jobId))throw new RuntimeException('cancelled');if($index%10===0)workerUpdate($jobId,'running',min(95,5+(int)(90*($index+1)/max(1,count($arguments['runs'])))));});
}
function mcpSteeringVotingAttributionAction(array $arguments,string $username,string $action): array {
  return mcpSteeringBatch($arguments['attributions'],(string)($arguments['transactionMode']??'atomic'),function(array $item):array{mcpSteeringTarget('Project',(int)$item['idProject'],'update');$rule=mcpSteeringTarget('VotingAttributionRule',(int)$item['ruleId'],'read');$party=(string)$item['partyType'];$criteria=array('idVotingAttributionRule'=>(int)$item['ruleId'],'refType'=>(string)$item['refType'],'idProject'=>(int)$item['idProject'],($party==='user'?'idUser':'idClient')=>(int)$item['partyId']);list($attribution,$operation)=mcpSteeringOperation('VotingAttribution',$item,$criteria);$total=(float)$item['totalValue'];if(!empty($rule->limitValue))$total=min($total,(float)$rule->limitValue);$used=$attribution->id?(float)$attribution->usedValue:0;$data=$operation==='delete'?array():$criteria+array('totalValue'=>$total,'usedValue'=>$used,'leftValue'=>$total-$used,'lastAttributionDate'=>$attribution->lastAttributionDate?:date('Y-m-d'),'endAttributionDate'=>$item['endDate']??null);return mcpSteeringSave($attribution,$operation,$item,$data,true);});
}
function mcpSteeringConsolidationAction(array $arguments,string $username,string $action): array {
  $mode=(string)$arguments['mode'];return mcpSteeringBatch($arguments['projects'],(string)($arguments['transactionMode']??'atomic'),function(array $item)use($mode,$arguments):array{$project=mcpSteeringTarget('Project',(int)$item['idProject'],'update');mcpSteeringVersion($project,$item,'update');$profile=(int)getSessionUser()->idProfile;$scope=in_array($mode,array('lock','unlock'),true)?'lockedImputation':'validationImputation';$right=mcpSteeringNatural('HabilitationOther',array('idProfile'=>$profile,'scope'=>$scope));if(!$right->id||($right->rightAccessCode??'NO')!=='YES')mcpJsonError(403,'forbidden',"$scope permission is required");$class=in_array($mode,array('lock','unlock'),true)?'LockedImputation':'ConsolidationValidation';$criteria=array('idProject'=>(int)$item['idProject'],'month'=>(string)$arguments['month']);$object=mcpSteeringNatural($class,$criteria);$operation=in_array($mode,array('cancel','unlock'),true)?'delete':($object->id?'update':'create');if($operation==='delete'&&!$object->id)return array('status'=>'existing','objectClass'=>$class,'id'=>null,'requestedFields'=>array(),'appliedFields'=>array(),'recalculatedFields'=>array(),'ignoredFields'=>array(),'rejectedFields'=>array(),'concurrencyUnchecked'=>false);$data=$operation==='delete'?array():$criteria+array('idResource'=>(int)getSessionUser()->id)+mcpSteeringFields($item,array('revenue','monthlyRevenue','validatedWork','realWork','realWorkConsumed','plannedWork','leftWork','margin'));return mcpSteeringSave($object,$operation,$item,$data,true);});
}
function mcpSteeringStateQueryAction(array $arguments,string $username,string $action): array {
  $domain=(string)$arguments['domain'];$parentClass=(string)$arguments['parentClass'];$parentId=(int)$arguments['parentId'];mcpSteeringTarget($parentClass,$parentId,'read');$map=array('approvers'=>array('Approver','refType','refId'),'checklists'=>array('Checklist','refType','refId'),'raci'=>array('RaciAssignment','idProject',null),'kpi_thresholds'=>array('KpiThreshold','idKpiDefinition',null),'situations'=>array('Situation','refType','refId'),'test_runs'=>array('TestCaseRun','idTestSession',null),'votes'=>array('Voting','refType','refId'),'voting_attributions'=>array('VotingAttribution','idProject',null),'live_meetings'=>array('LiveMeeting','idMeeting',null));if(!isset($map[$domain]))mcpJsonError(400,'unsupported_steering_domain','Unsupported Steering state domain');list($class,$field,$idField)=$map[$domain];$criteria=$idField===null?array($field=>$parentId):array($field=>$parentClass,$idField=>$parentId);$rows=(new $class())->getSqlElementsFromCriteria($criteria,false,null,'id asc',(int)($arguments['pageSize']??100),true);$items=array();foreach($rows as $row)$items[]=mcpSteeringStateRow($row);return array('ok'=>true,'domain'=>$domain,'parentClass'=>$parentClass,'parentId'=>$parentId,'count'=>count($items),'items'=>$items,'effects'=>array());
}
function mcpSteeringPreview(array $arguments,string $username,string $action): array {
  foreach(array('items','approvals','approvers','checklists','lines','assignments','meetings','links','thresholds','situations','runs','votes','attributions','projects') as $key)if(isset($arguments[$key])&&is_array($arguments[$key])){$items=array();foreach(array_slice($arguments[$key],0,200) as $index=>$item)$items[]=array('index'=>$index,'operation'=>$item['operation']??$item['decision']??null,'objectClass'=>$item['objectClass']??$item['refType']??null,'id'=>$item['id']??null,'expectedVersion'=>$item['expectedVersion']??null);return array('count'=>count($arguments[$key]),'transactionMode'=>$arguments['transactionMode']??'atomic','items'=>$items);}return array('count'=>0,'transactionMode'=>$arguments['transactionMode']??'atomic','items'=>array());
}
