<?php
declare(strict_types=1);

function mcpSteeringModuleDescriptor(): array {
  $id=array('type'=>'integer','minimum'=>1);$nullableId=array('type'=>array('integer','null'),'minimum'=>1);$version=array('type'=>'string','minLength'=>1,'maxLength'=>200);$boolean=array('type'=>'boolean');$text=array('type'=>array('string','null'),'maxLength'=>20000);$short=array('type'=>array('string','null'),'maxLength'=>500);$date=array('type'=>array('string','null'),'pattern'=>'^\d{4}-\d{2}-\d{2}$');$dateTime=array('type'=>array('string','null'),'maxLength'=>40);$number=array('type'=>'number');$operation=array('type'=>'string','enum'=>array('create','update','upsert','delete'));$transaction=array('type'=>'string','enum'=>array('atomic','best_effort'));
  $saved=mcpObjectSchema(array('id'=>$id,'_version'=>$version,'createdAssignments'=>array('type'=>'integer','minimum'=>0)),array(),false);$error=mcpObjectSchema(array('code'=>array('type'=>'string'),'message'=>array('type'=>'string'),'objectClass'=>array('type'=>'string'),'id'=>$id,'expectedVersion'=>$version,'actualVersion'=>$version,'missingFields'=>array('type'=>'array','items'=>array('type'=>'string')),'invalidFields'=>array('type'=>'array','items'=>array('type'=>'string'))),array('code','message'),false);
  $itemResult=mcpObjectSchema(array('index'=>array('type'=>'integer','minimum'=>0),'status'=>array('type'=>'string','enum'=>array('created','updated','deleted','existing','invalid','rolled_back','error')),'objectClass'=>array('type'=>'string'),'id'=>array('type'=>array('integer','null')),'requestedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'appliedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'recalculatedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'ignoredFields'=>array('type'=>'array','items'=>array('type'=>'string')),'rejectedFields'=>array('type'=>'array','items'=>array('type'=>'string')),'saved'=>$saved,'error'=>$error,'concurrencyUnchecked'=>$boolean),array('status','objectClass'),false);
  $effect=mcpObjectSchema(array('action'=>array('type'=>'string','enum'=>array('create','update','delete')),'objectClass'=>array('type'=>array('string','null')),'id'=>array('type'=>array('integer','null'))),array('action','objectClass','id'),false);
  $batchResult=mcpObjectSchema(array('ok'=>$boolean,'rolledBack'=>$boolean,'transactionMode'=>$transaction,'items'=>array('type'=>'array','maxItems'=>200,'items'=>$itemResult),'effects'=>array('type'=>'array','maxItems'=>400,'items'=>$effect)),array('ok','rolledBack','transactionMode','items','effects'),false);
  $preview=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpSteeringActionAvailable','permissionClasses'=>$classes,'transaction'=>'atomic','batchLimit'=>200,'preview'=>'mcpSteeringPreview','sideEffectClassification'=>'destructive'),$extra);};
  $options=function(array $classes,array $extra=array()):array{return array_merge(array('availability'=>'mcpSteeringActionAvailable','permissionClasses'=>$classes,'transaction'=>'atomic','batchLimit'=>200,'sideEffectClassification'=>'write'),$extra);};
  $batch=function(string $key,array $item,array $required)use($transaction):array{return mcpObjectSchema(array($key=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$item),'transactionMode'=>$transaction),$required,false);};
  $existingCondition=function(string $idField='id'):array{return array('allOf'=>array(array('if'=>array('properties'=>array('operation'=>array('enum'=>array('update','delete')))),'then'=>array('required'=>array($idField,'expectedVersion')))));};

  $business=mcpObjectSchema(array('objectClass'=>array('type'=>'string','enum'=>array('Risk','Issue','Opportunity','Decision','Question','Acceptance','TestCase','TestSession','Meeting','PeriodicMeeting')),'operation'=>$operation,'id'=>$id,'expectedVersion'=>$version,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'idProject'=>$nullableId,'idRiskType'=>$nullableId,'idIssueType'=>$nullableId,'idOpportunityType'=>$nullableId,'idDecisionType'=>$nullableId,'idQuestionType'=>$nullableId,'idAcceptanceType'=>$nullableId,'idTestCaseType'=>$nullableId,'idTestSessionType'=>$nullableId,'idMeetingType'=>$nullableId,'idStatus'=>$nullableId,'idResource'=>$nullableId,'idSeverity'=>$nullableId,'idLikelihood'=>$nullableId,'idCriticality'=>$nullableId,'idPriority'=>$nullableId,'idBusinessFeature'=>$nullableId,'idProduct'=>$nullableId,'idVersion'=>$nullableId,'idComponentVersion'=>$nullableId,'idActivity'=>$nullableId,'idTestCase'=>$nullableId,'idRunStatus'=>$nullableId,'externalReference'=>$short,'creationDate'=>$date,'creationDateTime'=>$dateTime,'initialDueDate'=>$date,'actualDueDate'=>$date,'initialEndDate'=>$date,'actualEndDate'=>$date,'decisionDate'=>$date,'acceptanceDate'=>$date,'meetingDate'=>$date,'meetingStartTime'=>$short,'meetingEndTime'=>$short,'location'=>$short,'description'=>$text,'result'=>$text,'cause'=>$text,'impact'=>$text,'mitigationPlan'=>$text,'prerequisite'=>$text,'plannedWork'=>$number,'handled'=>$boolean,'done'=>$boolean,'cancelled'=>$boolean,'idle'=>$boolean),array('objectClass','operation'),false)+$existingCondition();
  $approval=mcpObjectSchema(array('id'=>$id,'decision'=>array('type'=>'string','enum'=>array('approved','disapproved')),'comment'=>$text,'expectedVersion'=>$version),array('id','decision','expectedVersion'),false);
  $approver=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'idAffectable'=>$id,'idle'=>$boolean,'expectedVersion'=>$version),array('operation','refType','refId','idAffectable'),false)+$existingCondition();
  $checkLine=mcpObjectSchema(array('definitionLineId'=>$id,'value01'=>$boolean,'value02'=>$boolean,'value03'=>$boolean,'value04'=>$boolean,'value05'=>$boolean,'comment'=>$text,'expectedVersion'=>$version),array('definitionLineId'),false);
  $checklist=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'definitionId'=>$id,'comment'=>$text,'lines'=>array('type'=>'array','maxItems'=>200,'items'=>$checkLine),'expectedVersion'=>$version),array('operation','refType','refId'),false)+$existingCondition();
  $definitionLine=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'definitionId'=>$id,'name'=>array('type'=>'string','maxLength'=>500),'title'=>$short,'check01'=>$boolean,'title01'=>$short,'check02'=>$boolean,'title02'=>$short,'check03'=>$boolean,'title03'=>$short,'check04'=>$boolean,'title04'=>$short,'check05'=>$boolean,'title05'=>$short,'sortOrder'=>array('type'=>'integer','minimum'=>0),'exclusive'=>$boolean,'required'=>$boolean,'expectedVersion'=>$version),array('operation','definitionId'),false)+$existingCondition();
  $raci=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'projectId'=>$id,'modelId'=>$id,'roleId'=>$id,'affectableId'=>$id,'expectedVersion'=>$version),array('operation','projectId','modelId','roleId','affectableId'),false)+$existingCondition();
  $meetingTeam=mcpObjectSchema(array('objectClass'=>array('type'=>'string','enum'=>array('Meeting','PeriodicMeeting')),'id'=>$id,'expectedVersion'=>$version),array('objectClass','id','expectedVersion'),false);
  $meetingLink=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'meetingId'=>$id,'meetingExpectedVersion'=>$version,'targetClass'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'targetId'=>$id,'expectedVersion'=>$version),array('operation','meetingId','meetingExpectedVersion','targetClass','targetId'),false)+$existingCondition();
  $speaker=mcpObjectSchema(array('affectableId'=>$id,'elapsedSeconds'=>array('type'=>'number','minimum'=>0),'color'=>array('type'=>'string','minLength'=>1,'maxLength'=>30),'organizer'=>$boolean,'canSpeak'=>$boolean),array('affectableId','elapsedSeconds','color','organizer','canSpeak'),false);$liveMeeting=mcpObjectSchema(array('meetingId'=>$id,'result'=>$text,'participants'=>array('type'=>'array','maxItems'=>200,'items'=>$speaker),'lastElapsedSeconds'=>array('type'=>'number','minimum'=>0),'organizerElapsedSeconds'=>array('type'=>'number','minimum'=>0),'expectedVersion'=>$version,'liveExpectedVersion'=>$version),array('meetingId','expectedVersion'),false);
  $threshold=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'definitionId'=>$id,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'value'=>$number,'color'=>array('type'=>'string','pattern'=>'^#[0-9A-Fa-f]{6}$'),'expectedVersion'=>$version),array('operation','definitionId'),false)+$existingCondition();
  $situation=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'parentExpectedVersion'=>$version,'idProject'=>$nullableId,'idResource'=>$nullableId,'name'=>array('type'=>'string','minLength'=>1,'maxLength'=>500),'situationType'=>array('type'=>'string','enum'=>array('income','expense')),'date'=>$dateTime,'comment'=>$text,'expectedVersion'=>$version),array('operation','refType','refId','parentExpectedVersion'),false)+$existingCondition();
  $run=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'sessionId'=>$id,'testCaseId'=>$id,'idTicket'=>$nullableId,'comment'=>$text,'sortOrder'=>array('type'=>'integer','minimum'=>0),'idRunStatus'=>$nullableId,'result'=>$text,'idle'=>$boolean,'expectedVersion'=>$version),array('operation','sessionId','testCaseId'),false)+$existingCondition();
  $vote=mcpObjectSchema(array('operation'=>array('type'=>'string','enum'=>array('cast','retract')),'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'refId'=>$id,'partyType'=>array('type'=>'string','enum'=>array('user','client')),'partyId'=>$nullableId,'attributionId'=>$id,'attributionExpectedVersion'=>$version,'value'=>$number,'note'=>$text,'privacyId'=>$nullableId,'notify'=>$boolean,'expectedVersion'=>$version,'noteExpectedVersion'=>$version),array('operation','refType','refId','partyType','attributionId','attributionExpectedVersion','value'),false);
  $attribution=mcpObjectSchema(array('operation'=>$operation,'id'=>$id,'ruleId'=>$id,'refType'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'idProject'=>$id,'partyType'=>array('type'=>'string','enum'=>array('user','client')),'partyId'=>$id,'totalValue'=>$number,'endDate'=>$date,'expectedVersion'=>$version),array('operation','ruleId','refType','idProject','partyType','partyId','totalValue'),false)+$existingCondition();
  $consolidation=mcpObjectSchema(array('idProject'=>$id,'expectedVersion'=>$version,'revenue'=>$number,'monthlyRevenue'=>$number,'validatedWork'=>$number,'realWork'=>$number,'realWorkConsumed'=>$number,'plannedWork'=>$number,'leftWork'=>$number,'margin'=>$number),array('idProject','expectedVersion'),false);
  $stateItem=mcpObjectSchema(array('id'=>$id,'_version'=>$version,'objectClass'=>array('type'=>'string'),'refType'=>$short,'refId'=>$nullableId,'idProject'=>$nullableId,'idKpiDefinition'=>$nullableId,'idTestSession'=>$nullableId,'idTestCase'=>$nullableId,'idTicket'=>$nullableId,'idMeeting'=>$nullableId,'idAffectable'=>$nullableId,'idResource'=>$nullableId,'idUser'=>$nullableId,'idClient'=>$nullableId,'idVotingAttribution'=>$nullableId,'idVotingAttributionRule'=>$nullableId,'idRaciModel'=>$nullableId,'idRaciRole'=>$nullableId,'resourceType'=>$short,'resourceId'=>$nullableId,'name'=>$short,'approved'=>$boolean,'disapproved'=>$boolean,'approvedDate'=>$dateTime,'disapprovedDate'=>$dateTime,'comment'=>$text,'thresholdValue'=>$number,'thresholdColor'=>$short,'situationType'=>$short,'date'=>$dateTime,'sortOrder'=>array('type'=>'integer'),'idRunStatus'=>$nullableId,'result'=>$text,'statusDateTime'=>$dateTime,'value'=>$number,'totalValue'=>$number,'usedValue'=>$number,'leftValue'=>$number,'lastAttributionDate'=>$date,'endAttributionDate'=>$date,'idle'=>$boolean),array('id','_version','objectClass'),false);
  $stateResult=mcpObjectSchema(array('ok'=>$boolean,'domain'=>array('type'=>'string'),'parentClass'=>array('type'=>'string'),'parentId'=>$id,'count'=>array('type'=>'integer','minimum'=>0),'items'=>array('type'=>'array','maxItems'=>200,'items'=>$stateItem),'effects'=>array('type'=>'array','maxItems'=>0,'items'=>$effect)),array('ok','domain','parentClass','parentId','count','items','effects'),false);

  return array('id'=>'steering','version'=>'4.0.0','dependencies'=>array('core','configuration','planning','tools'),'actions'=>array(
    'steering.state.query'=>mcpActionSpec(mcpObjectSchema(array('domain'=>array('type'=>'string','enum'=>array('approvers','checklists','raci','kpi_thresholds','situations','test_runs','votes','voting_attributions','live_meetings')),'parentClass'=>array('type'=>'string','pattern'=>'^[A-Za-z][A-Za-z0-9_]{0,99}$'),'parentId'=>$id,'pageSize'=>array('type'=>'integer','minimum'=>1,'maximum'=>200)),array('domain','parentClass','parentId'),false),$stateResult,'read',false,'mcpSteeringStateQueryAction',array(),'steering.state.query',$options(array('Project'),array('transaction'=>'none','sideEffectClassification'=>'read'))),
    'steering.business.manage'=>mcpActionSpec($batch('items',$business,array('items')),$batchResult,'destructive',false,'mcpSteeringBusinessAction',array(),'steering.business.manage',$preview(array('Risk','Issue','Opportunity','Decision','Question','Acceptance','TestCase','TestSession','Meeting','PeriodicMeeting'))),
    'steering.approval.decide'=>mcpActionSpec($batch('approvals',$approval,array('approvals')),$batchResult,'write',false,'mcpSteeringApprovalDecideAction',array('tool:approveItem'),'steering.approval.decide',$options(array('Approver'))),
    'steering.approver.manage'=>mcpActionSpec($batch('approvers',$approver,array('approvers')),$batchResult,'destructive',false,'mcpSteeringApproverManageAction',array('tool:saveApprover','tool:removeApprover'),'steering.approver.manage',$preview(array('Approver'))),
    'steering.checklist.update'=>mcpActionSpec($batch('checklists',$checklist,array('checklists')),$batchResult,'destructive',false,'mcpSteeringChecklistAction',array('tool:dynamicDialogChecklist','tool:saveChecklist'),'steering.checklist.update',$preview(array('Checklist','ChecklistDefinition'))),
    'steering.checklist_definition.manage'=>mcpActionSpec($batch('lines',$definitionLine,array('lines')),$batchResult,'destructive',false,'mcpSteeringChecklistDefinitionAction',array('tool:saveChecklistDefinitionLine','tool:removeChecklistDefinitionLine'),'steering.checklist-definition.manage',$preview(array('ChecklistDefinition'))),
    'steering.raci.update'=>mcpActionSpec($batch('assignments',$raci,array('assignments')),$batchResult,'destructive',false,'mcpSteeringRaciAction',array('tool:saveRaciAssignment','tool:removeRaciAssignment'),'steering.raci.update',$preview(array('Project','RaciModel'))),
    'steering.meeting.assign_team'=>mcpActionSpec($batch('meetings',$meetingTeam,array('meetings')),$batchResult,'write',false,'mcpSteeringMeetingTeamAction',array('tool:assignTeamForMeeting'),'steering.meeting.assign-team',$options(array('Meeting','PeriodicMeeting'))),
    'steering.meeting.link'=>mcpActionSpec($batch('links',$meetingLink,array('links')),$batchResult,'destructive',false,'mcpSteeringMeetingLinkAction',array('view:liveMeetingViewBottom'),'steering.meeting.link',$preview(array('Meeting','Link'))),
    'steering.meeting.live_update'=>mcpActionSpec($batch('meetings',$liveMeeting,array('meetings')),$batchResult,'write',false,'mcpSteeringLiveMeetingAction',array('tool:liveMeetingUpdate','view:liveMeetingView'),'steering.meeting.live-update',$options(array('Meeting'))),
    'steering.kpi_threshold.manage'=>mcpActionSpec($batch('thresholds',$threshold,array('thresholds')),$batchResult,'destructive',false,'mcpSteeringKpiAction',array('tool:saveKpiThreshold','tool:removeKpiThreshold'),'steering.kpi-threshold.manage',$preview(array('KpiDefinition'))),
    'steering.situation.manage'=>mcpActionSpec($batch('situations',$situation,array('situations')),$batchResult,'destructive',false,'mcpSteeringSituationAction',array('tool:saveSituation'),'steering.situation.manage',$preview(array('Risk','Issue','Opportunity','Decision'))),
    'steering.test_run.execute'=>mcpActionSpec($batch('runs',$run,array('runs')),$batchResult,'destructive',true,'mcpSteeringTestRunWorker',array('tool:saveTestCaseRun','tool:removeTestCaseRun','tool:saveTcrData'),'steering.test-run.execute',$preview(array('TestSession','TestCase'),array('transaction'=>'worker','retryPolicy'=>'recovery_required'))),
    'steering.voting.cast'=>mcpActionSpec($batch('votes',$vote,array('votes')),$batchResult,'external',true,'mcpSteeringVotingWorker',array('tool:saveAddVote','tool:saveNoteStreamVote'),'steering.voting.cast',$preview(array('VotingUseRule'),array('transaction'=>'worker','retryPolicy'=>'recovery_required','sideEffectClassification'=>'external'))),
    'steering.voting.attribution_manage'=>mcpActionSpec($batch('attributions',$attribution,array('attributions')),$batchResult,'administrative',false,'mcpSteeringVotingAttributionAction',array('tool:saveVotingAttributionVote'),'steering.voting.attribution-manage',$preview(array('VotingAttributionRule','Project'),array('sideEffectClassification'=>'administrative'))),
    'steering.consolidation.validate'=>mcpActionSpec(mcpObjectSchema(array('mode'=>array('type'=>'string','enum'=>array('validate','cancel','lock','unlock')),'month'=>array('type'=>'string','pattern'=>'^\d{4}-\d{2}$'),'projects'=>array('type'=>'array','minItems'=>1,'maxItems'=>200,'items'=>$consolidation),'transactionMode'=>$transaction),array('mode','month','projects'),false),$batchResult,'administrative',false,'mcpSteeringConsolidationAction',array('tool:saveConsolidationValidation'),'steering.consolidation.validate',$preview(array('Project'),array('sideEffectClassification'=>'administrative')))
  ));
}
